import type { Style, StyleProperty, StyleValue } from "../schema";
import { toValue, type TransformValue } from "./to-value";
import { toProperty } from "./to-property";

type Declaration = {
  breakpoint: string;
  selector: string;
  property: StyleProperty;
  value: StyleValue;
};

type DeclarationKey = Omit<Declaration, "value">;

const getDeclarationKey = (declaraionKey: DeclarationKey) => {
  const { breakpoint, selector, property } = declaraionKey;
  return `${breakpoint}:${selector}:${property}`;
};

/**
 * Universal style rule with nested selectors and media queries support
 * Rules are generated by each media query
 * and heavily cached to avoid complex computation
 *
 * selector {
 *   \@media breakpoint {
 *     &selector {
 *       property: value
 *     }
 *   }
 * }
 */
export class NestingRule {
  #selector: string;
  // use map to avoid duplicated properties
  #declarations = new Map<string, Declaration>();
  // cached generated rule by breakpoint
  #cache = new Map<
    string,
    { generated: string; indent: number; transformValue?: TransformValue }
  >();
  constructor(selector: string) {
    this.#selector = selector;
  }
  getSelector() {
    return this.#selector;
  }
  setDeclaration(declaration: Declaration) {
    this.#declarations.set(getDeclarationKey(declaration), declaration);
    this.#cache.delete(declaration.breakpoint);
  }
  deleteDeclaration(declaration: DeclarationKey) {
    this.#declarations.delete(getDeclarationKey(declaration));
    this.#cache.delete(declaration.breakpoint);
  }
  getDeclarations() {
    return this.#declarations.values();
  }
  generateRules({
    breakpoint,
    indent = 0,
    transformValue,
  }: {
    breakpoint: string;
    indent?: number;
    transformValue?: TransformValue;
  }) {
    const cached = this.#cache.get(breakpoint);
    // invalidate cache when indent and value transformer are changed
    if (
      cached &&
      cached.indent === indent &&
      cached.transformValue === transformValue
    ) {
      return cached.generated;
    }
    const spaces = " ".repeat(indent);
    const linesBySelector = new Map<string, string>();
    for (const declaration of this.#declarations.values()) {
      // generate declarations only for specified breakpoint
      if (declaration.breakpoint !== breakpoint) {
        continue;
      }
      const { selector: nestedSelector, property, value } = declaration;
      const selector = `${this.#selector}${nestedSelector}`;
      const lines = linesBySelector.get(selector) ?? "";
      const propertyString = toProperty(property);
      const valueString = toValue(value, transformValue);
      const line = `${spaces}  ${propertyString}: ${valueString}`;
      linesBySelector.set(selector, lines === "" ? line : `${lines};\n${line}`);
    }
    // sort by selector to put values without nested selector first
    const generated = Array.from(linesBySelector)
      .sort(([leftSelector], [rightSelector]) =>
        leftSelector.localeCompare(rightSelector)
      )
      .map(
        ([selector, lines]) => `${spaces}${selector} {\n${lines}\n${spaces}}\n`
      )
      .join("")
      .trimEnd();
    this.#cache.set(breakpoint, { generated, indent, transformValue });
    return generated;
  }
}

export class StylePropertyMap {
  #styleMap: Map<StyleProperty, StyleValue | undefined> = new Map();
  #isDirty = true;
  #string = "";
  #indent = 0;
  #transformValue?: TransformValue;
  #onChange?: () => void;
  constructor(
    style: Style,
    transformValue?: TransformValue,
    onChange?: () => void
  ) {
    this.#transformValue = transformValue;
    this.#onChange = onChange;
    let property: StyleProperty;
    for (property in style) {
      this.#styleMap.set(property, style[property]);
    }
  }
  setTransformer(transformValue: TransformValue) {
    this.#transformValue = transformValue;
  }
  set(property: StyleProperty, value?: StyleValue) {
    this.#styleMap.set(property, value);
    this.#isDirty = true;
    this.#onChange?.();
  }
  get(property: StyleProperty) {
    return this.#styleMap.get(property);
  }
  has(property: StyleProperty) {
    return this.#styleMap.has(property);
  }
  get size() {
    return this.#styleMap.size;
  }
  keys() {
    return this.#styleMap.keys();
  }
  delete(property: StyleProperty) {
    this.#styleMap.delete(property);
    this.#isDirty = true;
    this.#onChange?.();
  }
  clear() {
    this.#styleMap.clear();
    this.#isDirty = true;
    this.#onChange?.();
  }
  toString({ indent = 0 } = {}) {
    if (this.#isDirty === false && indent === this.#indent) {
      return this.#string;
    }
    this.#indent = indent;
    const block: Array<string> = [];
    const spaces = " ".repeat(indent);
    for (const [property, value] of this.#styleMap) {
      if (value === undefined) {
        continue;
      }
      block.push(
        `${spaces}${toProperty(property)}: ${toValue(
          value,
          this.#transformValue
        )}`
      );
    }
    this.#string = block.join(";\n");
    this.#isDirty = false;
    return this.#string;
  }
}

export class StyleRule {
  styleMap;
  selectorText;
  constructor(
    selectorText: string,
    style: StylePropertyMap | Style,
    transformValue?: TransformValue,
    onChange?: () => void
  ) {
    this.selectorText = selectorText;
    this.styleMap =
      style instanceof StylePropertyMap
        ? style
        : new StylePropertyMap(style, transformValue, onChange);
  }
  get cssText() {
    return this.toString();
  }
  toString(options = { indent: 0 }) {
    const spaces = " ".repeat(options.indent);
    return `${spaces}${this.selectorText} {\n${this.styleMap.toString({
      indent: options.indent + 2,
    })}\n${spaces}}`;
  }
}

export type MediaRuleOptions = {
  minWidth?: number;
  maxWidth?: number;
  mediaType?: "all" | "screen" | "print";
};

export class MediaRule {
  #name: string;
  options: MediaRuleOptions;
  rules: Map<string, StyleRule | PlaintextRule>;
  #mediaType;
  constructor(name: string, options: MediaRuleOptions = {}) {
    this.#name = name;
    this.options = options;
    this.rules = new Map();
    this.#mediaType = options.mediaType ?? "all";
  }
  insertRule(rule: StyleRule | PlaintextRule) {
    this.rules.set(
      rule instanceof StyleRule ? rule.selectorText : rule.cssText,
      rule
    );
    return rule;
  }
  get cssText() {
    return this.toString();
  }
  toString() {
    return this.generateRule({ nestingRules: [] });
  }
  generateRule({
    nestingRules,
    transformValue,
  }: {
    nestingRules: NestingRule[];
    transformValue?: TransformValue;
  }) {
    if (this.rules.size === 0 && nestingRules.length === 0) {
      return "";
    }
    const rules = [];
    for (const rule of this.rules.values()) {
      rules.push(rule.toString({ indent: 2 }));
    }
    for (const rule of nestingRules) {
      const generatedRule = rule.generateRules({
        breakpoint: this.#name,
        indent: 2,
        transformValue,
      });
      if (generatedRule !== "") {
        rules.push(generatedRule);
      }
    }
    let conditionText = "";
    const { minWidth, maxWidth } = this.options;
    if (minWidth !== undefined) {
      conditionText = ` and (min-width: ${minWidth}px)`;
    }
    if (maxWidth !== undefined) {
      conditionText += ` and (max-width: ${maxWidth}px)`;
    }
    return `@media ${this.#mediaType}${conditionText} {\n${rules.join(
      "\n"
    )}\n}`;
  }
}

export class PlaintextRule {
  cssText;
  styleMap: StylePropertyMap;
  constructor(cssText: string) {
    this.cssText = cssText;
    this.styleMap = new StylePropertyMap({});
  }
  toString() {
    return this.cssText;
  }
}

export type FontFaceOptions = {
  fontFamily: string;
  fontStyle?: "normal" | "italic" | "oblique";
  fontWeight?: number | string;
  fontDisplay: "swap" | "auto" | "block" | "fallback" | "optional";
  src: string;
};

export class FontFaceRule {
  options: FontFaceOptions;
  constructor(options: FontFaceOptions) {
    this.options = options;
  }
  get cssText() {
    return this.toString();
  }
  toString() {
    const decls = [];
    const { fontFamily, fontStyle, fontWeight, fontDisplay, src } =
      this.options;
    const value = toValue(
      { type: "fontFamily", value: [fontFamily] },
      // Avoids adding a fallback automatically which needs to happen for font family in general but not for font face.
      (value) => value
    );
    decls.push(`font-family: ${value}`);
    decls.push(`font-style: ${fontStyle}`);
    decls.push(`font-weight: ${fontWeight}`);
    decls.push(`font-display: ${fontDisplay}`);
    decls.push(`src: ${src}`);
    return `@font-face {\n  ${decls.join("; ")};\n}`;
  }
}

export type AnyRule = StyleRule | MediaRule | PlaintextRule | FontFaceRule;
