import { readFile } from "node:fs/promises";
import { cwd } from "node:process";
import { join } from "node:path";
import * as httpClient from "@webstudio-is/http-client";
import {
  GLOBAL_CONFIG_FILE,
  LOCAL_CONFIG_FILE,
  jsonToGlobalConfig,
  jsonToLocalConfig,
} from "../config";
import { isFileExists } from "../fs-utils";
import { HandledCliError } from "../errors";
import { getLocalAssetPath, LOCAL_ASSETS_DIR } from "../asset-files";
import { apiCompatibilityHeaders } from "./api";
import type { CommonYargsArgv } from "./yargs-types";

const apiCommandHttpClient = httpClient;

type ApiCommandDependencies = typeof apiCommandHttpClient & {
  isFileExists: typeof isFileExists;
  readFile: typeof readFile;
};

const defaultDependencies: ApiCommandDependencies = {
  ...apiCommandHttpClient,
  isFileExists,
  readFile,
};

export const apiCommandOptions = (yargs: CommonYargsArgv) =>
  yargs.option("json", {
    type: "boolean",
    describe: "Required. Print a machine-readable JSON response to stdout",
    default: false,
  });

const requiredInputOption = (yargs: CommonYargsArgv, describe: string) =>
  yargs.option("input", {
    type: "string",
    describe,
    demandOption: true,
  });

const confirmOption = (yargs: CommonYargsArgv, describe: string) =>
  yargs.option("confirm", {
    type: "boolean",
    describe,
    demandOption: true,
  });

export const snapshotCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs)
    .option("include", {
      type: "array",
      string: true,
      describe:
        "Comma-separated build data namespaces to include, such as pages, instances, styles, assets, resources, variables",
    })
    .option("version", {
      type: "number",
      describe:
        "Read a specific numeric dev build version instead of the latest dev build",
    })
    .example(
      "$0 snapshot --include pages,instances,styles --json",
      "Read selected build namespaces from the configured project"
    );

export const applyPatchCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs)
    .option("base-version", {
      type: "number",
      describe:
        "Required. Expected current build version; the write fails if the project has changed",
      demandOption: true,
    })
    .option("input", {
      type: "string",
      describe:
        "Required. JSON file containing BuildPatchTransaction[] or { transactions } generated from Builder store patches",
      demandOption: true,
    })
    .example(
      "$0 apply-patch --base-version 42 --input patch.json --json",
      "Apply Builder patch transactions with optimistic version checking"
    );

export const pageCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs).option("page", {
    type: "string",
    describe: "Required page id",
    demandOption: true,
  });

export const pathCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs).option("path", {
    type: "string",
    describe: "Required page path, for example /pricing",
    demandOption: true,
  });

export const pagesCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs).option("include-folders", {
    type: "boolean",
    describe: "Include folder records alongside page summaries",
  });

export const createPageCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs)
    .option("page", {
      type: "string",
      describe: "Optional page id to create; generated by Builder when omitted",
    })
    .option("name", {
      type: "string",
      describe: "Required page name shown in Builder",
      demandOption: true,
    })
    .option("path", {
      type: "string",
      describe: "Required page URL path, for example /pricing",
      demandOption: true,
    })
    .option("title", {
      type: "string",
      describe: "Page title expression; defaults to --name",
    })
    .option("parent-folder", {
      type: "string",
      describe: "Folder id where the page should be created",
    });

export const updatePageCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs)
    .option("page", {
      type: "string",
      describe: "Required page id to update",
      demandOption: true,
    })
    .option("name", {
      type: "string",
      describe: "Update page name shown in Builder",
    })
    .option("path", {
      type: "string",
      describe: "Update page URL path, for example /pricing",
    })
    .option("title", {
      type: "string",
      describe: "Update page title expression",
    })
    .option("description", {
      type: "string",
      describe: "Update page meta description expression",
    })
    .option("language", {
      type: "string",
      describe: "Update page language expression",
    })
    .option("redirect", {
      type: "string",
      describe: "Update page redirect expression",
    })
    .option("social-image-url", {
      type: "string",
      describe: "Update page social image URL expression",
    })
    .option("social-image-asset", {
      type: "string",
      describe: "Update page social image asset id",
    })
    .option("exclude-page-from-search", {
      type: "boolean",
      describe: "Set whether search engines should skip this page",
    })
    .option("document-type", {
      choices: ["html", "xml", "text"] as const,
      describe: "Set page document type",
    })
    .option("content", {
      type: "string",
      describe: "Update page custom document content",
    })
    .option("parent-folder", {
      type: "string",
      describe: "Move page into this folder id",
    });

export const deletePageCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs).option("page", {
    type: "string",
    describe: "Required page id to delete",
    demandOption: true,
  });

export const duplicatePageCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs)
    .option("page", {
      type: "string",
      describe: "Required page id to duplicate",
      demandOption: true,
    })
    .option("name", {
      type: "string",
      describe: "Optional name for the duplicated page",
    })
    .option("path", {
      type: "string",
      describe: "Optional URL path for the duplicated page",
    })
    .option("parent-folder", {
      type: "string",
      describe: "Folder id where the duplicated page should be inserted",
    });

export const foldersCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs).option("include-pages", {
    type: "boolean",
    describe: "Include page summaries inside their folders",
  });

export const createFolderCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs)
    .option("folder", {
      type: "string",
      describe:
        "Optional folder id to create; generated by Builder when omitted",
    })
    .option("name", {
      type: "string",
      describe: "Required folder name shown in Builder",
      demandOption: true,
    })
    .option("slug", {
      type: "string",
      describe:
        "Required folder URL slug, use empty string for no path segment",
      demandOption: true,
    })
    .option("parent-folder", {
      type: "string",
      describe: "Parent folder id where the folder should be created",
    });

export const updateFolderCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs)
    .option("folder", {
      type: "string",
      describe: "Required folder id to update",
      demandOption: true,
    })
    .option("name", {
      type: "string",
      describe: "Update folder name shown in Builder",
    })
    .option("slug", {
      type: "string",
      describe: "Update folder URL slug",
    })
    .option("parent-folder", {
      type: "string",
      describe: "Move folder into this parent folder id",
    });

export const deleteFolderCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs).option("folder", {
    type: "string",
    describe: "Required folder id to delete with its child folders and pages",
    demandOption: true,
  });

export const instanceListCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs)
    .option("page", {
      type: "string",
      describe: "Limit results to a page id",
    })
    .option("path", {
      type: "string",
      describe: "Limit results to a page path, for example /pricing",
    })
    .option("root", {
      type: "string",
      describe: "Limit traversal to this root instance id",
    })
    .option("max-depth", {
      type: "number",
      describe: "Maximum descendant depth to include from the root",
    })
    .option("top-level", {
      type: "boolean",
      describe: "Only return root-level instances in the selected scope",
    })
    .option("component", {
      type: "string",
      describe: "Only return instances with this component name",
    })
    .option("tag", {
      type: "string",
      describe: "Only return instances with this HTML tag override",
    })
    .option("label", {
      type: "string",
      describe: "Only return instances whose label contains this text",
    });

export const instanceInspectCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs)
    .option("instance", {
      type: "string",
      describe: "Required instance id to inspect",
      demandOption: true,
    })
    .option("include", {
      type: "array",
      string: true,
      describe:
        "Comma-separated details to include: props, styles, children, bindings, sources",
    })
    .option("child-depth", {
      type: "number",
      describe: "When including children, maximum descendant depth to return",
    });

export const appendInstanceCommandOptions = (yargs: CommonYargsArgv) =>
  requiredInputOption(
    apiCommandOptions(yargs)
      .option("parent", {
        type: "string",
        describe: "Required parent instance id where new children are inserted",
        demandOption: true,
      })
      .option("mode", {
        choices: ["append", "prepend", "replace"] as const,
        describe:
          "Append, prepend, or replace parent children before inserting new instances",
      })
      .option("insert-index", {
        type: "number",
        describe: "Zero-based child index for insertion",
      }),
    "Required JSON file containing an array of children with tag, optional component, label, text, and instanceId"
  );

export const moveInstanceCommandOptions = (yargs: CommonYargsArgv) =>
  requiredInputOption(
    apiCommandOptions(yargs),
    "Required JSON file containing an array of moves with instanceId, parentInstanceId, and optional insertIndex"
  );

export const cloneInstanceCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs)
    .option("source", {
      type: "string",
      describe: "Required source instance id to clone",
      demandOption: true,
    })
    .option("parent", {
      type: "string",
      describe:
        "Optional target parent instance id; defaults to the source parent",
    })
    .option("insert-index", {
      type: "number",
      describe: "Zero-based child index for the cloned instance",
    });

export const deleteInstanceCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs).option("instance", {
    type: "array",
    string: true,
    describe:
      "Required instance id to delete. Repeat or comma-separate to delete multiple roots.",
    demandOption: true,
  });

export const updatePropsCommandOptions = (yargs: CommonYargsArgv) =>
  requiredInputOption(
    apiCommandOptions(yargs),
    "Required JSON file containing an array of prop updates with instanceId, name, type, value, and optional propId"
  );

export const deletePropsCommandOptions = (yargs: CommonYargsArgv) =>
  requiredInputOption(
    apiCommandOptions(yargs),
    "Required JSON file containing an array of prop deletions with instanceId and name"
  );

export const bindPropsCommandOptions = (yargs: CommonYargsArgv) =>
  requiredInputOption(
    apiCommandOptions(yargs),
    "Required JSON file containing an array of prop bindings with instanceId, name, and binding"
  );

export const textListCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs)
    .option("page", {
      type: "string",
      describe: "Limit text nodes to a page id",
    })
    .option("path", {
      type: "string",
      describe: "Limit text nodes to a page path, for example /pricing",
    })
    .option("instance", {
      type: "string",
      describe: "Limit text nodes to one instance id",
    })
    .option("mode", {
      choices: ["text", "expression", "all"] as const,
      describe: "Return text children, expression children, or both",
    })
    .option("contains", {
      type: "string",
      describe: "Only return text nodes whose value contains this substring",
    })
    .option("max-value-length", {
      type: "number",
      describe: "Truncate returned text values to this character count",
    });

export const textUpdateCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs)
    .option("instance", {
      type: "string",
      describe: "Required instance id containing the text child",
      demandOption: true,
    })
    .option("child-index", {
      type: "number",
      describe:
        "Required zero-based child index from list-texts for the text child to update",
      demandOption: true,
    })
    .option("text", {
      type: "string",
      describe: "Required replacement text or expression string",
      demandOption: true,
    })
    .option("mode", {
      choices: ["text", "expression"] as const,
      describe:
        "Optional expected child type; use expression to validate expression syntax",
    });

export const stylesCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs)
    .option("instance", {
      type: "string",
      describe: "Limit declarations to one instance id",
    })
    .option("page", {
      type: "string",
      describe: "Limit declarations to instances on this page id",
    })
    .option("path", {
      type: "string",
      describe: "Limit declarations to instances on this page path",
    })
    .option("breakpoint", {
      type: "string",
      describe: "Only return declarations for this breakpoint id",
    })
    .option("state", {
      type: "string",
      describe: "Only return declarations for this state selector",
    })
    .option("property", {
      type: "string",
      describe: "Only return declarations for this exact CSS property",
    })
    .option("property-filter", {
      type: "string",
      describe:
        "Only return declarations whose CSS property contains this text",
    })
    .option("include-tokens", {
      type: "boolean",
      describe:
        "Include token style declarations in addition to local declarations",
    });

export const updateStylesCommandOptions = (yargs: CommonYargsArgv) =>
  requiredInputOption(
    apiCommandOptions(yargs),
    "Required JSON file containing an array of style updates with instanceId, property, value, optional breakpoint/state"
  );

export const deleteStylesCommandOptions = (yargs: CommonYargsArgv) =>
  requiredInputOption(
    apiCommandOptions(yargs),
    "Required JSON file containing an array of style deletions with instanceId, property, optional breakpoint/state"
  );

export const replaceStylesCommandOptions = (yargs: CommonYargsArgv) =>
  requiredInputOption(
    apiCommandOptions(yargs),
    "Required JSON file containing property, fromValue, toValue, and optional pageId/pagePath"
  );

export const designTokensCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs)
    .option("filter", {
      type: "string",
      describe: "Only return design tokens whose name contains this text",
    })
    .option("with-usage", {
      type: "boolean",
      describe: "Include how many instances use each design token",
    })
    .option("sort", {
      choices: ["name", "usage"] as const,
      describe: "Sort design tokens by name or usage count",
    });

export const createDesignTokenCommandOptions = (yargs: CommonYargsArgv) =>
  requiredInputOption(
    apiCommandOptions(yargs),
    "Required JSON file containing an array of design tokens with name, optional tokenId, styles object, or declarations array"
  );

export const updateDesignTokenStylesCommandOptions = (yargs: CommonYargsArgv) =>
  requiredInputOption(
    apiCommandOptions(yargs).option("design-token", {
      type: "string",
      describe: "Required design token id",
      demandOption: true,
    }),
    "Required JSON file containing an array of style updates with property, value, optional breakpoint/state"
  );

export const deleteDesignTokenStylesCommandOptions = (yargs: CommonYargsArgv) =>
  requiredInputOption(
    apiCommandOptions(yargs).option("design-token", {
      type: "string",
      describe: "Required design token id",
      demandOption: true,
    }),
    "Required JSON file containing an array of style deletions with property, optional breakpoint/state"
  );

export const attachDesignTokenCommandOptions = (yargs: CommonYargsArgv) =>
  requiredInputOption(
    apiCommandOptions(yargs)
      .option("design-token", {
        type: "string",
        describe: "Required design token id",
        demandOption: true,
      })
      .option("position", {
        choices: ["before-local", "after-local"] as const,
        describe:
          "Where to place the token relative to an instance local style source",
      }),
    "Required JSON file containing an array of instance ids"
  );

export const detachDesignTokenCommandOptions = (yargs: CommonYargsArgv) =>
  requiredInputOption(
    apiCommandOptions(yargs).option("design-token", {
      type: "string",
      describe: "Required design token id",
      demandOption: true,
    }),
    "Required JSON file containing an array of instance ids"
  );

export const extractDesignTokenCommandOptions = (yargs: CommonYargsArgv) =>
  requiredInputOption(
    apiCommandOptions(yargs),
    "Required JSON file containing instanceIds, name, and optional removeLocalProps"
  );

export const cssVariablesCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs)
    .option("filter", {
      type: "string",
      describe: "Only return CSS variables whose name contains this text",
    })
    .option("with-usage", {
      type: "boolean",
      describe: "Include how many references use each CSS variable",
    });

export const defineCssVariableCommandOptions = (yargs: CommonYargsArgv) =>
  requiredInputOption(
    apiCommandOptions(yargs).option("overwrite", {
      type: "boolean",
      describe: "Replace existing CSS variable definitions with the same name",
    }),
    "Required JSON file containing an object of CSS variable names to values"
  );

export const deleteCssVariableCommandOptions = (yargs: CommonYargsArgv) =>
  requiredInputOption(
    confirmOption(
      apiCommandOptions(yargs).option("force", {
        type: "boolean",
        describe:
          "Delete CSS variable definitions even when they are referenced",
      }),
      "Required. Confirm deleting CSS variable definitions"
    ),
    "Required JSON file containing an array of CSS variable names"
  );

export const rewriteCssVariableRefsCommandOptions = (yargs: CommonYargsArgv) =>
  requiredInputOption(
    apiCommandOptions(yargs).option("scope-regex", {
      type: "string",
      describe: "Only rewrite references in matching instance or style scopes",
    }),
    "Required JSON file containing an object that maps old CSS variable names to new names"
  );

export const scopedCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs).option("scope-instance", {
    type: "string",
    describe: "Only return items scoped to this instance id",
  });

export const createVariableCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs)
    .option("variable", {
      type: "string",
      describe:
        "Optional variable data source id to create; generated by Builder when omitted",
    })
    .option("scope-instance", {
      type: "string",
      describe: "Required instance id where the variable is scoped",
      demandOption: true,
    })
    .option("name", {
      type: "string",
      describe: "Required variable name used in expressions",
      demandOption: true,
    })
    .option("value-type", {
      choices: ["string", "number", "boolean", "string[]", "json"] as const,
      describe: "Required variable value type",
      demandOption: true,
    })
    .option("value", {
      type: "string",
      describe:
        "Required variable value; use JSON for json and string[] value types",
      demandOption: true,
    });

export const updateVariableCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs)
    .option("variable", {
      type: "string",
      describe: "Required variable data source id to update",
      demandOption: true,
    })
    .option("scope-instance", {
      type: "string",
      describe: "Move variable scope to this instance id",
    })
    .option("name", {
      type: "string",
      describe: "Update variable name used in expressions",
    })
    .option("value-type", {
      choices: ["string", "number", "boolean", "string[]", "json"] as const,
      describe: "Variable value type when updating --value",
    })
    .option("value", {
      type: "string",
      describe: "Updated variable value; use JSON for json and string[] types",
    });

export const deleteVariableCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs).option("variable", {
    type: "string",
    describe: "Required variable data source id to delete",
    demandOption: true,
  });

export const createResourceCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs)
    .option("resource", {
      type: "string",
      describe:
        "Optional resource id to create; generated by Builder when omitted",
    })
    .option("input", {
      type: "string",
      describe:
        "Optional JSON file with resource fields: name, method, url, headers, searchParams, body, control",
    })
    .option("name", {
      type: "string",
      describe: "Required resource name unless provided by --input",
    })
    .option("method", {
      choices: ["get", "post", "put", "delete"] as const,
      describe: "Required HTTP method unless provided by --input",
    })
    .option("url", {
      type: "string",
      describe:
        'Required URL expression unless provided by --input, for example "\\"https://api.example.com/items\\""',
    })
    .option("body", {
      type: "string",
      describe: "Optional request body expression",
    })
    .option("scope-instance", {
      type: "string",
      describe:
        "Expose the resource as a data variable scoped to this instance",
    })
    .option("data-source", {
      type: "string",
      describe: "Optional data source id when exposing the resource",
    })
    .option("data-source-name", {
      type: "string",
      describe:
        "Optional data variable name when exposing the resource; defaults to resource name",
    });

export const updateResourceCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs)
    .option("resource", {
      type: "string",
      describe: "Required resource id to update",
      demandOption: true,
    })
    .option("input", {
      type: "string",
      describe:
        "Optional JSON file with resource fields to update: name, method, url, headers, searchParams, body, control",
    })
    .option("name", {
      type: "string",
      describe: "Update resource name",
    })
    .option("method", {
      choices: ["get", "post", "put", "delete"] as const,
      describe: "Update HTTP method",
    })
    .option("url", {
      type: "string",
      describe: "Update URL expression",
    })
    .option("body", {
      type: "string",
      describe: "Update request body expression",
    })
    .option("scope-instance", {
      type: "string",
      describe: "Move the exposed resource data variable to this instance id",
    })
    .option("data-source-name", {
      type: "string",
      describe: "Update the exposed resource data variable name",
    });

export const deleteResourceCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs)
    .option("resource", {
      type: "string",
      describe: "Required resource id to delete",
      demandOption: true,
    })
    .option("force", {
      type: "boolean",
      describe:
        "Also remove direct resource prop references that point at this resource",
    });

const publishTargetOption = (yargs: CommonYargsArgv) =>
  yargs.option("target", {
    choices: ["staging", "production"] as const,
    describe: "Required publish target",
    demandOption: true,
  });

const publishDomainsOption = (yargs: CommonYargsArgv) =>
  yargs.option("domain", {
    type: "array",
    string: true,
    describe:
      "Domain to publish or unpublish. Repeat or comma-separate to target multiple domains. Defaults to the configured project domain and active verified custom domains.",
  });

export const publishCommandOptions = (yargs: CommonYargsArgv) =>
  publishDomainsOption(publishTargetOption(apiCommandOptions(yargs)))
    .option("message", {
      type: "string",
      describe: "Optional human-readable publish message",
    })
    .option("idempotency-key", {
      type: "string",
      describe: "Optional idempotency key for retrying the same publish",
    });

export const publishJobCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs).option("job", {
    type: "string",
    describe: "Required publish job id returned by publish or unpublish",
    demandOption: true,
  });

export const unpublishCommandOptions = (yargs: CommonYargsArgv) =>
  confirmOption(
    publishCommandOptions(yargs),
    "Required. Confirm that selected domains should be unpublished"
  );

export const createDomainCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs).option("domain", {
    type: "string",
    describe: "Required custom domain, for example example.com",
    demandOption: true,
  });

export const updateDomainCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs)
    .option("domain-id", {
      type: "string",
      describe: "Required domain id to update",
      demandOption: true,
    })
    .option("input", {
      type: "string",
      describe: "Optional JSON file containing { domain }",
    })
    .option("domain", {
      type: "string",
      describe: "Set custom domain, for example www.example.com",
    });

export const deleteDomainCommandOptions = (yargs: CommonYargsArgv) =>
  confirmOption(
    apiCommandOptions(yargs).option("domain-id", {
      type: "string",
      describe: "Required domain id to delete",
      demandOption: true,
    }),
    "Required. Confirm that the domain should be removed"
  );

export const verifyDomainCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs).option("domain-id", {
    type: "string",
    describe: "Required domain id to verify",
    demandOption: true,
  });

export const assetsCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs)
    .option("type", {
      choices: ["image", "font"] as const,
      describe: "Only return assets of this type",
    })
    .option("sort", {
      choices: ["name", "size", "createdAt", "usage"] as const,
      describe: "Sort assets by name, size, creation time, or usage count",
    })
    .option("with-usage", {
      type: "boolean",
      describe: "Include how many build references point to each asset",
    })
    .option("cursor", {
      type: "string",
      describe: "Pagination cursor returned as nextCursor by the previous call",
    })
    .option("limit", {
      type: "number",
      describe: "Maximum number of assets to return",
    });

export const uploadAssetCommandOptions = (yargs: CommonYargsArgv) =>
  requiredInputOption(
    apiCommandOptions(yargs).option("assets-dir", {
      type: "string",
      describe: `Directory containing asset files; defaults to ${LOCAL_ASSETS_DIR}`,
    }),
    "Required JSON file containing asset descriptor: name, type, format, meta"
  );

export const uploadAssetsCommandOptions = (yargs: CommonYargsArgv) =>
  requiredInputOption(
    apiCommandOptions(yargs).option("assets-dir", {
      type: "string",
      describe: `Directory containing asset files; defaults to ${LOCAL_ASSETS_DIR}`,
    }),
    "Required JSON file containing an array of asset descriptors"
  );

export const assetCommandOptions = (yargs: CommonYargsArgv) =>
  apiCommandOptions(yargs).option("asset", {
    type: "string",
    describe: "Required asset id",
    demandOption: true,
  });

export const replaceAssetCommandOptions = (yargs: CommonYargsArgv) =>
  confirmOption(
    apiCommandOptions(yargs)
      .option("from", {
        type: "string",
        describe: "Required asset id to replace",
        demandOption: true,
      })
      .option("to", {
        type: "string",
        describe: "Required replacement asset id",
        demandOption: true,
      }),
    "Required. Confirm replacing asset references and deleting old asset"
  );

export const deleteAssetCommandOptions = (yargs: CommonYargsArgv) =>
  confirmOption(
    apiCommandOptions(yargs)
      .option("asset", {
        type: "array",
        string: true,
        describe: "Required asset ids or id prefixes to delete",
        demandOption: true,
      })
      .option("force", {
        type: "boolean",
        describe: "Delete assets even when they are referenced",
      }),
    "Required. Confirm deleting asset records"
  );

type ApiCommandOptions = {
  command: ApiCommandName;
  json?: boolean;
  include?: string[];
  version?: number;
  baseVersion?: number;
  input?: string;
  assetsDir?: string;
  page?: string;
  folder?: string;
  path?: string;
  name?: string;
  variable?: string;
  resource?: string;
  dataSource?: string;
  asset?: string | string[];
  domain?: string | string[];
  domainId?: string;
  target?: "staging" | "production";
  job?: string;
  idempotencyKey?: string;
  from?: string;
  to?: string;
  designToken?: string;
  dataSourceName?: string;
  slug?: string;
  title?: string;
  description?: string;
  language?: string;
  redirect?: string;
  socialImageUrl?: string;
  socialImageAsset?: string;
  excludePageFromSearch?: boolean;
  documentType?: "html" | "xml" | "text";
  content?: string;
  message?: string;
  parentFolder?: string;
  includeFolders?: boolean;
  includePages?: boolean;
  root?: string;
  maxDepth?: number;
  topLevel?: boolean;
  component?: string;
  tag?: string;
  label?: string;
  instance?: string | string[];
  parent?: string;
  source?: string;
  insertIndex?: number;
  childIndex?: number;
  text?: string;
  childDepth?: number;
  mode?: "text" | "expression" | "all" | "append" | "prepend" | "replace";
  valueType?: "string" | "number" | "boolean" | "string[]" | "json";
  value?: string;
  method?: "get" | "post" | "put" | "delete";
  url?: string;
  body?: string;
  force?: boolean;
  confirm?: boolean;
  overwrite?: boolean;
  scopeRegex?: string;
  contains?: string;
  maxValueLength?: number;
  breakpoint?: string;
  state?: string;
  property?: string;
  propertyFilter?: string;
  includeTokens?: boolean;
  position?: "before-local" | "after-local";
  filter?: string;
  withUsage?: boolean;
  scopeInstance?: string;
  type?: "image" | "font" | "file";
  sort?: "name" | "usage" | "size" | "createdAt";
  cursor?: string;
  limit?: number;
};

const resolveConnection = async (dependencies: ApiCommandDependencies) => {
  if ((await dependencies.isFileExists(LOCAL_CONFIG_FILE)) === false) {
    throw new Error(
      "Local config file is not found. Run webstudio init --link <api-share-link> from a Webstudio project."
    );
  }

  const localConfig = jsonToLocalConfig(
    JSON.parse(
      await dependencies.readFile(join(cwd(), LOCAL_CONFIG_FILE), "utf-8")
    )
  );
  const globalConfig = jsonToGlobalConfig(
    JSON.parse(await dependencies.readFile(GLOBAL_CONFIG_FILE, "utf-8"))
  );
  const projectConfig = globalConfig[localConfig.projectId];
  if (projectConfig === undefined) {
    throw new Error(
      "Project config is not found. Run webstudio init --link <api-share-link>."
    );
  }

  return {
    origin: projectConfig.origin,
    authToken: projectConfig.token,
    projectId: localConfig.projectId,
  };
};

type ApiConnection = Awaited<ReturnType<typeof resolveConnection>> & {
  headers: typeof apiCompatibilityHeaders;
};

type ResourceFieldsInput = Parameters<
  typeof httpClient.createResource
>[0]["resource"];
type VariableValueInput = Parameters<
  typeof httpClient.createVariable
>[0]["value"];
type AppendInstanceChildrenInput = Parameters<
  typeof httpClient.appendInstance
>[0]["children"];
type MoveInstanceInput = Parameters<typeof httpClient.moveInstance>[0]["moves"];
type PropUpdatesInput = Parameters<typeof httpClient.updateProps>[0]["updates"];
type PropDeletionsInput = Parameters<
  typeof httpClient.deleteProps
>[0]["deletions"];
type PropBindingsInput = Parameters<typeof httpClient.bindProps>[0]["bindings"];
type StyleUpdatesInput = Parameters<
  typeof httpClient.updateStyleDeclarations
>[0]["updates"];
type StyleDeletionsInput = Parameters<
  typeof httpClient.deleteStyleDeclarations
>[0]["deletions"];
type StyleReplaceInput = Omit<
  Parameters<typeof httpClient.replaceStyleValues>[0],
  "authToken" | "headers" | "origin" | "projectId"
>;
type CreateDesignTokensInput = Parameters<
  typeof httpClient.createDesignTokens
>[0]["tokens"];
type UpdateDesignTokenStylesInput = Parameters<
  typeof httpClient.updateDesignTokenStyles
>[0]["updates"];
type DeleteDesignTokenStylesInput = Parameters<
  typeof httpClient.deleteDesignTokenStyles
>[0]["deletions"];
type ExtractDesignTokenInput = Omit<
  Parameters<typeof httpClient.extractDesignToken>[0],
  "authToken" | "headers" | "origin" | "projectId"
>;
type DefineCssVariablesInput = Parameters<
  typeof httpClient.defineCssVariables
>[0]["vars"];
type DeleteCssVariablesInput = Parameters<
  typeof httpClient.deleteCssVariables
>[0]["names"];
type RewriteCssVariableRefsInput = Parameters<
  typeof httpClient.rewriteCssVariableRefs
>[0]["map"];
type UploadAssetInput = Parameters<
  typeof httpClient.uploadProjectAsset
>[0]["asset"];
type UploadAssetsInput = Parameters<
  typeof httpClient.uploadProjectAssets
>[0]["assets"];
type UpdateDomainInput = Parameters<
  typeof httpClient.updateDomain
>[0]["updates"];

const printJson = (value: unknown) => {
  console.info(JSON.stringify(value, undefined, 2));
};

const requireOption = (value: string | undefined, name: string) => {
  if (value === undefined || value.length === 0) {
    throw new Error(`${name} is required.`);
  }
  return value;
};

const requireSingleOption = (
  value: string | string[] | undefined,
  name: string
) => {
  if (Array.isArray(value)) {
    return requireOption(value[0], name);
  }
  return requireOption(value, name);
};

const requireStringOption = (value: string | undefined, name: string) => {
  if (value === undefined) {
    throw new Error(`${name} is required.`);
  }
  return value;
};

const requireTrueOption = (value: boolean | undefined, name: string) => {
  if (value !== true) {
    throw new Error(`${name} is required.`);
  }
};

const requireNumberOption = (value: number | undefined, name: string) => {
  if (value === undefined) {
    throw new Error(`${name} is required.`);
  }
  return value;
};

const listOption = (value: string[] | undefined) =>
  value?.flatMap((item) =>
    item
      .split(",")
      .map((item) => item.trim())
      .filter((item) => item.length > 0)
  );

const listStringOption = (value: string | string[] | undefined) =>
  listOption(
    Array.isArray(value) ? value : value === undefined ? undefined : [value]
  );

const requireListOption = (
  value: string | string[] | undefined,
  name: string
) => {
  const values = listStringOption(value);
  if (values === undefined || values.length === 0) {
    throw new Error(`${name} is required.`);
  }
  return values;
};

const optionalChoice = <Choice extends string>(
  value: string | undefined,
  choices: readonly Choice[],
  name: string
): Choice | undefined => {
  if (value === undefined) {
    return;
  }
  if ((choices as readonly string[]).includes(value)) {
    return value as Choice;
  }
  throw new Error(`Unsupported ${name} "${value}".`);
};

const requiredChoice = <Choice extends string>(
  value: string | undefined,
  choices: readonly Choice[],
  name: string
) => {
  const choice = optionalChoice(value, choices, name);
  if (choice === undefined) {
    throw new Error(`${name} is required.`);
  }
  return choice;
};

const designTokenSortOption = (
  value: ApiCommandOptions["sort"]
): "name" | "usage" | undefined =>
  optionalChoice(value, ["name", "usage"], "design token sort");

const assetListTypeOption = (
  value: ApiCommandOptions["type"]
): "image" | "font" | undefined =>
  optionalChoice(value, ["image", "font"], "asset list type");

const publishTargetValue = (
  value: ApiCommandOptions["target"]
): "staging" | "production" =>
  requiredChoice(value, ["staging", "production"], "--target");

const textUpdateModeOption = (
  value: ApiCommandOptions["mode"]
): "text" | "expression" | undefined =>
  optionalChoice(value, ["text", "expression"], "text update mode");

const textListModeOption = (
  value: ApiCommandOptions["mode"]
): "text" | "expression" | "all" | undefined =>
  optionalChoice(value, ["text", "expression", "all"], "text list mode");

const appendInstanceModeOption = (
  value: ApiCommandOptions["mode"]
): "append" | "prepend" | "replace" | undefined =>
  optionalChoice(
    value,
    ["append", "prepend", "replace"],
    "append instance mode"
  );

const readJsonFile = async (
  dependencies: ApiCommandDependencies,
  path: string | undefined,
  name: string
) => {
  return JSON.parse(
    await dependencies.readFile(requireOption(path, name), "utf-8")
  ) as unknown;
};

const readOptionalJsonObject = async (
  dependencies: ApiCommandDependencies,
  path: string | undefined
) => {
  if (path === undefined) {
    return {};
  }
  const value = await readJsonFile(dependencies, path, "--input");
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new Error("--input must contain a JSON object.");
  }
  return value as Record<string, unknown>;
};

const readJsonArray = async (
  dependencies: ApiCommandDependencies,
  path: string | undefined,
  name: string
) => {
  const value = await readJsonFile(dependencies, path, name);
  if (Array.isArray(value) === false) {
    throw new Error(`${name} must contain a JSON array.`);
  }
  return value;
};

const readInputObject = async <Value>(
  dependencies: ApiCommandDependencies,
  options: ApiCommandOptions
) => (await readOptionalJsonObject(dependencies, options.input)) as Value;

const readInputArray = async <Value>(
  dependencies: ApiCommandDependencies,
  options: ApiCommandOptions
) => (await readJsonArray(dependencies, options.input, "--input")) as Value;

const readAssetData =
  (dependencies: ApiCommandDependencies, assetsDirectory?: string) =>
  async (asset: { name: string }) =>
    (await dependencies.readFile(
      getLocalAssetPath(asset.name, assetsDirectory)
    )) as unknown as ArrayBufferView<ArrayBuffer>;

const parseVariableValue = (
  type: ApiCommandOptions["valueType"],
  value: string | undefined
): VariableValueInput => {
  const valueType = requireOption(type, "--value-type");
  const rawValue = requireStringOption(value, "--value");
  if (valueType === "string") {
    return { type: valueType, value: rawValue };
  }
  if (valueType === "number") {
    const number = Number(rawValue);
    if (Number.isFinite(number) === false) {
      throw new Error("--value must be a finite number.");
    }
    return { type: valueType, value: number };
  }
  if (valueType === "boolean") {
    if (rawValue !== "true" && rawValue !== "false") {
      throw new Error('--value must be "true" or "false".');
    }
    return { type: valueType, value: rawValue === "true" };
  }
  const parsed = JSON.parse(rawValue) as unknown;
  if (valueType === "string[]") {
    if (
      Array.isArray(parsed) === false ||
      parsed.every((item) => typeof item === "string") === false
    ) {
      throw new Error("--value must be a JSON array of strings.");
    }
    return { type: valueType, value: parsed };
  }
  return { type: "json", value: parsed };
};

const parseOptionalVariableValue = (
  options: ApiCommandOptions
): VariableValueInput | undefined => {
  if (options.value === undefined && options.valueType === undefined) {
    return;
  }
  if (options.value === undefined || options.valueType === undefined) {
    throw new Error("--value and --value-type must be provided together.");
  }
  return parseVariableValue(options.valueType, options.value);
};

const getResourceFields = async (
  dependencies: ApiCommandDependencies,
  options: ApiCommandOptions,
  requireComplete: boolean
) => {
  const input = await readOptionalJsonObject(dependencies, options.input);
  const fields: Record<string, unknown> = {
    ...input,
    name: options.name ?? input.name,
    method: options.method ?? input.method,
    url: options.url ?? input.url,
    body: options.body ?? input.body,
  };
  if (requireComplete && fields.headers === undefined) {
    fields.headers = [];
  }
  if (requireComplete) {
    fields.name = requireOption(
      typeof fields.name === "string" ? fields.name : undefined,
      "--name"
    );
    fields.method = requireOption(
      typeof fields.method === "string" ? fields.method : undefined,
      "--method"
    );
    fields.url = requireOption(
      typeof fields.url === "string" ? fields.url : undefined,
      "--url"
    );
  }
  return fields;
};

const getPageMetaOptions = (options: ApiCommandOptions) => {
  const meta = {
    description: options.description,
    language: options.language,
    redirect: options.redirect,
    socialImageUrl: options.socialImageUrl,
    socialImageAssetId: options.socialImageAsset,
    excludePageFromSearch: options.excludePageFromSearch,
    documentType: options.documentType,
    content: options.content,
  };
  return Object.values(meta).some((value) => value !== undefined)
    ? meta
    : undefined;
};

const getErrorCode = (error: unknown) => {
  const message = error instanceof Error ? error.message : String(error);
  if (error instanceof SyntaxError) {
    return "INVALID_JSON";
  }
  const apiErrorCode = httpClient.getApiErrorCode(error);
  if (apiErrorCode === "CONFLICT") {
    return "VERSION_CONFLICT";
  }
  if (apiErrorCode === "NOT_FOUND") {
    return "NOT_FOUND";
  }
  if (apiErrorCode === "UNAUTHORIZED" || apiErrorCode === "FORBIDDEN") {
    return "UNAUTHORIZED";
  }
  if (apiErrorCode === "BAD_REQUEST") {
    return "INVALID_ARGUMENT";
  }
  if (
    message.includes("Local config file") ||
    message.includes("Project config")
  ) {
    return "NOT_INITIALIZED";
  }
  if (message.includes(" is required")) {
    return "INVALID_ARGUMENT";
  }
  if (message.includes("Invalid patch JSON")) {
    return "INVALID_PATCH";
  }
  if (message.includes("version") || message.includes("CONFLICT")) {
    return "VERSION_CONFLICT";
  }
  return "API_COMMAND_FAILED";
};

const getRetryHint = (code: string) => {
  if (code === "VERSION_CONFLICT") {
    return "Run webstudio inspect --json, read the latest build, regenerate the patch, then retry apply-patch.";
  }
};

type ApiCommandHandler = (
  options: ApiCommandOptions,
  connection: ApiConnection,
  dependencies: ApiCommandDependencies
) => Promise<unknown>;

const apiCommandHandlers = {
  whoami: async (_options, connection, dependencies) =>
    dependencies.getApiTokenInfo(connection),
  permissions: async (_options, connection, dependencies) =>
    dependencies.getProjectPermissions(connection),
  inspect: async (_options, connection, dependencies) =>
    dependencies.getProjectInfo(connection),
  snapshot: async (options, connection, dependencies) =>
    dependencies.getBuildSnapshot({
      ...connection,
      include: listOption(options.include),
      version: options.version,
    }),
  "apply-patch": async (options, connection, dependencies) => {
    const patchInput = await readJsonFile(
      dependencies,
      options.input,
      "--input"
    );
    return dependencies.applyBuildPatch({
      ...connection,
      baseVersion: requireNumberOption(options.baseVersion, "--base-version"),
      transactions: patchInput,
    });
  },
  "list-pages": async (options, connection, dependencies) =>
    dependencies.listPages({
      ...connection,
      includeFolders: options.includeFolders,
    }),
  "get-page": async (options, connection, dependencies) =>
    dependencies.getPage({
      ...connection,
      pageId: requireOption(options.page, "--page"),
    }),
  "get-page-by-path": async (options, connection, dependencies) =>
    dependencies.getPageByPath({
      ...connection,
      path: requireOption(options.path, "--path"),
    }),
  "create-page": async (options, connection, dependencies) =>
    dependencies.createPage({
      ...connection,
      pageId: options.page,
      name: requireOption(options.name, "--name"),
      path: requireOption(options.path, "--path"),
      title: options.title,
      parentFolderId: options.parentFolder,
      meta: getPageMetaOptions(options),
    }),
  "update-page": async (options, connection, dependencies) =>
    dependencies.updatePage({
      ...connection,
      pageId: requireOption(options.page, "--page"),
      values: {
        name: options.name,
        path: options.path,
        title: options.title,
        parentFolderId: options.parentFolder,
        meta: getPageMetaOptions(options),
      },
    }),
  "delete-page": async (options, connection, dependencies) =>
    dependencies.deletePage({
      ...connection,
      pageId: requireOption(options.page, "--page"),
    }),
  "duplicate-page": async (options, connection, dependencies) =>
    dependencies.duplicatePage({
      ...connection,
      pageId: requireOption(options.page, "--page"),
      parentFolderId: options.parentFolder,
      name: options.name,
      path: options.path,
    }),
  "list-folders": async (options, connection, dependencies) =>
    dependencies.listFolders({
      ...connection,
      includePages: options.includePages,
    }),
  "create-folder": async (options, connection, dependencies) =>
    dependencies.createFolder({
      ...connection,
      folderId: options.folder,
      name: requireOption(options.name, "--name"),
      slug: requireOption(options.slug, "--slug"),
      parentFolderId: options.parentFolder,
    }),
  "update-folder": async (options, connection, dependencies) =>
    dependencies.updateFolder({
      ...connection,
      folderId: requireOption(options.folder, "--folder"),
      values: {
        name: options.name,
        slug: options.slug,
        parentFolderId: options.parentFolder,
      },
    }),
  "delete-folder": async (options, connection, dependencies) =>
    dependencies.deleteFolder({
      ...connection,
      folderId: requireOption(options.folder, "--folder"),
    }),
  "list-instances": async (options, connection, dependencies) =>
    dependencies.listInstances({
      ...connection,
      pageId: options.page,
      pagePath: options.path,
      rootInstanceId: options.root,
      maxDepth: options.maxDepth,
      topLevelOnly: options.topLevel,
      component: options.component,
      tag: options.tag,
      labelContains: options.label,
    }),
  "inspect-instance": async (options, connection, dependencies) =>
    dependencies.inspectInstance({
      ...connection,
      instanceId: requireSingleOption(options.instance, "--instance"),
      include: listOption(options.include),
      childDepth: options.childDepth,
    }),
  "append-instance": async (options, connection, dependencies) =>
    dependencies.appendInstance({
      ...connection,
      parentInstanceId: requireOption(options.parent, "--parent"),
      mode: appendInstanceModeOption(options.mode),
      insertIndex: options.insertIndex,
      children: await readInputArray<AppendInstanceChildrenInput>(
        dependencies,
        options
      ),
    }),
  "move-instance": async (options, connection, dependencies) =>
    dependencies.moveInstance({
      ...connection,
      moves: await readInputArray<MoveInstanceInput>(dependencies, options),
    }),
  "clone-instance": async (options, connection, dependencies) =>
    dependencies.cloneInstance({
      ...connection,
      sourceInstanceId: requireOption(options.source, "--source"),
      targetParentInstanceId: options.parent,
      insertIndex: options.insertIndex,
    }),
  "delete-instance": async (options, connection, dependencies) =>
    dependencies.deleteInstance({
      ...connection,
      instanceIds: requireListOption(options.instance, "--instance"),
    }),
  "update-props": async (options, connection, dependencies) =>
    dependencies.updateProps({
      ...connection,
      updates: await readInputArray<PropUpdatesInput>(dependencies, options),
    }),
  "delete-props": async (options, connection, dependencies) =>
    dependencies.deleteProps({
      ...connection,
      deletions: await readInputArray<PropDeletionsInput>(
        dependencies,
        options
      ),
    }),
  "bind-props": async (options, connection, dependencies) =>
    dependencies.bindProps({
      ...connection,
      bindings: await readInputArray<PropBindingsInput>(dependencies, options),
    }),
  "list-texts": async (options, connection, dependencies) =>
    dependencies.listTexts({
      ...connection,
      pageId: options.page,
      pagePath: options.path,
      instanceId:
        typeof options.instance === "string" ? options.instance : undefined,
      mode: textListModeOption(options.mode),
      contains: options.contains,
      maxValueLength: options.maxValueLength,
    }),
  "update-text": async (options, connection, dependencies) =>
    dependencies.updateText({
      ...connection,
      instanceId: requireSingleOption(options.instance, "--instance"),
      childIndex: requireNumberOption(options.childIndex, "--child-index"),
      text: requireStringOption(options.text, "--text"),
      mode: textUpdateModeOption(options.mode),
    }),
  "get-styles": async (options, connection, dependencies) =>
    dependencies.getStyleDeclarations({
      ...connection,
      instanceIds:
        typeof options.instance === "string" ? [options.instance] : undefined,
      pageId: options.page,
      pagePath: options.path,
      breakpoint: options.breakpoint,
      state: options.state,
      property: options.property,
      propertyFilter: options.propertyFilter,
      includeTokens: options.includeTokens,
    }),
  "update-styles": async (options, connection, dependencies) =>
    dependencies.updateStyleDeclarations({
      ...connection,
      updates: await readInputArray<StyleUpdatesInput>(dependencies, options),
    }),
  "delete-styles": async (options, connection, dependencies) =>
    dependencies.deleteStyleDeclarations({
      ...connection,
      deletions: await readInputArray<StyleDeletionsInput>(
        dependencies,
        options
      ),
    }),
  "replace-styles": async (options, connection, dependencies) =>
    dependencies.replaceStyleValues({
      ...connection,
      ...(await readInputObject<StyleReplaceInput>(dependencies, options)),
    }),
  "list-design-tokens": async (options, connection, dependencies) =>
    dependencies.listDesignTokens({
      ...connection,
      filter: options.filter,
      withUsage: options.withUsage,
      sort: designTokenSortOption(options.sort),
    }),
  "create-design-token": async (options, connection, dependencies) =>
    dependencies.createDesignTokens({
      ...connection,
      tokens: await readInputArray<CreateDesignTokensInput>(
        dependencies,
        options
      ),
    }),
  "update-design-token-styles": async (options, connection, dependencies) =>
    dependencies.updateDesignTokenStyles({
      ...connection,
      designTokenId: requireOption(options.designToken, "--design-token"),
      updates: await readInputArray<UpdateDesignTokenStylesInput>(
        dependencies,
        options
      ),
    }),
  "delete-design-token-styles": async (options, connection, dependencies) =>
    dependencies.deleteDesignTokenStyles({
      ...connection,
      designTokenId: requireOption(options.designToken, "--design-token"),
      deletions: await readInputArray<DeleteDesignTokenStylesInput>(
        dependencies,
        options
      ),
    }),
  "attach-design-token": async (options, connection, dependencies) =>
    dependencies.attachDesignToken({
      ...connection,
      designTokenId: requireOption(options.designToken, "--design-token"),
      instanceIds: await readInputArray<string[]>(dependencies, options),
      position: options.position,
    }),
  "detach-design-token": async (options, connection, dependencies) =>
    dependencies.detachDesignToken({
      ...connection,
      designTokenId: requireOption(options.designToken, "--design-token"),
      instanceIds: await readInputArray<string[]>(dependencies, options),
    }),
  "extract-design-token": async (options, connection, dependencies) =>
    dependencies.extractDesignToken({
      ...connection,
      ...(await readInputObject<ExtractDesignTokenInput>(
        dependencies,
        options
      )),
    }),
  "list-css-variables": async (options, connection, dependencies) =>
    dependencies.listCssVariables({
      ...connection,
      filter: options.filter,
      withUsage: options.withUsage,
    }),
  "define-css-variable": async (options, connection, dependencies) =>
    dependencies.defineCssVariables({
      ...connection,
      vars: await readInputObject<DefineCssVariablesInput>(
        dependencies,
        options
      ),
      overwrite: options.overwrite,
    }),
  "delete-css-variable": async (options, connection, dependencies) => {
    requireTrueOption(options.confirm, "--confirm");
    return dependencies.deleteCssVariables({
      ...connection,
      names: await readInputArray<DeleteCssVariablesInput>(
        dependencies,
        options
      ),
      force: options.force,
    });
  },
  "rewrite-css-variable-refs": async (options, connection, dependencies) =>
    dependencies.rewriteCssVariableRefs({
      ...connection,
      map: await readInputObject<RewriteCssVariableRefsInput>(
        dependencies,
        options
      ),
      scopeRegex: options.scopeRegex,
    }),
  "list-variables": async (options, connection, dependencies) =>
    dependencies.listVariables({
      ...connection,
      scopeInstanceId: options.scopeInstance,
    }),
  "create-variable": async (options, connection, dependencies) =>
    dependencies.createVariable({
      ...connection,
      dataSourceId: options.variable,
      scopeInstanceId: requireOption(options.scopeInstance, "--scope-instance"),
      name: requireOption(options.name, "--name"),
      value: parseVariableValue(options.valueType, options.value),
    }),
  "update-variable": async (options, connection, dependencies) =>
    dependencies.updateVariable({
      ...connection,
      dataSourceId: requireOption(options.variable, "--variable"),
      values: {
        scopeInstanceId: options.scopeInstance,
        name: options.name,
        value: parseOptionalVariableValue(options),
      },
    }),
  "delete-variable": async (options, connection, dependencies) =>
    dependencies.deleteVariable({
      ...connection,
      dataSourceId: requireOption(options.variable, "--variable"),
    }),
  "list-resources": async (options, connection, dependencies) =>
    dependencies.listResources({
      ...connection,
      scopeInstanceId: options.scopeInstance,
    }),
  "create-resource": async (options, connection, dependencies) =>
    dependencies.createResource({
      ...connection,
      resourceId: options.resource,
      resource: (await getResourceFields(
        dependencies,
        options,
        true
      )) as ResourceFieldsInput,
      dataSourceId: options.dataSource,
      scopeInstanceId: options.scopeInstance,
      dataSourceName: options.dataSourceName,
    }),
  "update-resource": async (options, connection, dependencies) =>
    dependencies.updateResource({
      ...connection,
      resourceId: requireOption(options.resource, "--resource"),
      values: (await getResourceFields(
        dependencies,
        options,
        false
      )) as Partial<ResourceFieldsInput>,
      dataSourceName: options.dataSourceName,
      scopeInstanceId: options.scopeInstance,
    }),
  "delete-resource": async (options, connection, dependencies) =>
    dependencies.deleteResource({
      ...connection,
      resourceId: requireOption(options.resource, "--resource"),
      force: options.force,
    }),
  publish: async (options, connection, dependencies) =>
    dependencies.publish({
      ...connection,
      target: publishTargetValue(options.target),
      domains: listStringOption(options.domain),
      message: options.message,
      idempotencyKey: options.idempotencyKey,
    }),
  "list-publishes": async (_options, connection, dependencies) =>
    dependencies.listPublishes(connection),
  "get-publish-job": async (options, connection, dependencies) =>
    dependencies.getPublishJob({
      ...connection,
      jobId: requireOption(options.job, "--job"),
    }),
  unpublish: async (options, connection, dependencies) => {
    requireTrueOption(options.confirm, "--confirm");
    return dependencies.unpublish({
      ...connection,
      target: publishTargetValue(options.target),
      domains: listStringOption(options.domain),
      message: options.message,
      idempotencyKey: options.idempotencyKey,
    });
  },
  "list-domains": async (_options, connection, dependencies) =>
    dependencies.listDomains(connection),
  "create-domain": async (options, connection, dependencies) =>
    dependencies.createDomain({
      ...connection,
      domain: requireSingleOption(options.domain, "--domain"),
    }),
  "update-domain": async (options, connection, dependencies) =>
    dependencies.updateDomain({
      ...connection,
      domainId: requireOption(options.domainId, "--domain-id"),
      updates: {
        ...(await readInputObject<UpdateDomainInput>(dependencies, options)),
        domain: typeof options.domain === "string" ? options.domain : undefined,
      },
    }),
  "delete-domain": async (options, connection, dependencies) => {
    requireTrueOption(options.confirm, "--confirm");
    return dependencies.deleteDomain({
      ...connection,
      domainId: requireOption(options.domainId, "--domain-id"),
    });
  },
  "verify-domain": async (options, connection, dependencies) =>
    dependencies.verifyDomain({
      ...connection,
      domainId: requireOption(options.domainId, "--domain-id"),
    }),
  "list-assets": async (options, connection, dependencies) =>
    dependencies.listAssets({
      ...connection,
      type: assetListTypeOption(options.type),
      sort: options.sort,
      withUsage: options.withUsage,
      cursor: options.cursor,
      limit: options.limit,
    }),
  "upload-asset": async (options, connection, dependencies) =>
    dependencies.uploadProjectAsset({
      ...connection,
      asset: await readInputObject<UploadAssetInput>(dependencies, options),
      readAssetData: readAssetData(dependencies, options.assetsDir),
    }),
  "upload-assets": async (options, connection, dependencies) =>
    dependencies.uploadProjectAssets({
      ...connection,
      assets: await readInputArray<UploadAssetsInput>(dependencies, options),
      readAssetData: readAssetData(dependencies, options.assetsDir),
    }),
  "find-asset-usage": async (options, connection, dependencies) =>
    dependencies.findAssetUsage({
      ...connection,
      assetId: requireSingleOption(options.asset, "--asset"),
    }),
  "replace-asset": async (options, connection, dependencies) => {
    requireTrueOption(options.confirm, "--confirm");
    return dependencies.replaceAsset({
      ...connection,
      fromAssetId: requireOption(options.from, "--from"),
      toAssetId: requireOption(options.to, "--to"),
    });
  },
  "delete-asset": async (options, connection, dependencies) => {
    requireTrueOption(options.confirm, "--confirm");
    return dependencies.deleteAssets({
      ...connection,
      assetIdsOrPrefixes: requireListOption(options.asset, "--asset"),
      force: options.force,
    });
  },
} satisfies Record<string, ApiCommandHandler>;

export type ApiCommandName = keyof typeof apiCommandHandlers;

export const apiCommand = async (
  options: ApiCommandOptions,
  dependencies = defaultDependencies
) => {
  const start = Date.now();
  let projectId: string | undefined;
  try {
    if (options.json !== true) {
      throw new Error(`${options.command} currently requires --json.`);
    }

    const connection = await resolveConnection(dependencies);
    projectId = connection.projectId;
    const apiConnection = {
      ...connection,
      headers: apiCompatibilityHeaders,
    };

    const query = apiCommandHandlers[options.command];
    const data = await query(options, apiConnection, dependencies);
    printJson({
      ok: true,
      data,
      meta: {
        command: options.command,
        projectId: connection.projectId,
        durationMs: Date.now() - start,
      },
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    if (options.json === true) {
      const code = getErrorCode(error);
      printJson({
        ok: false,
        error: {
          code,
          message,
          retry: getRetryHint(code),
        },
        meta: {
          command: options.command,
          projectId,
          durationMs: Date.now() - start,
        },
      });
    } else {
      console.error(message);
    }
    throw new HandledCliError();
  }
};
