import type { KeyboardEvent, FocusEvent } from "react";
import { Box, Flex, styled, Text } from "@webstudio-is/design-system";
import { PageIcon, TextCapitalizeIcon } from "@webstudio-is/icons";
import { wsVideoLoader } from "@webstudio-is/image";
import { UploadingAnimation } from "./uploading-animation";
import { AssetInfo, assetInfoCssVars } from "./asset-info";
import type { AssetContainer } from "~/builder/shared/assets";
import { Image } from "./image";
import brokenImage from "~/shared/images/broken-image-placeholder.svg";
import { theme } from "@webstudio-is/design-system";
import {
  formatAssetName,
  parseAssetName,
} from "~/builder/shared/assets/asset-utils";
import type { IconComponent } from "@webstudio-is/icons";
import {
  FILE_EXTENSIONS_BY_CATEGORY,
  IMAGE_EXTENSIONS,
  isVideoFormat,
} from "@webstudio-is/asset-uploader";
import type { FileCategory } from "@webstudio-is/asset-uploader";

const FORMAT_CATEGORIES = FILE_EXTENSIONS_BY_CATEGORY;

const CATEGORY_ICON_MAP: Partial<Record<FileCategory, IconComponent>> = {
  fonts: TextCapitalizeIcon,
  documents: PageIcon,
};

const isImageFormat = (format: string): boolean => {
  return IMAGE_EXTENSIONS.includes(format.toLowerCase());
};

const getFileIcon = (format: string): IconComponent => {
  const lowerFormat = format.toLowerCase();

  // Check which category this format belongs to
  for (const [category, extensions] of Object.entries(FORMAT_CATEGORIES)) {
    if (extensions.includes(lowerFormat)) {
      return CATEGORY_ICON_MAP[category as FileCategory] ?? PageIcon;
    }
  }

  // Default to PageIcon if not found in any category
  return PageIcon;
};

const StyledWebstudioImage = styled(Image, {
  position: "absolute",
  width: "100%",
  height: "100%",
  objectFit: "contain",

  // This is shown only if an image was not loaded and broken
  // From the spec:
  // - The pseudo-elements generated by ::before and ::after are contained by the element's formatting box,
  //   and thus don't apply to "replaced" elements such as <img>, or to <br> elements
  // Not in spec but supported by all browsers:
  // - broken image is not a "replaced" element so this style is applied
  "&::after": {
    content: "' '",
    position: "absolute",
    width: "100%",
    height: "100%",
    left: 0,
    top: 0,
    backgroundSize: "contain",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    backgroundImage: `url(${brokenImage})`,
  },
});

const StyledWebstudioVideo = styled("video", {
  position: "absolute",
  width: "100%",
  height: "100%",
  objectFit: "contain",

  // This is shown only if an image was not loaded and broken
  // From the spec:
  // - The pseudo-elements generated by ::before and ::after are contained by the element's formatting box,
  //   and thus don't apply to "replaced" elements such as <img>, or to <br> elements
  // Not in spec but supported by all browsers:
  // - broken image is not a "replaced" element so this style is applied
  "&::after": {
    content: "' '",
    position: "absolute",
    width: "100%",
    height: "100%",
    left: 0,
    top: 0,
    backgroundSize: "contain",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    backgroundImage: `url(${brokenImage})`,
  },
});

const ThumbnailContainer = styled(Box, {
  position: "relative",
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
  flexDirection: "column",
  borderRadius: theme.borderRadius[4],
  outline: "none",
  gap: theme.spacing[3],
  overflow: "hidden",
  padding: 2,
  "&:hover": {
    ...assetInfoCssVars({ show: true }),
    backgroundColor: theme.colors.backgroundAssetcardHover,
  },
  variants: {
    status: {
      uploading: {},
      uploaded: {},
      deleting: {},
    },
    state: {
      selected: {
        outline: `1px solid ${theme.colors.borderFocus}`,
        outlineOffset: -1,
        backgroundColor: theme.colors.backgroundAssetcardHover,
        ...assetInfoCssVars({ show: true }),
      },
    },
  },
});

const Thumbnail = styled(Box, {
  width: "100%",
  height: theme.spacing[19],
  flexShrink: 0,
  position: "relative",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
});

const GenericFilePreview = ({
  ext,
  format,
}: {
  ext: string;
  format: string;
}) => {
  const Icon = getFileIcon(format);
  const showExtension = Icon === PageIcon;

  return (
    <Box css={{ position: "relative" }}>
      <Icon size={48} strokeWidth={0.5} />
      {showExtension && (
        <Text
          variant="tiny"
          color="subtle"
          css={{
            position: "absolute",
            top: 30,
            left: "50%",
            transform: "translateX(-50%)",
          }}
        >
          {ext.toUpperCase()}
        </Text>
      )}
    </Box>
  );
};

type AssetThumbnailProps = {
  assetContainer: AssetContainer;
  onSelect: (assetContainer?: AssetContainer) => void;
  onChange?: (assetContainer: AssetContainer) => void;
  state?: "selected";
};

export const AssetThumbnail = ({
  assetContainer,
  onSelect,
  onChange,
  state,
}: AssetThumbnailProps) => {
  const { asset } = assetContainer;
  const { basename, ext } = parseAssetName(asset.name);
  const alt = asset.description ?? formatAssetName(asset);
  const isUploading = assetContainer.status === "uploading";

  return (
    <ThumbnailContainer
      title={alt}
      tabIndex={0}
      status={assetContainer.status}
      state={state}
      onFocus={() => {
        onSelect?.(assetContainer);
      }}
      onBlur={(event: FocusEvent) => {
        const isFocusWithin = event.currentTarget.contains(event.relatedTarget);
        if (isFocusWithin === false) {
          onSelect();
        }
      }}
      onKeyDown={(event: KeyboardEvent) => {
        if (event.code === "Enter") {
          onChange?.(assetContainer);
        }
      }}
    >
      <Thumbnail
        onClick={() => {
          onChange?.(assetContainer);
        }}
      >
        {isImageFormat(asset.format) ? (
          // Image files - show preview
          <StyledWebstudioImage
            assetId={asset.id}
            name={asset.name}
            objectURL={
              assetContainer.status === "uploading"
                ? assetContainer.objectURL
                : undefined
            }
            alt={alt}
            // width={64} used for Image optimizations it should be approximately equal to the width of the picture on the screen in px
            width={64}
          />
        ) : isVideoFormat(asset.format) ? (
          // Video files - show video thumbnail (first frame)
          <StyledWebstudioVideo
            src={
              assetContainer.status === "uploading"
                ? assetContainer.objectURL
                : wsVideoLoader({ src: asset.name })
            }
          />
        ) : (
          // Other files - show icon based on category
          <GenericFilePreview ext={ext} format={asset.format} />
        )}
      </Thumbnail>
      <Flex css={{ width: "100%", paddingBottom: 4 }} justify="center">
        <Text variant="tiny" truncate>
          {asset.filename ?? basename}
        </Text>
        <Text variant="tiny">.{ext}</Text>
      </Flex>
      {assetContainer.status === "uploaded" && (
        <AssetInfo asset={assetContainer.asset} />
      )}
      {isUploading && <UploadingAnimation />}
    </ThumbnailContainer>
  );
};
