import { useEffect, useRef, type KeyboardEvent, type FocusEvent } from "react";
import { Box, styled, Text } from "@webstudio-is/design-system";
import { PageIcon, TextCapitalizeIcon } from "@webstudio-is/icons";
import { wsVideoLoader } from "@webstudio-is/image";
import { UploadingAnimation } from "./uploading-animation";
import { AssetInfo } from "./asset-info";
import type { AssetContainer } from "~/builder/shared/assets";
import { Image } from "./image";
import brokenImage from "~/shared/images/broken-image-placeholder.svg";
import {
  formatAssetName,
  parseAssetName,
} from "@webstudio-is/project-build/runtime";
import type { IconComponent } from "@webstudio-is/icons";
import type { AllowedFileExtension } from "@webstudio-is/sdk";
import {
  FILE_EXTENSIONS_BY_CATEGORY,
  detectAssetType,
} from "@webstudio-is/sdk";
import type { MimeCategory } from "@webstudio-is/sdk";
import { draggable } from "@atlaskit/pragmatic-drag-and-drop/element/adapter";
import { AssetThumbnailCard } from "./asset-thumbnail-card";

const FORMAT_CATEGORIES = FILE_EXTENSIONS_BY_CATEGORY;

const CATEGORY_ICON_MAP: Partial<Record<MimeCategory, IconComponent>> = {
  font: TextCapitalizeIcon,
};

const getFileIcon = (format: string): IconComponent => {
  const lowerFormat = format.toLowerCase();

  // Check which category this format belongs to
  for (const [category, extensions] of Object.entries(FORMAT_CATEGORIES)) {
    if (extensions.includes(lowerFormat as AllowedFileExtension)) {
      return CATEGORY_ICON_MAP[category as MimeCategory] ?? PageIcon;
    }
  }

  // Default to PageIcon if not found in any category
  return PageIcon;
};

const mediaPreviewStyle = {
  position: "absolute",
  width: "100%",
  height: "100%",
  objectFit: "contain",

  // This is shown only if an image was not loaded and broken
  // From the spec:
  // - The pseudo-elements generated by ::before and ::after are contained by the element's formatting box,
  //   and thus don't apply to "replaced" elements such as <img>, or to <br> elements
  // Not in spec but supported by all browsers:
  // - broken image is not a "replaced" element so this style is applied
  "&::after": {
    content: "' '",
    position: "absolute",
    width: "100%",
    height: "100%",
    left: 0,
    top: 0,
    backgroundSize: "contain",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    backgroundImage: `url(${brokenImage})`,
  },
} as const;

const StyledWebstudioImage = styled(Image, mediaPreviewStyle);
const StyledWebstudioVideo = styled("video", mediaPreviewStyle);

const GenericFilePreview = ({
  ext,
  format,
}: {
  ext: string;
  format: string;
}) => {
  const Icon = getFileIcon(format);
  const showExtension = Icon === PageIcon;

  return (
    <Box css={{ position: "relative" }}>
      <Icon size={48} strokeWidth={0.5} />
      {showExtension && (
        <Text
          variant="tiny"
          color="subtle"
          css={{
            position: "absolute",
            top: 30,
            left: "50%",
            transform: "translateX(-50%)",
          }}
        >
          {ext.toUpperCase()}
        </Text>
      )}
    </Box>
  );
};

type AssetThumbnailProps = {
  assetContainer: AssetContainer;
  onSelect: (assetContainer?: AssetContainer) => void;
  onChange?: (assetContainer: AssetContainer) => void;
  state?: "selected";
  folderPath?: string;
  canDrag?: boolean;
};

export const AssetThumbnail = ({
  assetContainer,
  onSelect,
  onChange,
  state,
  folderPath,
  canDrag = false,
}: AssetThumbnailProps) => {
  const elementRef = useRef<HTMLElement>(null);
  const { asset } = assetContainer;
  const { basename, ext } = parseAssetName(asset.name);
  const alt = asset.description ?? formatAssetName(asset);
  const isUploading = assetContainer.status === "uploading";
  const assetType = detectAssetType(asset.name);

  useEffect(() => {
    const element = elementRef.current;
    if (element === null || canDrag === false || isUploading) {
      return;
    }
    return draggable({
      element,
      getInitialData: () => ({ kind: "asset", id: asset.id }),
    });
  }, [asset.id, canDrag, isUploading]);

  return (
    <AssetThumbnailCard
      ref={elementRef}
      title={alt}
      tabIndex={0}
      selected={state === "selected"}
      preview={
        assetType === "image" ? (
          <StyledWebstudioImage
            assetId={asset.id}
            name={asset.name}
            objectURL={
              assetContainer.status === "uploading"
                ? assetContainer.objectURL
                : undefined
            }
            alt={alt}
            width={64}
          />
        ) : assetType === "video" ? (
          <StyledWebstudioVideo
            src={
              assetContainer.status === "uploading"
                ? assetContainer.objectURL
                : wsVideoLoader({ src: asset.name })
            }
          />
        ) : (
          <GenericFilePreview ext={ext} format={asset.format} />
        )
      }
      label={asset.filename ?? basename}
      labelSuffix={`.${ext}`}
      path={folderPath}
      onPreviewClick={() => onChange?.(assetContainer)}
      onFocus={() => {
        onSelect?.(assetContainer);
      }}
      onBlur={(event: FocusEvent) => {
        const isFocusWithin = event.currentTarget.contains(event.relatedTarget);
        if (isFocusWithin === false) {
          onSelect();
        }
      }}
      onKeyDown={(event: KeyboardEvent) => {
        if (event.code === "Enter") {
          onChange?.(assetContainer);
        }
      }}
    >
      {assetContainer.status === "uploaded" && (
        <AssetInfo asset={assetContainer.asset} />
      )}
      {isUploading && <UploadingAnimation />}
    </AssetThumbnailCard>
  );
};
