import {
  useEffect,
  useRef,
  useState,
  type KeyboardEvent,
  type FocusEvent,
} from "react";
import { useStore } from "@nanostores/react";
import {
  Box,
  ContextMenu,
  ContextMenuTrigger,
  styled,
  Text,
} from "@webstudio-is/design-system";
import { PageIcon, TextCapitalizeIcon } from "@webstudio-is/icons";
import { wsVideoLoader } from "@webstudio-is/image";
import { UploadingAnimation } from "./uploading-animation";
import { AssetDeleteDialog, AssetInfo } from "./asset-info";
import type { AssetContainer } from "~/builder/shared/assets";
import { Image } from "./image";
import brokenImage from "~/shared/images/broken-image-placeholder.svg";
import {
  formatAssetName,
  parseAssetName,
} from "@webstudio-is/project-build/runtime";
import type { IconComponent } from "@webstudio-is/icons";
import type { AllowedFileExtension } from "@webstudio-is/sdk";
import {
  FILE_EXTENSIONS_BY_CATEGORY,
  IMAGE_MIME_TYPES,
  detectAssetType,
} from "@webstudio-is/sdk";
import type { MimeCategory } from "@webstudio-is/sdk";
import { draggable } from "@atlaskit/pragmatic-drag-and-drop/element/adapter";
import {
  AssetThumbnailAction,
  AssetThumbnailCard,
  AssetThumbnailGroup,
} from "./asset-thumbnail-card";
import { $authPermit, $permissions } from "~/shared/nano-states";
import { replaceAsset } from "~/builder/shared/assets";
import { validateFiles } from "~/builder/shared/assets/asset-upload";
import { getAssetUrl } from "~/builder/shared/assets/asset-utils";
import {
  copyAssetManagerItem,
  cutAssetManagerItem,
  duplicateAssetManagerItem,
} from "./asset-manager-clipboard";
import {
  AssetManagerItemContextMenuContent,
  type AssetManagerItemActions,
} from "./asset-manager-item-menu";

const FORMAT_CATEGORIES = FILE_EXTENSIONS_BY_CATEGORY;

const CATEGORY_ICON_MAP: Partial<Record<MimeCategory, IconComponent>> = {
  font: TextCapitalizeIcon,
};

const getFileIcon = (format: string): IconComponent => {
  const lowerFormat = format.toLowerCase();

  // Check which category this format belongs to
  for (const [category, extensions] of Object.entries(FORMAT_CATEGORIES)) {
    if (extensions.includes(lowerFormat as AllowedFileExtension)) {
      return CATEGORY_ICON_MAP[category as MimeCategory] ?? PageIcon;
    }
  }

  // Default to PageIcon if not found in any category
  return PageIcon;
};

const mediaPreviewStyle = {
  position: "absolute",
  width: "100%",
  height: "100%",
  objectFit: "contain",

  // This is shown only if an image was not loaded and broken
  // From the spec:
  // - The pseudo-elements generated by ::before and ::after are contained by the element's formatting box,
  //   and thus don't apply to "replaced" elements such as <img>, or to <br> elements
  // Not in spec but supported by all browsers:
  // - broken image is not a "replaced" element so this style is applied
  "&::after": {
    content: "' '",
    position: "absolute",
    width: "100%",
    height: "100%",
    left: 0,
    top: 0,
    backgroundSize: "contain",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    backgroundImage: `url(${brokenImage})`,
  },
} as const;

const StyledWebstudioImage = styled(Image, mediaPreviewStyle);
const StyledWebstudioVideo = styled("video", mediaPreviewStyle);

const GenericFilePreview = ({
  ext,
  format,
}: {
  ext: string;
  format: string;
}) => {
  const Icon = getFileIcon(format);
  const showExtension = Icon === PageIcon;

  return (
    <Box css={{ position: "relative" }}>
      <Icon size={48} strokeWidth={0.5} />
      {showExtension && (
        <Text
          variant="tiny"
          color="subtle"
          css={{
            position: "absolute",
            top: 30,
            left: "50%",
            transform: "translateX(-50%)",
          }}
        >
          {ext.toUpperCase()}
        </Text>
      )}
    </Box>
  );
};

type AssetThumbnailProps = {
  assetContainer: AssetContainer;
  onSelect: (assetContainer?: AssetContainer) => void;
  onChange?: (assetContainer: AssetContainer) => void;
  selected?: boolean;
  folderPath?: string;
  canDrag?: boolean;
  onElementChange?: (element: HTMLElement | null) => void;
};

export const AssetThumbnail = ({
  assetContainer,
  onSelect,
  onChange,
  selected,
  folderPath,
  canDrag = false,
  onElementChange,
}: AssetThumbnailProps) => {
  const elementRef = useRef<HTMLElement | null>(null);
  const replaceInputRef = useRef<HTMLInputElement>(null);
  const [detailsOpen, setDetailsOpen] = useState(false);
  const [focusName, setFocusName] = useState(false);
  const [deleteOpen, setDeleteOpen] = useState(false);
  const authPermit = useStore($authPermit);
  const { canDownloadAssets } = useStore($permissions);
  const { asset } = assetContainer;
  const { basename, ext } = parseAssetName(asset.name);
  const alt = asset.description ?? formatAssetName(asset);
  const isUploading = assetContainer.status === "uploading";
  const assetType = detectAssetType(asset.name);
  const item = {
    type: "asset" as const,
    id: asset.id,
    projectId:
      assetContainer.status === "uploaded"
        ? assetContainer.asset.projectId
        : "uploading",
  };
  const download = () => {
    if (assetContainer.status !== "uploaded") {
      return;
    }
    const link = document.createElement("a");
    link.download = formatAssetName(assetContainer.asset);
    link.href = getAssetUrl(assetContainer.asset, window.location.origin).href;
    link.click();
  };
  const actions: AssetManagerItemActions =
    assetContainer.status === "uploading"
      ? {}
      : {
          ...(authPermit === "view"
            ? {}
            : {
                rename: () => {
                  setFocusName(true);
                  setDetailsOpen(true);
                },
                cut: () => cutAssetManagerItem(item),
                copy: () => copyAssetManagerItem(item),
                duplicate: () => duplicateAssetManagerItem(item),
                delete: () => setDeleteOpen(true),
                ...(asset.type === "image"
                  ? { replace: () => replaceInputRef.current?.click() }
                  : {}),
              }),
          ...(authPermit !== "view" && canDownloadAssets ? { download } : {}),
        };

  const handleReplaceFile = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = validateFiles(Array.from(event.target.files ?? []))[0];
    if (file !== undefined) {
      replaceAsset(asset.id, file);
    }
    event.target.value = "";
  };

  useEffect(() => {
    const element = elementRef.current;
    if (element === null || canDrag === false || isUploading) {
      return;
    }
    return draggable({
      element,
      getInitialData: () => ({ kind: "asset", id: asset.id }),
    });
  }, [asset.id, canDrag, isUploading]);

  return (
    <>
      <input
        ref={replaceInputRef}
        type="file"
        accept={IMAGE_MIME_TYPES.join(", ")}
        hidden
        onChange={handleReplaceFile}
      />
      <ContextMenu>
        <ContextMenuTrigger asChild>
          <AssetThumbnailGroup
            selected={selected}
            onFocus={() => onSelect(assetContainer)}
            onBlur={(event: FocusEvent) => {
              if (event.currentTarget.contains(event.relatedTarget) === false) {
                onSelect();
              }
            }}
          >
            <AssetThumbnailCard
              ref={(element) => {
                elementRef.current = element;
                onElementChange?.(element);
              }}
              as="button"
              type="button"
              title={alt}
              selected={selected}
              preview={
                assetType === "image" ? (
                  <StyledWebstudioImage
                    assetId={asset.id}
                    name={asset.name}
                    objectURL={
                      assetContainer.status === "uploading"
                        ? assetContainer.objectURL
                        : undefined
                    }
                    alt={alt}
                    width={64}
                  />
                ) : assetType === "video" ? (
                  <StyledWebstudioVideo
                    src={
                      assetContainer.status === "uploading"
                        ? assetContainer.objectURL
                        : wsVideoLoader({ src: asset.name })
                    }
                  />
                ) : (
                  <GenericFilePreview ext={ext} format={asset.format} />
                )
              }
              label={asset.filename ?? basename}
              labelSuffix={`.${ext}`}
              path={folderPath}
              onContextMenu={() => onSelect(assetContainer)}
              onPreviewClick={() => onChange?.(assetContainer)}
              onKeyDown={(event: KeyboardEvent) => {
                if (event.code === "Enter") {
                  onChange?.(assetContainer);
                }
              }}
            >
              {isUploading && <UploadingAnimation />}
            </AssetThumbnailCard>
            {assetContainer.status === "uploaded" && (
              <AssetThumbnailAction>
                <AssetInfo
                  asset={assetContainer.asset}
                  open={detailsOpen}
                  onOpenChange={(open) => {
                    setDetailsOpen(open);
                    if (open === false) {
                      setFocusName(false);
                    }
                  }}
                  actions={actions}
                  focusName={focusName}
                />
              </AssetThumbnailAction>
            )}
          </AssetThumbnailGroup>
        </ContextMenuTrigger>
        <AssetManagerItemContextMenuContent actions={actions} />
      </ContextMenu>
      {assetContainer.status === "uploaded" && (
        <AssetDeleteDialog
          asset={assetContainer.asset}
          open={deleteOpen}
          onOpenChange={setDeleteOpen}
        />
      )}
    </>
  );
};
