// This file is generated by apps/builder/scripts/generate-server-only-api-metadata.ts.
// Do not edit manually.

import type {
  InputJsonSchema,
  PublicApiOperationNamespace,
  PublicApiOperationPermit,
} from "../runtime-contracts";

export const serverOnlyRouterOperationMetadata = {
  "auth.me": {
    id: "auth.me",
    command: "whoami",
    method: "query",
    path: "api.auth.me",
    client: "getApiTokenInfo",
    permit: "view",
    inputSchema: {
      type: "object",
      additionalProperties: true,
      properties: {},
      required: [],
    },
  },
  "projects.permissions": {
    id: "projects.permissions",
    command: "permissions",
    method: "query",
    path: "api.projects.permissions",
    client: "getProjectPermissions",
    permit: "view",
    inputSchema: {
      type: "object",
      properties: {},
      required: [],
      additionalProperties: true,
    },
  },
  "projects.get": {
    id: "projects.get",
    command: "inspect",
    method: "query",
    path: "api.projects.get",
    client: "getProjectInfo",
    permit: "view",
    inputSchema: {
      type: "object",
      properties: {},
      required: [],
      additionalProperties: true,
    },
  },
  "build.get": {
    id: "build.get",
    command: "snapshot",
    method: "query",
    path: "api.build.get",
    client: "getBuildSnapshot",
    permit: "view",
    inputSchema: {
      type: "object",
      properties: {
        include: {
          type: "array",
          items: {
            type: "string",
            enum: [
              "designTokens",
              "pages",
              "folders",
              "instances",
              "props",
              "styles",
              "styleSources",
              "styleSourceSelections",
              "variables",
              "resources",
              "assets",
              "assetFolders",
              "breakpoints",
              "projectSettings",
              "marketplaceProduct",
            ],
          },
        },
        version: {
          type: "integer",
          minimum: -9007199254740991,
          maximum: 9007199254740991,
        },
      },
      required: [],
    },
  },
  "build.patch": {
    id: "build.patch",
    command: "apply-patch",
    method: "mutation",
    path: "api.build.patch",
    client: "applyBuildPatch",
    permit: "build",
    invalidatesNamespaces: [
      "pages",
      "instances",
      "props",
      "styles",
      "styleSources",
      "styleSourceSelections",
      "dataSources",
      "resources",
      "assets",
      "assetFolders",
      "breakpoints",
      "projectSettings",
      "marketplaceProduct",
    ],
    inputSchema: {
      type: "object",
      properties: {
        baseVersion: {
          type: "integer",
          minimum: -9007199254740991,
          maximum: 9007199254740991,
        },
        transactions: {
          minItems: 1,
          type: "array",
          items: {
            type: "object",
            properties: {
              id: {
                type: "string",
                minLength: 1,
              },
              payload: {
                type: "array",
                items: {
                  type: "object",
                  properties: {
                    namespace: {
                      type: "string",
                      enum: [
                        "pages",
                        "instances",
                        "props",
                        "styles",
                        "styleSources",
                        "styleSourceSelections",
                        "dataSources",
                        "resources",
                        "assets",
                        "assetFolders",
                        "breakpoints",
                        "projectSettings",
                        "marketplaceProduct",
                      ],
                    },
                    patches: {
                      type: "array",
                      items: {
                        anyOf: [
                          {
                            type: "object",
                            properties: {
                              op: {
                                type: "string",
                                const: "add",
                              },
                              path: {
                                type: "array",
                                items: {
                                  anyOf: [
                                    {
                                      type: "string",
                                    },
                                    {
                                      type: "number",
                                    },
                                  ],
                                },
                              },
                              value: {},
                            },
                            required: ["op", "path"],
                          },
                          {
                            type: "object",
                            properties: {
                              op: {
                                type: "string",
                                const: "replace",
                              },
                              path: {
                                type: "array",
                                items: {
                                  anyOf: [
                                    {
                                      type: "string",
                                    },
                                    {
                                      type: "number",
                                    },
                                  ],
                                },
                              },
                              value: {},
                            },
                            required: ["op", "path"],
                          },
                          {
                            type: "object",
                            properties: {
                              op: {
                                type: "string",
                                const: "remove",
                              },
                              path: {
                                type: "array",
                                items: {
                                  anyOf: [
                                    {
                                      type: "string",
                                    },
                                    {
                                      type: "number",
                                    },
                                  ],
                                },
                              },
                            },
                            required: ["op", "path"],
                          },
                        ],
                      },
                    },
                  },
                  required: ["namespace", "patches"],
                },
              },
            },
            required: ["id", "payload"],
          },
        },
      },
      required: ["baseVersion", "transactions"],
    },
  },
  "publish.list": {
    id: "publish.list",
    command: "list-publishes",
    method: "query",
    path: "api.publish.list",
    client: "listPublishes",
    permit: "view",
    inputSchema: {
      type: "object",
      properties: {
        cursor: {
          type: "string",
        },
        limit: {
          type: "integer",
          minimum: 1,
          maximum: 200,
        },
        verbose: {
          description:
            "Expand the same result with complete records and diagnostics. Omit for compact output.",
          type: "boolean",
        },
      },
      required: [],
    },
  },
  "publish.create": {
    id: "publish.create",
    command: "publish",
    method: "mutation",
    path: "api.publish.create",
    client: "publish",
    permit: "edit",
    inputSchema: {
      type: "object",
      properties: {
        target: {
          type: "string",
          enum: ["staging", "production"],
        },
        domains: {
          type: "array",
          items: {
            type: "string",
          },
        },
        message: {
          type: "string",
        },
        idempotencyKey: {
          type: "string",
        },
      },
      required: ["target"],
    },
  },
  "publish.getJob": {
    id: "publish.getJob",
    command: "get-publish-job",
    method: "query",
    path: "api.publish.getJob",
    client: "getPublishJob",
    permit: "view",
    inputSchema: {
      type: "object",
      properties: {
        jobId: {
          type: "string",
        },
      },
      required: ["jobId"],
    },
  },
  "publish.unpublish": {
    id: "publish.unpublish",
    command: "unpublish",
    method: "mutation",
    path: "api.publish.unpublish",
    client: "unpublish",
    permit: "edit",
    inputSchema: {
      type: "object",
      properties: {
        target: {
          type: "string",
          enum: ["staging", "production"],
        },
        domains: {
          type: "array",
          items: {
            type: "string",
          },
        },
        message: {
          type: "string",
        },
        idempotencyKey: {
          type: "string",
        },
      },
      required: ["target"],
    },
  },
  "domains.list": {
    id: "domains.list",
    command: "list-domains",
    method: "query",
    path: "api.domains.list",
    client: "listDomains",
    permit: "view",
    inputSchema: {
      type: "object",
      properties: {
        cursor: {
          type: "string",
        },
        limit: {
          type: "integer",
          minimum: 1,
          maximum: 200,
        },
        verbose: {
          description:
            "Expand the same result with complete records and diagnostics. Omit for compact output.",
          type: "boolean",
        },
      },
      required: [],
    },
  },
  "domains.create": {
    id: "domains.create",
    command: "create-domain",
    method: "mutation",
    path: "api.domains.create",
    client: "createDomain",
    permit: "admin",
    inputSchema: {
      type: "object",
      properties: {
        domain: {
          type: "string",
        },
      },
      required: ["domain"],
    },
  },
  "domains.update": {
    id: "domains.update",
    command: "update-domain",
    method: "mutation",
    path: "api.domains.update",
    client: "updateDomain",
    permit: "admin",
    inputSchema: {
      type: "object",
      properties: {
        domainId: {
          type: "string",
        },
        updates: {
          type: "object",
          properties: {
            domain: {
              type: "string",
            },
          },
          required: [],
        },
      },
      required: ["domainId", "updates"],
    },
  },
  "domains.delete": {
    id: "domains.delete",
    command: "delete-domain",
    method: "mutation",
    path: "api.domains.delete",
    client: "deleteDomain",
    permit: "admin",
    inputSchema: {
      type: "object",
      properties: {
        domainId: {
          type: "string",
        },
      },
      required: ["domainId"],
    },
  },
  "domains.verify": {
    id: "domains.verify",
    command: "verify-domain",
    method: "mutation",
    path: "api.domains.verify",
    client: "verifyDomain",
    permit: "admin",
    inputSchema: {
      type: "object",
      properties: {
        domainId: {
          type: "string",
        },
      },
      required: ["domainId"],
    },
  },
} as const satisfies Record<
  string,
  {
    id: string;
    command: string;
    method: "query" | "mutation";
    path: string;
    client: string;
    permit: PublicApiOperationPermit;
    invalidatesNamespaces?: readonly PublicApiOperationNamespace[];
    inputSchema: InputJsonSchema;
  }
>;
