export const builderRuntimeCutoverManifests = [
  {
    family: "pages-read",
    operationIds: ["pages.list", "pages.get", "pages.getByPath"] as const,
    callers: ["appRouter.api.pages"] as const,
  },
  {
    family: "page-create-update-mutations",
    operationIds: [
      "pages.create",
      "pages.update",
      "pages.updateSettings",
      "pages.updateMarketplace",
      "pages.savePathInHistory",
      "pages.setHome",
    ] as const,
    callers: ["appRouter.api.pages", "Builder pages UI"] as const,
  },
  {
    family: "page-delete-mutations",
    operationIds: ["pages.delete"] as const,
    callers: ["appRouter.api.pages"] as const,
  },
  {
    family: "page-duplicate-mutations",
    operationIds: ["pages.duplicate"] as const,
    callers: [
      "appRouter.api.pages",
      "Builder pages UI",
      "Builder copy/paste",
    ] as const,
  },
  {
    family: "page-template-operations",
    operationIds: [
      "pageTemplates.list",
      "pageTemplates.create",
      "pageTemplates.update",
      "pageTemplates.delete",
      "pageTemplates.duplicate",
      "pageTemplates.reorder",
      "pageTemplates.createPage",
    ] as const,
    callers: ["appRouter.api.pageTemplates", "Builder pages UI"] as const,
  },
  {
    family: "project-settings-operations",
    operationIds: [
      "projectSettings.get",
      "projectSettings.getMarketplaceProduct",
      "projectSettings.update",
      "projectSettings.updateMarketplaceProduct",
    ] as const,
    callers: ["appRouter.api.projectSettings"] as const,
  },
  {
    family: "redirect-operations",
    operationIds: [
      "redirects.list",
      "redirects.create",
      "redirects.update",
      "redirects.delete",
      "redirects.setAll",
    ] as const,
    callers: ["appRouter.api.redirects"] as const,
  },
  {
    family: "breakpoint-operations",
    operationIds: [
      "breakpoints.list",
      "breakpoints.create",
      "breakpoints.update",
      "breakpoints.delete",
    ] as const,
    callers: [
      "appRouter.api.breakpoints",
      "Builder breakpoint utilities",
    ] as const,
  },
  {
    family: "folders-read",
    operationIds: ["folders.list"] as const,
    callers: ["appRouter.api.folders"] as const,
  },
  {
    family: "folder-create-update-mutations",
    operationIds: [
      "folders.create",
      "folders.update",
      "folders.duplicate",
    ] as const,
    callers: ["appRouter.api.folders", "Builder pages UI"] as const,
  },
  {
    family: "folder-delete-mutations",
    operationIds: ["folders.delete"] as const,
    callers: ["appRouter.api.folders"] as const,
  },
  {
    family: "instances-read",
    operationIds: [
      "instances.list",
      "instances.inspect",
      "instances.listTexts",
    ] as const,
    callers: ["appRouter.api.instances"] as const,
  },
  {
    family: "project-inspection-read",
    operationIds: [
      "project.search",
      "project.audit",
      "project.verifyBindings",
    ] as const,
    callers: ["MCP/CLI project search and audit"] as const,
  },
  {
    family: "instance-structural-api-mutations",
    operationIds: [
      "instances.move",
      "instances.clone",
      "instances.delete",
      "instances.reparent",
      "instances.wrap",
      "instances.convert",
      "instances.unwrap",
      "instances.duplicateAfterItself",
      "instances.deleteBySelector",
    ] as const,
    callers: ["appRouter.api.instances"] as const,
  },
  {
    family: "component-insert-mutations",
    operationIds: [
      "instances.insertComponent",
      "instances.insertCollection",
      "instances.insertFragment",
      "slots.attach",
      "slots.extract",
    ] as const,
    callers: [
      "appRouter.api.instances",
      "MCP insert-collection",
      "MCP insert-fragment",
      "MCP shared Slot authoring",
      "Builder components panel",
    ] as const,
  },
  {
    family: "runtime-ui-integration",
    operationIds: ["runtimeUi.integrate"] as const,
    callers: ["MCP/CLI runtime UI authoring"] as const,
  },
  {
    family: "text-content-mutations",
    operationIds: [
      "instances.updateText",
      "instances.replaceText",
      "instances.setTextContent",
      "instances.updateTextTree",
    ] as const,
    callers: [
      "appRouter.api.instances",
      "Builder text-content controls",
    ] as const,
  },
  {
    family: "prop-mutations",
    operationIds: [
      "instances.updateProps",
      "instances.replacePropText",
      "instances.deleteProps",
      "instances.bindProps",
    ] as const,
    callers: [
      "appRouter.api.instances",
      "Builder props utilities",
      "Builder settings panel",
      "Builder CSS variable utilities",
    ] as const,
  },
  {
    family: "instance-metadata-mutations",
    operationIds: ["instances.setTag", "instances.setLabel"] as const,
    callers: ["Builder settings panel", "Builder navigator"] as const,
  },
  {
    family: "instance-layout-mutations",
    operationIds: ["instances.fillGrid"] as const,
    callers: ["Builder layout panel"] as const,
  },
  {
    family: "style-reads",
    operationIds: ["styles.getDeclarations", "designTokens.list"] as const,
    callers: ["appRouter.api.styles", "appRouter.api.designTokens"] as const,
  },
  {
    family: "style-declaration-mutations",
    operationIds: [
      "styles.updateDeclarations",
      "styles.deleteDeclarations",
      "styles.replaceValues",
      "styles.updateSelectedDeclarations",
      "styles.deleteSelectedDeclarations",
    ] as const,
    callers: ["appRouter.api.styles"] as const,
  },
  {
    family: "design-token-mutations",
    operationIds: [
      "designTokens.create",
      "designTokens.import",
      "designTokens.updateStyles",
      "designTokens.deleteStyles",
      "designTokens.attach",
      "designTokens.detach",
      "designTokens.extract",
      "designTokens.createAttached",
    ] as const,
    callers: ["appRouter.api.designTokens"] as const,
  },
  {
    family: "style-source-mutations",
    operationIds: [
      "styleSources.rename",
      "styleSources.delete",
      "styleSources.setLock",
      "styleSources.reorder",
      "styleSources.clearStyles",
      "styleSources.duplicate",
      "styleSources.convertLocalToToken",
    ] as const,
    callers: ["Builder style source controls"] as const,
  },
  {
    family: "css-variable-operations",
    operationIds: [
      "cssVariables.list",
      "cssVariables.define",
      "cssVariables.delete",
      "cssVariables.rewriteRefs",
      "cssVariables.rename",
    ] as const,
    callers: [
      "appRouter.api.cssVariables",
      "Builder CSS variable utilities",
    ] as const,
  },
  {
    family: "data-reads",
    operationIds: ["variables.list", "resources.list"] as const,
    callers: ["appRouter.api.variables", "appRouter.api.resources"] as const,
  },
  {
    family: "resource-mutations",
    operationIds: [
      "resources.create",
      "resources.update",
      "resources.replaceText",
      "resources.delete",
      "resources.upsert",
      "resources.upsertProp",
    ] as const,
    callers: ["appRouter.api.resources"] as const,
  },
  {
    family: "font-read",
    operationIds: ["fonts.list"] as const,
    callers: ["MCP/CLI font discovery"] as const,
  },
  {
    family: "asset-folder-operations",
    operationIds: [
      "assetFolders.list",
      "assetFolders.create",
      "assetFolders.update",
      "assetFolders.delete",
      "assetFolders.duplicate",
    ] as const,
    callers: ["appRouter.api.assetFolders", "Builder asset manager"] as const,
  },
  {
    family: "asset-reference-operations",
    operationIds: [
      "assets.list",
      "assets.get",
      "assets.findUsage",
      "assets.update",
      "assets.setImageDescriptions",
      "assets.add",
      "assets.duplicate",
      "assets.replace",
      "assets.delete",
    ] as const,
    callers: [
      "appRouter.api.assets",
      "Builder asset manager",
      "Builder asset replacement",
    ] as const,
  },
  {
    family: "variable-mutations",
    operationIds: [
      "variables.create",
      "variables.update",
      "variables.delete",
      "variables.deleteUnused",
    ] as const,
    callers: ["appRouter.api.variables"] as const,
  },
  {
    family: "page-tree-and-transfer-mutations",
    operationIds: [
      "pages.copy",
      "pageTransfer.insert",
      "pageTree.move",
      "pageTree.reparentOrphans",
    ] as const,
    callers: ["Builder pages UI", "Builder copy/paste"] as const,
  },
] as const;
