inputs:
  package: 
    description: 'Package.json location (relative)'
    default: null
runs:
  using: "composite"
  steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: yarn install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: false
          check-version: true
          access: 'public'
          package: $ {{ inputs.package }}