import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { format } from "prettier";
import * as React from "react";
import {
  getApiRouterProcedures,
  getProcedureInputFields,
  getProcedureInputFieldTypes,
  getProcedureMethod,
  getProcedurePublicApiOperation,
  getProcedurePublicApiPermit,
  getProcedureRequiredInputFields,
} from "../app/services/api-router-introspection.server";

(globalThis as { React?: typeof React }).React = React;

const { apiRouter } = await import("../app/services/api-router.server");

const generatedFile = join(
  dirname(fileURLToPath(import.meta.url)),
  "../../../packages/protocol/src/builder-api/__generated__/server-only-router-operation-metadata.ts"
);

const procedures = getApiRouterProcedures(apiRouter);

const metadata = Object.fromEntries(
  Object.entries(procedures).flatMap(([path, procedure]) => {
    const id = path;
    const operation = getProcedurePublicApiOperation(procedure);
    if (operation === undefined) {
      return [];
    }
    if (
      typeof operation !== "object" ||
      operation === null ||
      "command" in operation === false ||
      "client" in operation === false
    ) {
      throw new Error(`Invalid public API operation metadata for api.${path}.`);
    }
    const method = getProcedureMethod(procedure);
    const permit = getProcedurePublicApiPermit(procedure);
    if (method === undefined) {
      throw new Error(`Missing public API method for api.${path}.`);
    }
    if (typeof permit !== "string") {
      throw new Error(`Missing public API permit for api.${path}.`);
    }
    return [
      [
        id,
        {
          id,
          command: operation.command,
          method,
          path: `api.${path}`,
          client: operation.client,
          permit,
          invalidatesNamespaces:
            "invalidatesNamespaces" in operation
              ? operation.invalidatesNamespaces
              : undefined,
          inputFields: getProcedureInputFields(procedure),
          requiredInputFields: getProcedureRequiredInputFields(procedure),
          inputFieldTypes: getProcedureInputFieldTypes(procedure),
        },
      ],
    ];
  })
);

await mkdir(dirname(generatedFile), { recursive: true });

await writeFile(
  generatedFile,
  await format(
    `// This file is generated by apps/builder/scripts/generate-server-only-api-metadata.ts.
// Do not edit manually.

import type {
  PublicApiOperationNamespace,
  PublicApiOperationPermit,
} from "../runtime-contracts";

export const serverOnlyRouterOperationMetadata = ${JSON.stringify(
      metadata,
      undefined,
      2
    )} as const satisfies Record<
  string,
  {
    id: string;
    command: string;
    method: "query" | "mutation";
    path: string;
    client: string;
    permit: PublicApiOperationPermit;
    invalidatesNamespaces?: readonly PublicApiOperationNamespace[];
    inputFields: readonly string[];
    requiredInputFields: readonly string[];
    inputFieldTypes: Partial<Record<string, "array">>;
  }
>;
`,
    { filepath: generatedFile }
  )
);
