// This file was generated by pnpm mdn-data
export const experimentalProperties = {
  "anchor-name": "https://developer.mozilla.org/docs/Web/CSS/anchor-name",
  "anchor-scope": "https://developer.mozilla.org/en-US/search?q=anchor-scope",
  "animation-range-end":
    "https://developer.mozilla.org/docs/Web/CSS/animation-range-end",
  "animation-range-start":
    "https://developer.mozilla.org/docs/Web/CSS/animation-range-start",
  "animation-timeline":
    "https://developer.mozilla.org/docs/Web/CSS/animation-timeline",
  "field-sizing": "https://developer.mozilla.org/docs/Web/CSS/field-sizing",
  "font-synthesis-position":
    "https://developer.mozilla.org/docs/Web/CSS/font-synthesis-position",
  "font-width": "https://developer.mozilla.org/en-US/search?q=font-width",
  "image-resolution":
    "https://developer.mozilla.org/docs/Web/CSS/image-resolution",
  "initial-letter-align":
    "https://developer.mozilla.org/en-US/search?q=initial-letter-align",
  "interpolate-size":
    "https://developer.mozilla.org/docs/Web/CSS/interpolate-size",
  "line-height-step":
    "https://developer.mozilla.org/docs/Web/CSS/line-height-step",
  "link-parameters":
    "https://developer.mozilla.org/docs/Web/CSS/link-parameters",
  "margin-trim": "https://developer.mozilla.org/docs/Web/CSS/margin-trim",
  "math-shift": "https://developer.mozilla.org/docs/Web/CSS/math-shift",
  "max-lines": "https://developer.mozilla.org/en-US/search?q=max-lines",
  "object-view-box":
    "https://developer.mozilla.org/en-US/search?q=object-view-box",
  overlay: "https://developer.mozilla.org/docs/Web/CSS/overlay",
  "position-anchor":
    "https://developer.mozilla.org/docs/Web/CSS/position-anchor",
  "position-area": "https://developer.mozilla.org/docs/Web/CSS/position-area",
  "position-try-fallbacks":
    "https://developer.mozilla.org/docs/Web/CSS/position-try-fallbacks",
  "position-try-order":
    "https://developer.mozilla.org/docs/Web/CSS/position-try-order",
  "position-visibility":
    "https://developer.mozilla.org/docs/Web/CSS/position-visibility",
  "ruby-merge": "https://developer.mozilla.org/en-US/search?q=ruby-merge",
  "scroll-initial-target":
    "https://developer.mozilla.org/en-US/search?q=scroll-initial-target",
  "scroll-timeline-axis":
    "https://developer.mozilla.org/docs/Web/CSS/scroll-timeline-axis",
  "scroll-timeline-name":
    "https://developer.mozilla.org/docs/Web/CSS/scroll-timeline-name",
  "speak-as": "https://developer.mozilla.org/en-US/search?q=speak-as",
  "stroke-color": "https://developer.mozilla.org/en-US/search?q=stroke-color",
  "text-decoration-skip":
    "https://developer.mozilla.org/docs/Web/CSS/text-decoration-skip",
  "text-size-adjust":
    "https://developer.mozilla.org/docs/Web/CSS/text-size-adjust",
  "text-spacing-trim":
    "https://developer.mozilla.org/docs/Web/CSS/text-spacing-trim",
  "timeline-scope": "https://developer.mozilla.org/docs/Web/CSS/timeline-scope",
  "view-timeline-axis":
    "https://developer.mozilla.org/docs/Web/CSS/view-timeline-axis",
  "view-timeline-inset":
    "https://developer.mozilla.org/docs/Web/CSS/view-timeline-inset",
  "view-timeline-name":
    "https://developer.mozilla.org/docs/Web/CSS/view-timeline-name",
  "animation-range":
    "https://developer.mozilla.org/docs/Web/CSS/animation-range",
  "position-try": "https://developer.mozilla.org/docs/Web/CSS/position-try",
  "scroll-timeline":
    "https://developer.mozilla.org/docs/Web/CSS/scroll-timeline",
  "view-timeline": "https://developer.mozilla.org/docs/Web/CSS/view-timeline",
} as const;
