// This file was generated by pnpm mdn-data
export const properties = {
  accentColor: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.00030097,
    appliesTo: "allElements",
  },
  alignContent: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0.2430101,
    appliesTo: "multilineFlexContainers",
  },
  alignItems: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0.71654912,
    appliesTo: "flexContainersGridContainers",
  },
  alignSelf: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.43732689,
    appliesTo: "flexItemsGridItemsAndAbsolutelyPositionedBoxes",
  },
  alignTracks: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0,
    appliesTo: "gridContainersWithMasonryLayoutInTheirBlockAxis",
  },
  animationDelay: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.27086537,
    appliesTo: "allElementsAndPseudos",
  },
  animationDirection: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0.11739459,
    appliesTo: "allElementsAndPseudos",
  },
  animationDuration: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.4062731,
    appliesTo: "allElementsAndPseudos",
  },
  animationFillMode: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.2785038,
    appliesTo: "allElementsAndPseudos",
  },
  animationIterationCount: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 1,
    },
    popularity: 0.21759716,
    appliesTo: "allElementsAndPseudos",
  },
  animationName: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.40320939,
    appliesTo: "allElementsAndPseudos",
  },
  animationPlayState: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "running",
    },
    popularity: 0.07996997,
    appliesTo: "allElementsAndPseudos",
  },
  animationTimingFunction: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "ease",
    },
    popularity: 0.41317969,
    appliesTo: "allElementsAndPseudos",
  },
  appearance: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.24468974,
    appliesTo: "allElements",
  },
  aspectRatio: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.07243677,
    appliesTo: "allElementsExceptInlineBoxesAndInternalRubyOrTableBoxes",
  },
  backdropFilter: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.0728427,
    appliesTo: "allElementsSVGContainerElements",
  },
  backfaceVisibility: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "visible",
    },
    popularity: 0.19792557,
    appliesTo: "transformableElements",
  },
  backgroundAttachment: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "scroll",
    },
    popularity: 0.08164946,
    appliesTo: "allElements",
  },
  backgroundBlendMode: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0.01578865,
    appliesTo: "allElementsSVGContainerGraphicsAndGraphicsReferencingElements",
  },
  backgroundClip: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "border-box",
    },
    popularity: 0.36203159,
    appliesTo: "allElements",
  },
  backgroundColor: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "transparent",
    },
    popularity: 0.89693959,
    appliesTo: "allElements",
  },
  backgroundImage: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.78519153,
    appliesTo: "allElements",
  },
  backgroundOrigin: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "padding-box",
    },
    popularity: 0.0847006,
    appliesTo: "allElements",
  },
  backgroundPositionX: {
    inherited: false,
    initial: {
      type: "unit",
      value: 0,
      unit: "%",
    },
    popularity: 0.08951679,
    appliesTo: "allElements",
  },
  backgroundPositionY: {
    inherited: false,
    initial: {
      type: "unit",
      value: 0,
      unit: "%",
    },
    popularity: 0.06759137,
    appliesTo: "allElements",
  },
  backgroundRepeat: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "repeat",
    },
    popularity: 0.72870191,
    appliesTo: "allElements",
  },
  backgroundSize: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.73157126,
    appliesTo: "allElements",
  },
  blockOverflow: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "clip",
    },
    popularity: 0,
    appliesTo: "blockContainers",
  },
  blockSize: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.00226404,
    appliesTo: "sameAsWidthAndHeight",
  },
  borderBlockColor: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentcolor",
    },
    popularity: 0.00012849,
    appliesTo: "allElements",
  },
  borderBlockStyle: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.0003145,
    appliesTo: "allElements",
  },
  borderBlockWidth: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    popularity: 0.0003078,
    appliesTo: "allElements",
  },
  borderBlockEndColor: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentcolor",
    },
    popularity: 0.00172099,
    appliesTo: "allElements",
  },
  borderBlockEndStyle: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.00169793,
    appliesTo: "allElements",
  },
  borderBlockEndWidth: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    popularity: 0.00170225,
    appliesTo: "allElements",
  },
  borderBlockStartColor: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentcolor",
    },
    popularity: 0.00170188,
    appliesTo: "allElements",
  },
  borderBlockStartStyle: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.00168772,
    appliesTo: "allElements",
  },
  borderBlockStartWidth: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    popularity: 0.00169412,
    appliesTo: "allElements",
  },
  borderBottomColor: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentcolor",
    },
    popularity: 0.42283564,
    appliesTo: "allElements",
  },
  borderBottomLeftRadius: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.51220741,
    appliesTo: "allElementsUAsNotRequiredWhenCollapse",
  },
  borderBottomRightRadius: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.49744373,
    appliesTo: "allElementsUAsNotRequiredWhenCollapse",
  },
  borderBottomStyle: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.17956288,
    appliesTo: "allElements",
  },
  borderBottomWidth: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    popularity: 0.24668981,
    appliesTo: "allElements",
  },
  borderCollapse: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "separate",
    },
    popularity: 0.47856821,
    appliesTo: "tableElements",
  },
  borderEndEndRadius: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.00029065,
    appliesTo: "allElementsUAsNotRequiredWhenCollapse",
  },
  borderEndStartRadius: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.0003058,
    appliesTo: "allElementsUAsNotRequiredWhenCollapse",
  },
  borderImageOutset: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.00458637,
    appliesTo: "allElementsExceptTableElementsWhenCollapse",
  },
  borderImageRepeat: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "stretch",
    },
    popularity: 0.00685817,
    appliesTo: "allElementsExceptTableElementsWhenCollapse",
  },
  borderImageSlice: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 100,
    },
    popularity: 0.0093669,
    appliesTo: "allElementsExceptTableElementsWhenCollapse",
  },
  borderImageSource: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.00991835,
    appliesTo: "allElementsExceptTableElementsWhenCollapse",
  },
  borderImageWidth: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 1,
    },
    popularity: 0.0072772,
    appliesTo: "allElementsExceptTableElementsWhenCollapse",
  },
  borderInlineColor: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentcolor",
    },
    popularity: 0.00007844,
    appliesTo: "allElements",
  },
  borderInlineStyle: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.00031147,
    appliesTo: "allElements",
  },
  borderInlineWidth: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    popularity: 0.0002956,
    appliesTo: "allElements",
  },
  borderInlineEndColor: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentcolor",
    },
    popularity: 0.00196849,
    appliesTo: "allElements",
  },
  borderInlineEndStyle: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.00171907,
    appliesTo: "allElements",
  },
  borderInlineEndWidth: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    popularity: 0.0051498,
    appliesTo: "allElements",
  },
  borderInlineStartColor: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentcolor",
    },
    popularity: 0.00196928,
    appliesTo: "allElements",
  },
  borderInlineStartStyle: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.00177637,
    appliesTo: "allElements",
  },
  borderInlineStartWidth: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    popularity: 0.00438625,
    appliesTo: "allElements",
  },
  borderLeftColor: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentcolor",
    },
    popularity: 0.30754028,
    appliesTo: "allElements",
  },
  borderLeftStyle: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.06120178,
    appliesTo: "allElements",
  },
  borderLeftWidth: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    popularity: 0.17181793,
    appliesTo: "allElements",
  },
  borderRightColor: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentcolor",
    },
    popularity: 0.29336595,
    appliesTo: "allElements",
  },
  borderRightStyle: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.06714237,
    appliesTo: "allElements",
  },
  borderRightWidth: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    popularity: 0.17940634,
    appliesTo: "allElements",
  },
  borderSpacing: {
    inherited: true,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.37217618,
    appliesTo: "tableElements",
  },
  borderStartEndRadius: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.00029494,
    appliesTo: "allElementsUAsNotRequiredWhenCollapse",
  },
  borderStartStartRadius: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.00028405,
    appliesTo: "allElementsUAsNotRequiredWhenCollapse",
  },
  borderTopColor: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentcolor",
    },
    popularity: 0.43342948,
    appliesTo: "allElements",
  },
  borderTopLeftRadius: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.50859807,
    appliesTo: "allElementsUAsNotRequiredWhenCollapse",
  },
  borderTopRightRadius: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.50073217,
    appliesTo: "allElementsUAsNotRequiredWhenCollapse",
  },
  borderTopStyle: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.16269446,
    appliesTo: "allElements",
  },
  borderTopWidth: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    popularity: 0.21953437,
    appliesTo: "allElements",
  },
  bottom: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.8243869,
    appliesTo: "positionedElements",
  },
  boxDecorationBreak: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "slice",
    },
    popularity: 0,
    appliesTo: "allElements",
  },
  boxShadow: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.81259285,
    appliesTo: "allElements",
  },
  boxSizing: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "content-box",
    },
    popularity: 0.86402206,
    appliesTo: "allElementsAcceptingWidthOrHeight",
  },
  breakAfter: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.00365105,
    appliesTo: "blockLevelElements",
  },
  breakBefore: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.00341796,
    appliesTo: "blockLevelElements",
  },
  breakInside: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.02782348,
    appliesTo: "blockLevelElements",
  },
  captionSide: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "top",
    },
    popularity: 0.04083929,
    appliesTo: "tableCaptionElements",
  },
  caretColor: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.05410129,
    appliesTo: "allElements",
  },
  clear: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.7016813,
    appliesTo: "blockLevelElements",
  },
  clip: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.48810561,
    appliesTo: "absolutelyPositionedElements",
  },
  clipPath: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.20754263,
    appliesTo: "allElementsSVGContainerElements",
  },
  color: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "inherit",
    },
    popularity: 0.90791486,
    appliesTo: "allElements",
  },
  colorAdjust: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "economy",
    },
    popularity: 0,
    appliesTo: "allElements",
  },
  colorScheme: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0.03358925,
    appliesTo: "allElementsAndText",
  },
  columnCount: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.07098549,
    appliesTo: "blockContainersExceptTableWrappers",
  },
  columnFill: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "balance",
    },
    popularity: 0.01738207,
    appliesTo: "multicolElements",
  },
  columnGap: {
    inherited: false,
    initial: {
      type: "unit",
      value: 0,
      unit: "px",
    },
    popularity: 0.09282422,
    appliesTo: "multiColumnElementsFlexContainersGridContainers",
  },
  columnRuleColor: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentcolor",
    },
    popularity: 0.01356616,
    appliesTo: "multicolElements",
  },
  columnRuleStyle: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.0131392,
    appliesTo: "multicolElements",
  },
  columnRuleWidth: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    popularity: 0.00328701,
    appliesTo: "multicolElements",
  },
  columnSpan: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.00654278,
    appliesTo: "inFlowBlockLevelElements",
  },
  columnWidth: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.03188644,
    appliesTo: "blockContainersExceptTableWrappers",
  },
  contain: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.17189203,
    appliesTo: "allElements",
  },
  content: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0.81447258,
    appliesTo: "allElementsTreeAbidingPseudoElementsPageMarginBoxes",
  },
  contentVisibility: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "visible",
    },
    popularity: 0.04199404,
    appliesTo: "elementsForWhichLayoutContainmentCanApply",
  },
  counterIncrement: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.07472144,
    appliesTo: "allElements",
  },
  counterReset: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.06641074,
    appliesTo: "allElements",
  },
  counterSet: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.00016346,
    appliesTo: "allElements",
  },
  cursor: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.85037255,
    appliesTo: "allElements",
  },
  direction: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "ltr",
    },
    popularity: 0.40017516,
    appliesTo: "allElements",
  },
  display: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "inline",
    },
    popularity: 0.93157435,
    appliesTo: "allElements",
  },
  emptyCells: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "show",
    },
    popularity: 0.03153899,
    appliesTo: "tableCellElements",
  },
  filter: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.32058162,
    appliesTo: "allElementsSVGContainerElements",
  },
  flexBasis: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.3070072,
    appliesTo: "flexItemsAndInFlowPseudos",
  },
  flexDirection: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "row",
    },
    popularity: 0.65789154,
    appliesTo: "flexContainers",
  },
  flexGrow: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.50511311,
    appliesTo: "flexItemsAndInFlowPseudos",
  },
  flexShrink: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 1,
    },
    popularity: 0.4809155,
    appliesTo: "flexItemsAndInFlowPseudos",
  },
  flexWrap: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "nowrap",
    },
    popularity: 0.58959861,
    appliesTo: "flexContainers",
  },
  float: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.8383589,
    appliesTo: "allElementsNoEffectIfDisplayNone",
  },
  fontFamily: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "inherit",
    },
    popularity: 0.88101351,
    appliesTo: "allElements",
  },
  fontFeatureSettings: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0.12538368,
    appliesTo: "allElements",
  },
  fontKerning: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.01160796,
    appliesTo: "allElements",
  },
  fontLanguageOverride: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0,
    appliesTo: "allElements",
  },
  fontOpticalSizing: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.0006232,
    appliesTo: "allElements",
  },
  fontVariationSettings: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0.00471835,
    appliesTo: "allElements",
  },
  fontSize: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "inherit",
    },
    popularity: 0.90325346,
    appliesTo: "allElements",
  },
  fontSizeAdjust: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.000003,
    appliesTo: "allElements",
  },
  fontStretch: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0.12741738,
    appliesTo: "allElements",
  },
  fontStyle: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0.7961795,
    appliesTo: "allElements",
  },
  fontSynthesis: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "weight style",
    },
    popularity: 0.00686166,
    appliesTo: "allElements",
  },
  fontVariant: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0.30968418,
    appliesTo: "allElements",
  },
  fontVariantAlternates: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0,
    appliesTo: "allElements",
  },
  fontVariantCaps: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0.00514777,
    appliesTo: "allElements",
  },
  fontVariantEastAsian: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0.00328361,
    appliesTo: "allElements",
  },
  fontVariantLigatures: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0.05055055,
    appliesTo: "allElements",
  },
  fontVariantNumeric: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0.01816086,
    appliesTo: "allElements",
  },
  fontVariantPosition: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0,
    appliesTo: "allElements",
  },
  fontWeight: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0.88598106,
    appliesTo: "allElements",
  },
  forcedColorAdjust: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.02245871,
    appliesTo: "allElementsAndText",
  },
  gridAutoColumns: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.01226638,
    appliesTo: "gridContainers",
  },
  gridAutoFlow: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "row",
    },
    popularity: 0.03982344,
    appliesTo: "gridContainers",
  },
  gridAutoRows: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.02839547,
    appliesTo: "gridContainers",
  },
  gridColumnEnd: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.01848874,
    appliesTo: "gridItemsAndBoxesWithinGridContainer",
  },
  gridColumnStart: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.02019688,
    appliesTo: "gridItemsAndBoxesWithinGridContainer",
  },
  gridRowEnd: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.00961681,
    appliesTo: "gridItemsAndBoxesWithinGridContainer",
  },
  gridRowStart: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.01281513,
    appliesTo: "gridItemsAndBoxesWithinGridContainer",
  },
  gridTemplateAreas: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.05496001,
    appliesTo: "gridContainers",
  },
  gridTemplateColumns: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.17745181,
    appliesTo: "gridContainers",
  },
  gridTemplateRows: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.07489386,
    appliesTo: "gridContainers",
  },
  hangingPunctuation: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0,
    appliesTo: "allElements",
  },
  height: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.93056784,
    appliesTo: "allElementsButNonReplacedAndTableColumns",
  },
  hyphens: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "manual",
    },
    popularity: 0.10122444,
    appliesTo: "allElements",
  },
  imageOrientation: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "from-image",
    },
    popularity: 0.00207108,
    appliesTo: "allElements",
  },
  imageRendering: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.11112647,
    appliesTo: "allElements",
  },
  imageResolution: {
    inherited: true,
    initial: {
      type: "unit",
      unit: "px",
      value: 1,
    },
    popularity: 0,
    appliesTo: "allElements",
  },
  initialLetter: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0,
    appliesTo: "firstLetterPseudoElementsAndInlineLevelFirstChildren",
  },
  initialLetterAlign: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0,
    appliesTo: "firstLetterPseudoElementsAndInlineLevelFirstChildren",
  },
  inlineSize: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.00381706,
    appliesTo: "sameAsWidthAndHeight",
  },
  inset: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.02156551,
    appliesTo: "positionedElements",
  },
  insetBlock: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.00014881,
    appliesTo: "positionedElements",
  },
  insetBlockEnd: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.00031067,
    appliesTo: "positionedElements",
  },
  insetBlockStart: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.00036346,
    appliesTo: "positionedElements",
  },
  insetInline: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.00021379,
    appliesTo: "positionedElements",
  },
  insetInlineEnd: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.00419961,
    appliesTo: "positionedElements",
  },
  insetInlineStart: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.00379395,
    appliesTo: "positionedElements",
  },
  isolation: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.01962288,
    appliesTo: "allElementsSVGContainerGraphicsAndGraphicsReferencingElements",
  },
  justifyContent: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0.72371,
    appliesTo: "flexContainers",
  },
  justifyItems: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "legacy",
    },
    popularity: 0.05716411,
    appliesTo: "flexContainersGridContainers",
  },
  justifySelf: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.06147513,
    appliesTo: "blockLevelBoxesAndAbsolutelyPositionedBoxesAndGridItems",
  },
  justifyTracks: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0,
    appliesTo: "gridContainersWithMasonryLayoutInTheirInlineAxis",
  },
  left: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.90948372,
    appliesTo: "positionedElements",
  },
  letterSpacing: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0.64325492,
    appliesTo: "allElements",
  },
  lineBreak: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.03790035,
    appliesTo: "allElements",
  },
  lineClamp: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0,
    appliesTo: "blockContainersExceptMultiColumnContainers",
  },
  lineHeight: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "inherit",
    },
    popularity: 0.87354969,
    appliesTo: "allElements",
  },
  lineHeightStep: {
    inherited: true,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0,
    appliesTo: "blockContainers",
  },
  listStyleImage: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.05896406,
    appliesTo: "listItems",
  },
  listStylePosition: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "outside",
    },
    popularity: 0.10836703,
    appliesTo: "listItems",
  },
  listStyleType: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "disc",
    },
    popularity: 0.50305363,
    appliesTo: "listItems",
  },
  marginBlock: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.00120447,
    appliesTo: "sameAsMargin",
  },
  marginBlockEnd: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.06678285,
    appliesTo: "sameAsMargin",
  },
  marginBlockStart: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.06603158,
    appliesTo: "sameAsMargin",
  },
  marginBottom: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.84497162,
    appliesTo: "allElementsExceptTableDisplayTypes",
  },
  marginInline: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.00136801,
    appliesTo: "sameAsMargin",
  },
  marginInlineEnd: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.02346878,
    appliesTo: "sameAsMargin",
  },
  marginInlineStart: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.03660688,
    appliesTo: "sameAsMargin",
  },
  marginLeft: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.84846503,
    appliesTo: "allElementsExceptTableDisplayTypes",
  },
  marginRight: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.83485199,
    appliesTo: "allElementsExceptTableDisplayTypes",
  },
  marginTop: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.90536837,
    appliesTo: "allElementsExceptTableDisplayTypes",
  },
  marginTrim: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0,
    appliesTo: "blockContainersAndMultiColumnContainers",
  },
  maskBorderMode: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "alpha",
    },
    popularity: 0,
    appliesTo: "allElementsSVGContainerElements",
  },
  maskBorderOutset: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0,
    appliesTo: "allElementsSVGContainerElements",
  },
  maskBorderRepeat: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "stretch",
    },
    popularity: 0,
    appliesTo: "allElementsSVGContainerElements",
  },
  maskBorderSlice: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0,
    appliesTo: "allElementsSVGContainerElements",
  },
  maskBorderSource: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0,
    appliesTo: "allElementsSVGContainerElements",
  },
  maskBorderWidth: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0,
    appliesTo: "allElementsSVGContainerElements",
  },
  maskClip: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "border-box",
    },
    popularity: 0,
    appliesTo: "allElementsSVGContainerElements",
  },
  maskComposite: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "add",
    },
    popularity: 0,
    appliesTo: "allElementsSVGContainerElements",
  },
  maskImage: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0,
    appliesTo: "allElementsSVGContainerElements",
  },
  maskMode: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "match-source",
    },
    popularity: 0,
    appliesTo: "allElementsSVGContainerElements",
  },
  maskOrigin: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "border-box",
    },
    popularity: 0,
    appliesTo: "allElementsSVGContainerElements",
  },
  maskPosition: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "center",
    },
    popularity: 0,
    appliesTo: "allElementsSVGContainerElements",
  },
  maskRepeat: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "no-repeat",
    },
    popularity: 0,
    appliesTo: "allElementsSVGContainerElements",
  },
  maskSize: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0,
    appliesTo: "allElementsSVGContainerElements",
  },
  maskType: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "luminance",
    },
    popularity: 0.00355107,
    appliesTo: "maskElements",
  },
  masonryAutoFlow: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "pack",
    },
    popularity: 0,
    appliesTo: "gridContainersWithMasonryLayout",
  },
  mathStyle: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 3e-8,
    appliesTo: "allElements",
  },
  maxBlockSize: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.00064707,
    appliesTo: "sameAsWidthAndHeight",
  },
  maxHeight: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.72769912,
    appliesTo: "allElementsButNonReplacedAndTableColumns",
  },
  maxInlineSize: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.00062504,
    appliesTo: "sameAsWidthAndHeight",
  },
  maxLines: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0,
    appliesTo: "blockContainersExceptMultiColumnContainers",
  },
  maxWidth: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.83290711,
    appliesTo: "allElementsButNonReplacedAndTableRows",
  },
  minBlockSize: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.00192722,
    appliesTo: "sameAsWidthAndHeight",
  },
  minHeight: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.80088013,
    appliesTo: "allElementsButNonReplacedAndTableColumns",
  },
  minInlineSize: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.00357429,
    appliesTo: "sameAsWidthAndHeight",
  },
  minWidth: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.77790217,
    appliesTo: "allElementsButNonReplacedAndTableRows",
  },
  mixBlendMode: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0.05430564,
    appliesTo: "allElements",
  },
  objectFit: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "fill",
    },
    popularity: 0.38359477,
    appliesTo: "replacedElements",
  },
  objectPosition: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "50% 50%",
    },
    popularity: 0.08374319,
    appliesTo: "replacedElements",
  },
  offsetAnchor: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 6e-8,
    appliesTo: "transformableElements",
  },
  offsetDistance: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.0007637,
    appliesTo: "transformableElements",
  },
  offsetPath: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.0008741,
    appliesTo: "transformableElements",
  },
  offsetPosition: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 3e-8,
    appliesTo: "transformableElements",
  },
  offsetRotate: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.00073039,
    appliesTo: "transformableElements",
  },
  opacity: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 1,
    },
    popularity: 0.87714344,
    appliesTo: "allElements",
  },
  order: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.28274872,
    appliesTo: "flexItemsGridItemsAbsolutelyPositionedContainerChildren",
  },
  orphans: {
    inherited: true,
    initial: {
      type: "unit",
      unit: "px",
      value: 2,
    },
    popularity: 0.03717837,
    appliesTo: "blockContainerElements",
  },
  outlineColor: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "invertOrCurrentColor",
    },
    popularity: 0.09538741,
    appliesTo: "allElements",
  },
  outlineOffset: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.35495556,
    appliesTo: "allElements",
  },
  outlineStyle: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.22264732,
    appliesTo: "allElements",
  },
  outlineWidth: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    popularity: 0.23008945,
    appliesTo: "allElements",
  },
  overflow: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "visible",
    },
    popularity: 0.87464713,
    appliesTo: "blockContainersFlexContainersGridContainers",
  },
  overflowAnchor: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.05039229,
    appliesTo: "allElements",
  },
  overflowBlock: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0,
    appliesTo: "blockContainersFlexContainersGridContainers",
  },
  overflowClipMargin: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.0001932,
    appliesTo: "allElements",
  },
  overflowInline: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0,
    appliesTo: "blockContainersFlexContainersGridContainers",
  },
  overflowWrap: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0.2917187,
    appliesTo: "nonReplacedInlineElements",
  },
  overflowX: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "visible",
    },
    popularity: 0.6419296,
    appliesTo: "blockContainersFlexContainersGridContainers",
  },
  overflowY: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "visible",
    },
    popularity: 0.66040666,
    appliesTo: "blockContainersFlexContainersGridContainers",
  },
  overscrollBehavior: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0,
    appliesTo: "nonReplacedBlockAndInlineBlockElements",
  },
  overscrollBehaviorBlock: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.0002038,
    appliesTo: "nonReplacedBlockAndInlineBlockElements",
  },
  overscrollBehaviorInline: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.0003654,
    appliesTo: "nonReplacedBlockAndInlineBlockElements",
  },
  overscrollBehaviorX: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0,
    appliesTo: "nonReplacedBlockAndInlineBlockElements",
  },
  overscrollBehaviorY: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0,
    appliesTo: "nonReplacedBlockAndInlineBlockElements",
  },
  paddingBlock: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.00094479,
    appliesTo: "allElements",
  },
  paddingBlockEnd: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.00269343,
    appliesTo: "allElements",
  },
  paddingBlockStart: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.00281718,
    appliesTo: "allElements",
  },
  paddingBottom: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.80249482,
    appliesTo: "allElementsExceptInternalTableDisplayTypes",
  },
  paddingInline: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.01735028,
    appliesTo: "allElements",
  },
  paddingInlineEnd: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.02914235,
    appliesTo: "allElements",
  },
  paddingInlineStart: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.03734959,
    appliesTo: "allElements",
  },
  paddingLeft: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.81912414,
    appliesTo: "allElementsExceptInternalTableDisplayTypes",
  },
  paddingRight: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.80336339,
    appliesTo: "allElementsExceptInternalTableDisplayTypes",
  },
  paddingTop: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.82360295,
    appliesTo: "allElementsExceptInternalTableDisplayTypes",
  },
  pageBreakAfter: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.04793594,
    appliesTo: "blockElementsInNormalFlow",
  },
  pageBreakBefore: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.0173306,
    appliesTo: "blockElementsInNormalFlow",
  },
  pageBreakInside: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.0636772,
    appliesTo: "blockElementsInNormalFlow",
  },
  paintOrder: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0.0013931,
    appliesTo: "textElements",
  },
  perspective: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.11208199,
    appliesTo: "transformableElements",
  },
  perspectiveOrigin: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "50% 50%",
    },
    popularity: 0.03597136,
    appliesTo: "transformableElements",
  },
  placeContent: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0.00389319,
    appliesTo: "multilineFlexContainers",
  },
  pointerEvents: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.65656971,
    appliesTo: "allElements",
  },
  position: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "static",
    },
    popularity: 0.92435004,
    appliesTo: "allElements",
  },
  quotes: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "dependsOnUserAgent",
    },
    popularity: 0.08095164,
    appliesTo: "allElements",
  },
  resize: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.20814477,
    appliesTo: "elementsWithOverflowNotVisibleAndReplacedElements",
  },
  right: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.83840245,
    appliesTo: "positionedElements",
  },
  rotate: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 4e-8,
    appliesTo: "transformableElements",
  },
  rowGap: {
    inherited: false,
    initial: {
      type: "unit",
      value: 0,
      unit: "px",
    },
    popularity: 0.01955862,
    appliesTo: "multiColumnElementsFlexContainersGridContainers",
  },
  rubyAlign: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "space-around",
    },
    popularity: 0,
    appliesTo: "rubyBasesAnnotationsBaseAnnotationContainers",
  },
  rubyMerge: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "separate",
    },
    popularity: 0,
    appliesTo: "rubyAnnotationsContainers",
  },
  rubyPosition: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "alternate",
    },
    popularity: 0.00156034,
    appliesTo: "rubyAnnotationsContainers",
  },
  scale: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 2e-7,
    appliesTo: "transformableElements",
  },
  scrollbarColor: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0,
    appliesTo: "scrollingBoxes",
  },
  scrollbarGutter: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.00128847,
    appliesTo: "scrollingBoxes",
  },
  scrollbarWidth: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.000001,
    appliesTo: "scrollingBoxes",
  },
  scrollBehavior: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.06855196,
    appliesTo: "scrollingBoxes",
  },
  scrollMargin: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0,
    appliesTo: "allElements",
  },
  scrollMarginBlock: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0,
    appliesTo: "allElements",
  },
  scrollMarginBlockStart: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0,
    appliesTo: "allElements",
  },
  scrollMarginBlockEnd: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0,
    appliesTo: "allElements",
  },
  scrollMarginBottom: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0,
    appliesTo: "allElements",
  },
  scrollMarginInline: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0,
    appliesTo: "allElements",
  },
  scrollMarginInlineStart: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0,
    appliesTo: "allElements",
  },
  scrollMarginInlineEnd: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0,
    appliesTo: "allElements",
  },
  scrollMarginLeft: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0,
    appliesTo: "allElements",
  },
  scrollMarginRight: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0,
    appliesTo: "allElements",
  },
  scrollMarginTop: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0,
    appliesTo: "allElements",
  },
  scrollPadding: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.00684182,
    appliesTo: "scrollContainers",
  },
  scrollPaddingBlock: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.00011157,
    appliesTo: "scrollContainers",
  },
  scrollPaddingBlockStart: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.0003318,
    appliesTo: "scrollContainers",
  },
  scrollPaddingBlockEnd: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.00033098,
    appliesTo: "scrollContainers",
  },
  scrollPaddingBottom: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.00046042,
    appliesTo: "scrollContainers",
  },
  scrollPaddingInline: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.00030929,
    appliesTo: "scrollContainers",
  },
  scrollPaddingInlineStart: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.00034054,
    appliesTo: "scrollContainers",
  },
  scrollPaddingInlineEnd: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.00033178,
    appliesTo: "scrollContainers",
  },
  scrollPaddingLeft: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.00318274,
    appliesTo: "scrollContainers",
  },
  scrollPaddingRight: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.00046376,
    appliesTo: "scrollContainers",
  },
  scrollPaddingTop: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.0199363,
    appliesTo: "scrollContainers",
  },
  scrollSnapAlign: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.05990673,
    appliesTo: "allElements",
  },
  scrollSnapStop: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0.0074871,
    appliesTo: "allElements",
  },
  scrollSnapType: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.05778112,
    appliesTo: "allElements",
  },
  shapeImageThreshold: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.00579108,
    appliesTo: "floats",
  },
  shapeMargin: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.00212267,
    appliesTo: "floats",
  },
  shapeOutside: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.00236383,
    appliesTo: "floats",
  },
  tabSize: {
    inherited: true,
    initial: {
      type: "unit",
      unit: "px",
      value: 8,
    },
    popularity: 0.03065152,
    appliesTo: "blockContainers",
  },
  tableLayout: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.20669832,
    appliesTo: "tableElements",
  },
  textAlign: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "startOrNamelessValueIfLTRRightIfRTL",
    },
    popularity: 0.89287477,
    appliesTo: "blockContainers",
  },
  textAlignLast: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.02339794,
    appliesTo: "blockContainers",
  },
  textCombineUpright: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.00187072,
    appliesTo: "nonReplacedInlineElements",
  },
  textDecorationColor: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentcolor",
    },
    popularity: 0.05079903,
    appliesTo: "allElements",
  },
  textDecorationLine: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.03656271,
    appliesTo: "allElements",
  },
  textDecorationSkip: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "objects",
    },
    popularity: 0.054238,
    appliesTo: "allElements",
  },
  textDecorationSkipInk: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.01645826,
    appliesTo: "allElements",
  },
  textDecorationStyle: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "solid",
    },
    popularity: 0.02111189,
    appliesTo: "allElements",
  },
  textDecorationThickness: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.00728976,
    appliesTo: "allElements",
  },
  textEmphasisColor: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentcolor",
    },
    popularity: 0,
    appliesTo: "allElements",
  },
  textEmphasisPosition: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "over right",
    },
    popularity: 0,
    appliesTo: "allElements",
  },
  textEmphasisStyle: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0,
    appliesTo: "allElements",
  },
  textIndent: {
    inherited: true,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.37633903,
    appliesTo: "blockContainers",
  },
  textJustify: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 8e-7,
    appliesTo: "inlineLevelAndTableCellElements",
  },
  textOrientation: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "mixed",
    },
    popularity: 0.00286298,
    appliesTo: "allElementsExceptTableRowGroupsRowsColumnGroupsAndColumns",
  },
  textOverflow: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "clip",
    },
    popularity: 0.65272517,
    appliesTo: "blockContainerElements",
  },
  textRendering: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.3619822,
    appliesTo: "textElements",
  },
  textShadow: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.49899917,
    appliesTo: "allElements",
  },
  textSizeAdjust: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.13611964,
    appliesTo: "allElements",
  },
  textTransform: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.73056963,
    appliesTo: "allElements",
  },
  textUnderlineOffset: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.00558599,
    appliesTo: "allElements",
  },
  textUnderlinePosition: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.0070495,
    appliesTo: "allElements",
  },
  top: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.91426675,
    appliesTo: "positionedElements",
  },
  touchAction: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.37581741,
    appliesTo:
      "allElementsExceptNonReplacedInlineElementsTableRowsColumnsRowColumnGroups",
  },
  transform: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 0.82452786,
    appliesTo: "transformableElements",
  },
  transformBox: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "view-box",
    },
    popularity: 0.00167776,
    appliesTo: "transformableElements",
  },
  transformOrigin: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "50% 50% 0",
    },
    popularity: 0.54179205,
    appliesTo: "transformableElements",
  },
  transformStyle: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "flat",
    },
    popularity: 0.11068509,
    appliesTo: "transformableElements",
  },
  transitionDelay: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.26633596,
    appliesTo: "allElementsAndPseudos",
  },
  transitionDuration: {
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    popularity: 0.27645681,
    appliesTo: "allElementsAndPseudos",
  },
  transitionProperty: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "all",
    },
    popularity: 0.28626935,
    appliesTo: "allElementsAndPseudos",
  },
  transitionTimingFunction: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "ease",
    },
    popularity: 0.28535681,
    appliesTo: "allElementsAndPseudos",
  },
  translate: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    popularity: 9e-8,
    appliesTo: "transformableElements",
  },
  unicodeBidi: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0.13633243,
    appliesTo: "allElementsSomeValuesNoEffectOnNonInlineElements",
  },
  userSelect: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.55451382,
    appliesTo: "allElements",
  },
  verticalAlign: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "baseline",
    },
    popularity: 0.84531302,
    appliesTo: "inlineLevelAndTableCellElements",
  },
  visibility: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "visible",
    },
    popularity: 0.76715746,
    appliesTo: "allElements",
  },
  whiteSpace: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0.80711821,
    appliesTo: "allElements",
  },
  widows: {
    inherited: true,
    initial: {
      type: "unit",
      unit: "px",
      value: 2,
    },
    popularity: 0.03635817,
    appliesTo: "blockContainerElements",
  },
  width: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.93671487,
    appliesTo: "allElementsButNonReplacedAndTableRows",
  },
  willChange: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.28251419,
    appliesTo: "allElements",
  },
  wordBreak: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0.51074263,
    appliesTo: "allElements",
  },
  wordSpacing: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0.15650671,
    appliesTo: "allElements",
  },
  wordWrap: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    popularity: 0.55291577,
    appliesTo: "nonReplacedInlineElements",
  },
  writingMode: {
    inherited: true,
    initial: {
      type: "keyword",
      value: "horizontal-tb",
    },
    popularity: 0.00947773,
    appliesTo: "allElementsExceptTableRowColumnGroupsTableRowsColumns",
  },
  zIndex: {
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    popularity: 0.85875694,
    appliesTo: "positionedElements",
  },
} as const;
