// This file was generated by pnpm mdn-data

import type {
  __HyphenatedProperty,
  StyleValue,
} from "@webstudio-is/css-engine";
type UnitGroup =
  | "number"
  | "percentage"
  | "angle"
  | "decibel"
  | "flex"
  | "frequency"
  | "length"
  | "resolution"
  | "semitones"
  | "time";
type PropertyData = {
  unitGroups: UnitGroup[];
  inherited: boolean;
  initial: StyleValue;
  mdnUrl?: string;
};
type Properties = Record<__HyphenatedProperty, PropertyData> &
  Record<`--${string}`, undefined>;
export const properties: Properties = {
  "-webkit-font-smoothing": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth",
  },
  "-moz-osx-font-smoothing": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth",
  },
  "-webkit-box-orient": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "horizontal",
    },
    mdnUrl: "https://developer.mozilla.org/en-US/docs/Web/CSS/box-orient",
  },
  "view-timeline-name": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl:
      "https://developer.mozilla.org/en-US/docs/Web/CSS/view-timeline-name",
  },
  "scroll-timeline-name": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl:
      "https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-timeline-name",
  },
  "view-timeline-inset": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl:
      "https://developer.mozilla.org/en-US/docs/Web/CSS/view-timeline-inset",
  },
  "-webkit-line-clamp": {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/-webkit-line-clamp",
  },
  "-webkit-overflow-scrolling": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/-webkit-overflow-scrolling",
  },
  "-webkit-tap-highlight-color": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "black",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/-webkit-tap-highlight-color",
  },
  "accent-color": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/accent-color",
  },
  "align-content": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/align-content",
  },
  "align-items": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/align-items",
  },
  "align-self": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/align-self",
  },
  "animation-delay": {
    unitGroups: ["time"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "s",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/animation-delay",
  },
  "animation-direction": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/animation-direction",
  },
  "animation-duration": {
    unitGroups: ["time"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "s",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/animation-duration",
  },
  "animation-fill-mode": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/animation-fill-mode",
  },
  "animation-iteration-count": {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "number",
      value: 1,
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/animation-iteration-count",
  },
  "animation-name": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/animation-name",
  },
  "animation-play-state": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "running",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/animation-play-state",
  },
  "animation-timing-function": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "ease",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/animation-timing-function",
  },
  appearance: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/appearance",
  },
  "aspect-ratio": {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/aspect-ratio",
  },
  "backdrop-filter": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/backdrop-filter",
  },
  "backface-visibility": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "visible",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/backface-visibility",
  },
  "background-attachment": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "scroll",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/background-attachment",
  },
  "background-blend-mode": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/background-blend-mode",
  },
  "background-clip": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "border-box",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/background-clip",
  },
  "background-color": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "transparent",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/background-color",
  },
  "background-image": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/background-image",
  },
  "background-origin": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "padding-box",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/background-origin",
  },
  "background-position-x": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "%",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/background-position-x",
  },
  "background-position-y": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "%",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/background-position-y",
  },
  "background-repeat": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "repeat",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/background-repeat",
  },
  "background-size": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/background-size",
  },
  "block-size": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/block-size",
  },
  "border-block-color": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentColor",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-block-color",
  },
  "border-block-style": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-block-style",
  },
  "border-block-width": {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-block-width",
  },
  "border-block-end-color": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentColor",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-block-end-color",
  },
  "border-block-end-style": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-block-end-style",
  },
  "border-block-end-width": {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-block-end-width",
  },
  "border-block-start-color": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentColor",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/border-block-start-color",
  },
  "border-block-start-style": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/border-block-start-style",
  },
  "border-block-start-width": {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/border-block-start-width",
  },
  "border-bottom-color": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentColor",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-bottom-color",
  },
  "border-bottom-left-radius": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/border-bottom-left-radius",
  },
  "border-bottom-right-radius": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/border-bottom-right-radius",
  },
  "border-bottom-style": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-bottom-style",
  },
  "border-bottom-width": {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-bottom-width",
  },
  "border-collapse": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "separate",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-collapse",
  },
  "border-end-end-radius": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-end-end-radius",
  },
  "border-end-start-radius": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/border-end-start-radius",
  },
  "border-image-outset": {
    unitGroups: ["length", "number"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "number",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-image-outset",
  },
  "border-image-repeat": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "stretch",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-image-repeat",
  },
  "border-image-slice": {
    unitGroups: ["number", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "%",
      value: 100,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-image-slice",
  },
  "border-image-source": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-image-source",
  },
  "border-image-width": {
    unitGroups: ["length", "percentage", "number"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "number",
      value: 1,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-image-width",
  },
  "border-inline-color": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentColor",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-inline-color",
  },
  "border-inline-style": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-inline-style",
  },
  "border-inline-width": {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-inline-width",
  },
  "border-inline-end-color": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentColor",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/border-inline-end-color",
  },
  "border-inline-end-style": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/border-inline-end-style",
  },
  "border-inline-end-width": {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/border-inline-end-width",
  },
  "border-inline-start-color": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentColor",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/border-inline-start-color",
  },
  "border-inline-start-style": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/border-inline-start-style",
  },
  "border-inline-start-width": {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/border-inline-start-width",
  },
  "border-left-color": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentColor",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-left-color",
  },
  "border-left-style": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-left-style",
  },
  "border-left-width": {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-left-width",
  },
  "border-right-color": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentColor",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-right-color",
  },
  "border-right-style": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-right-style",
  },
  "border-right-width": {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-right-width",
  },
  "border-spacing": {
    unitGroups: ["length"],
    inherited: true,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-spacing",
  },
  "border-start-end-radius": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/border-start-end-radius",
  },
  "border-start-start-radius": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/border-start-start-radius",
  },
  "border-top-color": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentColor",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-top-color",
  },
  "border-top-left-radius": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-top-left-radius",
  },
  "border-top-right-radius": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/border-top-right-radius",
  },
  "border-top-style": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-top-style",
  },
  "border-top-width": {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/border-top-width",
  },
  bottom: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/bottom",
  },
  "box-decoration-break": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "slice",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/box-decoration-break",
  },
  "box-shadow": {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/box-shadow",
  },
  "box-sizing": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "content-box",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/box-sizing",
  },
  "break-after": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/break-after",
  },
  "break-before": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/break-before",
  },
  "break-inside": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/break-inside",
  },
  "caption-side": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "top",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/caption-side",
  },
  "caret-color": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/caret-color",
  },
  clear: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/clear",
  },
  clip: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/clip",
  },
  "clip-path": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/clip-path",
  },
  color: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "black",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/color",
  },
  "color-scheme": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/color-scheme",
  },
  "column-count": {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/column-count",
  },
  "column-fill": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "balance",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/column-fill",
  },
  "column-gap": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      value: 0,
      unit: "px",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/column-gap",
  },
  "column-rule-color": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentColor",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/column-rule-color",
  },
  "column-rule-style": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/column-rule-style",
  },
  "column-rule-width": {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/column-rule-width",
  },
  "column-span": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/column-span",
  },
  "column-width": {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/column-width",
  },
  contain: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/contain",
  },
  "contain-intrinsic-block-size": {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/contain-intrinsic-block-size",
  },
  "contain-intrinsic-height": {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/contain-intrinsic-height",
  },
  "contain-intrinsic-inline-size": {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/contain-intrinsic-inline-size",
  },
  "contain-intrinsic-width": {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/contain-intrinsic-width",
  },
  "container-name": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/container-name",
  },
  "container-type": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/container-type",
  },
  content: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/content",
  },
  "content-visibility": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "visible",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/content-visibility",
  },
  "counter-increment": {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/counter-increment",
  },
  "counter-reset": {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/counter-reset",
  },
  "counter-set": {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/counter-set",
  },
  cursor: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/cursor",
  },
  direction: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "ltr",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/direction",
  },
  display: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "inline",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/display",
  },
  "empty-cells": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "show",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/empty-cells",
  },
  "field-sizing": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "fixed",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/field-sizing",
  },
  filter: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/filter",
  },
  "flex-basis": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/flex-basis",
  },
  "flex-direction": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "row",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/flex-direction",
  },
  "flex-grow": {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "number",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/flex-grow",
  },
  "flex-shrink": {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "number",
      value: 1,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/flex-shrink",
  },
  "flex-wrap": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "nowrap",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/flex-wrap",
  },
  float: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/float",
  },
  "font-family": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "fontFamily",
      value: ["serif"],
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/font-family",
  },
  "font-feature-settings": {
    unitGroups: ["number"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/font-feature-settings",
  },
  "font-kerning": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/font-kerning",
  },
  "font-language-override": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/font-language-override",
  },
  "font-optical-sizing": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/font-optical-sizing",
  },
  "font-variation-settings": {
    unitGroups: ["number"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/font-variation-settings",
  },
  "font-size": {
    unitGroups: ["length", "percentage"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "medium",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/font-size",
  },
  "font-size-adjust": {
    unitGroups: ["number"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/font-size-adjust",
  },
  "font-stretch": {
    unitGroups: ["percentage"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/font-stretch",
  },
  "font-style": {
    unitGroups: ["angle"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/font-style",
  },
  "font-synthesis-small-caps": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/font-synthesis-small-caps",
  },
  "font-synthesis-style": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/font-synthesis-style",
  },
  "font-synthesis-weight": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/font-synthesis-weight",
  },
  "font-variant-alternates": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/font-variant-alternates",
  },
  "font-variant-caps": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/font-variant-caps",
  },
  "font-variant-east-asian": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/font-variant-east-asian",
  },
  "font-variant-ligatures": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/font-variant-ligatures",
  },
  "font-variant-numeric": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/font-variant-numeric",
  },
  "font-variant-position": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/font-variant-position",
  },
  "font-weight": {
    unitGroups: ["number"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/font-weight",
  },
  "grid-auto-columns": {
    unitGroups: ["length", "percentage", "flex"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/grid-auto-columns",
  },
  "grid-auto-flow": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "row",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/grid-auto-flow",
  },
  "grid-auto-rows": {
    unitGroups: ["length", "percentage", "flex"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/grid-auto-rows",
  },
  "grid-column-end": {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/grid-column-end",
  },
  "grid-column-start": {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/grid-column-start",
  },
  "grid-row-end": {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/grid-row-end",
  },
  "grid-row-start": {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/grid-row-start",
  },
  "grid-template-areas": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/grid-template-areas",
  },
  "grid-template-columns": {
    unitGroups: ["length", "percentage", "flex"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/grid-template-columns",
  },
  "grid-template-rows": {
    unitGroups: ["length", "percentage", "flex"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/grid-template-rows",
  },
  "hanging-punctuation": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/hanging-punctuation",
  },
  height: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/height",
  },
  "hyphenate-character": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/hyphenate-character",
  },
  "hyphenate-limit-chars": {
    unitGroups: ["number"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/hyphenate-limit-chars",
  },
  hyphens: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "manual",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/hyphens",
  },
  "image-orientation": {
    unitGroups: ["angle"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "from-image",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/image-orientation",
  },
  "image-rendering": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/image-rendering",
  },
  "inline-size": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/inline-size",
  },
  "inset-block-end": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/inset-block-end",
  },
  "inset-block-start": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/inset-block-start",
  },
  "inset-inline-end": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/inset-inline-end",
  },
  "inset-inline-start": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/inset-inline-start",
  },
  isolation: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/isolation",
  },
  "justify-content": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/justify-content",
  },
  "justify-items": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "legacy",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/justify-items",
  },
  "justify-self": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/justify-self",
  },
  left: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/left",
  },
  "letter-spacing": {
    unitGroups: ["length"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/letter-spacing",
  },
  "line-break": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/line-break",
  },
  "line-height": {
    unitGroups: ["number", "length", "percentage"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/line-height",
  },
  "list-style-image": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/list-style-image",
  },
  "list-style-position": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "outside",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/list-style-position",
  },
  "list-style-type": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "disc",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/list-style-type",
  },
  "margin-block-end": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/margin-block-end",
  },
  "margin-block-start": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/margin-block-start",
  },
  "margin-bottom": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/margin-bottom",
  },
  "margin-inline-end": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/margin-inline-end",
  },
  "margin-inline-start": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/margin-inline-start",
  },
  "margin-left": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/margin-left",
  },
  "margin-right": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/margin-right",
  },
  "margin-top": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/margin-top",
  },
  "mask-border-mode": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "alpha",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/mask-border-mode",
  },
  "mask-border-outset": {
    unitGroups: ["length", "number"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "number",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/mask-border-outset",
  },
  "mask-border-repeat": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "stretch",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/mask-border-repeat",
  },
  "mask-border-slice": {
    unitGroups: ["number", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "number",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/mask-border-slice",
  },
  "mask-border-source": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/mask-border-source",
  },
  "mask-border-width": {
    unitGroups: ["length", "percentage", "number"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/mask-border-width",
  },
  "mask-clip": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "border-box",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/mask-clip",
  },
  "mask-composite": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "add",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/mask-composite",
  },
  "mask-image": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/mask-image",
  },
  "mask-mode": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "match-source",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/mask-mode",
  },
  "mask-origin": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "border-box",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/mask-origin",
  },
  "mask-position": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "tuple",
      value: [
        {
          type: "unit",
          unit: "%",
          value: 0,
        },
        {
          type: "unit",
          unit: "%",
          value: 0,
        },
      ],
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/mask-position",
  },
  "mask-repeat": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "repeat",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/mask-repeat",
  },
  "mask-size": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/mask-size",
  },
  "mask-type": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "luminance",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/mask-type",
  },
  "math-depth": {
    unitGroups: ["number"],
    inherited: true,
    initial: {
      type: "unit",
      unit: "number",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/math-depth",
  },
  "math-shift": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/math-shift",
  },
  "math-style": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/math-style",
  },
  "max-block-size": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/max-block-size",
  },
  "max-height": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/max-height",
  },
  "max-inline-size": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/max-inline-size",
  },
  "max-width": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/max-width",
  },
  "min-block-size": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/min-block-size",
  },
  "min-height": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/min-height",
  },
  "min-inline-size": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/min-inline-size",
  },
  "min-width": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/min-width",
  },
  "mix-blend-mode": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/mix-blend-mode",
  },
  "object-fit": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "fill",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/object-fit",
  },
  "object-position": {
    unitGroups: ["length", "percentage"],
    inherited: true,
    initial: {
      type: "tuple",
      value: [
        {
          type: "unit",
          unit: "%",
          value: 50,
        },
        {
          type: "unit",
          unit: "%",
          value: 50,
        },
      ],
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/object-position",
  },
  "offset-anchor": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
  },
  "offset-distance": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/offset-distance",
  },
  "offset-path": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/offset-path",
  },
  "offset-position": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
  },
  "offset-rotate": {
    unitGroups: ["angle"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/offset-rotate",
  },
  opacity: {
    unitGroups: ["number", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "number",
      value: 1,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/opacity",
  },
  order: {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "number",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/order",
  },
  orphans: {
    unitGroups: ["number"],
    inherited: true,
    initial: {
      type: "unit",
      unit: "number",
      value: 2,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/orphans",
  },
  "outline-color": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/outline-color",
  },
  "outline-offset": {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/outline-offset",
  },
  "outline-style": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/outline-style",
  },
  "outline-width": {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/outline-width",
  },
  "overflow-wrap": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/overflow-wrap",
  },
  "overflow-x": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "visible",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/overflow-x",
  },
  "overflow-y": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "visible",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/overflow-y",
  },
  "overscroll-behavior": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/overscroll-behavior",
  },
  "overscroll-behavior-block": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/overscroll-behavior-block",
  },
  "overscroll-behavior-inline": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/overscroll-behavior-inline",
  },
  "overscroll-behavior-x": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/overscroll-behavior-x",
  },
  "overscroll-behavior-y": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/overscroll-behavior-y",
  },
  "padding-block-end": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/padding-block-end",
  },
  "padding-block-start": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/padding-block-start",
  },
  "padding-bottom": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/padding-bottom",
  },
  "padding-inline-end": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/padding-inline-end",
  },
  "padding-inline-start": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/padding-inline-start",
  },
  "padding-left": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/padding-left",
  },
  "padding-right": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/padding-right",
  },
  "padding-top": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/padding-top",
  },
  page: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/page",
  },
  "page-break-after": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/page-break-after",
  },
  "page-break-before": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/page-break-before",
  },
  "page-break-inside": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/page-break-inside",
  },
  "paint-order": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/paint-order",
  },
  perspective: {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/perspective",
  },
  "perspective-origin": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "tuple",
      value: [
        {
          type: "unit",
          unit: "%",
          value: 50,
        },
        {
          type: "unit",
          unit: "%",
          value: 50,
        },
      ],
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/perspective-origin",
  },
  "pointer-events": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/pointer-events",
  },
  position: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "static",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/position",
  },
  "print-color-adjust": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "economy",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/print-color-adjust",
  },
  quotes: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "dependsOnUserAgent",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/quotes",
  },
  resize: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/resize",
  },
  right: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/right",
  },
  rotate: {
    unitGroups: ["angle", "number"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/rotate",
  },
  "row-gap": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      value: 0,
      unit: "px",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/row-gap",
  },
  scale: {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/scale",
  },
  "scrollbar-color": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/scrollbar-color",
  },
  "scrollbar-gutter": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/scrollbar-gutter",
  },
  "scrollbar-width": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/scrollbar-width",
  },
  "scroll-behavior": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/scroll-behavior",
  },
  "scroll-margin-block-start": {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/scroll-margin-block-start",
  },
  "scroll-margin-block-end": {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/scroll-margin-block-end",
  },
  "scroll-margin-bottom": {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/scroll-margin-bottom",
  },
  "scroll-margin-inline-start": {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/scroll-margin-inline-start",
  },
  "scroll-margin-inline-end": {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/scroll-margin-inline-end",
  },
  "scroll-margin-left": {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/scroll-margin-left",
  },
  "scroll-margin-right": {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/scroll-margin-right",
  },
  "scroll-margin-top": {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/scroll-margin-top",
  },
  "scroll-padding-block-start": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/scroll-padding-block-start",
  },
  "scroll-padding-block-end": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/scroll-padding-block-end",
  },
  "scroll-padding-bottom": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/scroll-padding-bottom",
  },
  "scroll-padding-inline-start": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/scroll-padding-inline-start",
  },
  "scroll-padding-inline-end": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/scroll-padding-inline-end",
  },
  "scroll-padding-left": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/scroll-padding-left",
  },
  "scroll-padding-right": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/scroll-padding-right",
  },
  "scroll-padding-top": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/scroll-padding-top",
  },
  "scroll-snap-align": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/scroll-snap-align",
  },
  "scroll-snap-stop": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/scroll-snap-stop",
  },
  "scroll-snap-type": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/scroll-snap-type",
  },
  "shape-image-threshold": {
    unitGroups: ["number", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "number",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/shape-image-threshold",
  },
  "shape-margin": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/shape-margin",
  },
  "shape-outside": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/shape-outside",
  },
  "tab-size": {
    unitGroups: ["number", "length"],
    inherited: true,
    initial: {
      type: "unit",
      unit: "number",
      value: 8,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/tab-size",
  },
  "table-layout": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/table-layout",
  },
  "text-align": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "start",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/text-align",
  },
  "text-align-last": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/text-align-last",
  },
  "text-combine-upright": {
    unitGroups: ["number"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/text-combine-upright",
  },
  "text-decoration-color": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentColor",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/text-decoration-color",
  },
  "text-decoration-line": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/text-decoration-line",
  },
  "text-decoration-skip-ink": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/text-decoration-skip-ink",
  },
  "text-decoration-style": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "solid",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/text-decoration-style",
  },
  "text-decoration-thickness": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/text-decoration-thickness",
  },
  "text-emphasis-color": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "currentColor",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/text-emphasis-color",
  },
  "text-emphasis-position": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "tuple",
      value: [
        {
          type: "keyword",
          value: "over",
        },
        {
          type: "keyword",
          value: "right",
        },
      ],
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/text-emphasis-position",
  },
  "text-emphasis-style": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/text-emphasis-style",
  },
  "text-indent": {
    unitGroups: ["length", "percentage"],
    inherited: true,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/text-indent",
  },
  "text-justify": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/text-justify",
  },
  "text-orientation": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "mixed",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/text-orientation",
  },
  "text-overflow": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "clip",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/text-overflow",
  },
  "text-rendering": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/text-rendering",
  },
  "text-shadow": {
    unitGroups: ["length"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/text-shadow",
  },
  "text-size-adjust": {
    unitGroups: ["percentage"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/text-size-adjust",
  },
  "text-transform": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/text-transform",
  },
  "text-underline-offset": {
    unitGroups: ["length", "percentage"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/text-underline-offset",
  },
  "text-underline-position": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/text-underline-position",
  },
  "text-wrap-mode": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "wrap",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/text-wrap-mode",
  },
  "text-wrap-style": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/text-wrap-style",
  },
  top: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/top",
  },
  "touch-action": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/touch-action",
  },
  transform: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/transform",
  },
  "transform-box": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "view-box",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/transform-box",
  },
  "transform-origin": {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "tuple",
      value: [
        {
          type: "unit",
          unit: "%",
          value: 50,
        },
        {
          type: "unit",
          unit: "%",
          value: 50,
        },
        {
          type: "unit",
          unit: "px",
          value: 0,
        },
      ],
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/transform-origin",
  },
  "transform-style": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "flat",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/transform-style",
  },
  "transition-behavior": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/transition-behavior",
  },
  "transition-delay": {
    unitGroups: ["time"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "s",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/transition-delay",
  },
  "transition-duration": {
    unitGroups: ["time"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "s",
      value: 0,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/transition-duration",
  },
  "transition-property": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "all",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/transition-property",
  },
  "transition-timing-function": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "ease",
    },
    mdnUrl:
      "https://developer.mozilla.org/docs/Web/CSS/transition-timing-function",
  },
  translate: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/translate",
  },
  "unicode-bidi": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/unicode-bidi",
  },
  "user-select": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/user-select",
  },
  "vertical-align": {
    unitGroups: ["percentage", "length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "baseline",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/vertical-align",
  },
  visibility: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "visible",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/visibility",
  },
  "white-space-collapse": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "collapse",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/white-space-collapse",
  },
  widows: {
    unitGroups: ["number"],
    inherited: true,
    initial: {
      type: "unit",
      unit: "number",
      value: 2,
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/widows",
  },
  width: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/width",
  },
  "will-change": {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/will-change",
  },
  "word-break": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/word-break",
  },
  "word-spacing": {
    unitGroups: ["length"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/word-spacing",
  },
  "word-wrap": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/overflow-wrap",
  },
  "writing-mode": {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "horizontal-tb",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/writing-mode",
  },
  "z-index": {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/z-index",
  },
  zoom: {
    unitGroups: ["number", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    mdnUrl: "https://developer.mozilla.org/docs/Web/CSS/zoom",
  },
};
