// This file was generated by pnpm mdn-data
export const properties = {
  WebkitFontSmoothing: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  MozOsxFontSmoothing: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  accentColor: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["hex-color"],
  },
  alignContent: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: [],
  },
  alignItems: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: [],
  },
  alignSelf: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  animationDelay: {
    unitGroups: ["time"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "s",
      value: 0,
    },
    types: ["time"],
  },
  animationDirection: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: [],
  },
  animationDuration: {
    unitGroups: ["time"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "s",
      value: 0,
    },
    types: ["time"],
  },
  animationFillMode: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: [],
  },
  animationIterationCount: {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "number",
      value: 1,
    },
    types: ["number"],
  },
  animationName: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["custom-ident", "string"],
  },
  animationPlayState: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "running",
    },
    types: [],
  },
  animationTimingFunction: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "ease",
    },
    types: [],
  },
  appearance: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: [],
  },
  aspectRatio: {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["number"],
  },
  backdropFilter: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["url"],
  },
  backfaceVisibility: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "visible",
    },
    types: [],
  },
  backgroundAttachment: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "scroll",
    },
    types: [],
  },
  backgroundBlendMode: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: [],
  },
  backgroundClip: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "border-box",
    },
    types: [],
  },
  backgroundColor: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "transparent",
    },
    types: ["hex-color"],
  },
  backgroundImage: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["url"],
  },
  backgroundOrigin: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "padding-box",
    },
    types: [],
  },
  backgroundPosition: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "tuple",
      value: [
        {
          type: "unit",
          unit: "%",
          value: 0,
        },
        {
          type: "unit",
          unit: "%",
          value: 0,
        },
      ],
    },
    types: ["length", "percentage"],
  },
  backgroundRepeat: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "repeat",
    },
    types: [],
  },
  backgroundSize: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage"],
  },
  blockSize: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage"],
  },
  borderBlockColor: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentColor",
    },
    types: ["hex-color"],
  },
  borderBlockStyle: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: [],
  },
  borderBlockWidth: {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    types: ["length"],
  },
  borderBlockEndColor: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentColor",
    },
    types: ["hex-color"],
  },
  borderBlockEndStyle: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: [],
  },
  borderBlockEndWidth: {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    types: ["length"],
  },
  borderBlockStartColor: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentColor",
    },
    types: ["hex-color"],
  },
  borderBlockStartStyle: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: [],
  },
  borderBlockStartWidth: {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    types: ["length"],
  },
  borderBottomColor: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentColor",
    },
    types: ["hex-color"],
  },
  borderBottomLeftRadius: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length", "percentage"],
  },
  borderBottomRightRadius: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length", "percentage"],
  },
  borderBottomStyle: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: [],
  },
  borderBottomWidth: {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    types: ["length"],
  },
  borderCollapse: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "separate",
    },
    types: [],
  },
  borderEndEndRadius: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length", "percentage"],
  },
  borderEndStartRadius: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length", "percentage"],
  },
  borderImageOutset: {
    unitGroups: ["length", "number"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "number",
      value: 0,
    },
    types: ["length", "number"],
  },
  borderImageRepeat: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "stretch",
    },
    types: [],
  },
  borderImageSlice: {
    unitGroups: ["number", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "%",
      value: 100,
    },
    types: ["number", "percentage"],
  },
  borderImageSource: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["url"],
  },
  borderImageWidth: {
    unitGroups: ["length", "percentage", "number"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "number",
      value: 1,
    },
    types: ["length", "percentage", "number"],
  },
  borderInlineColor: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentColor",
    },
    types: ["hex-color"],
  },
  borderInlineStyle: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: [],
  },
  borderInlineWidth: {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    types: ["length"],
  },
  borderInlineEndColor: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentColor",
    },
    types: ["hex-color"],
  },
  borderInlineEndStyle: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: [],
  },
  borderInlineEndWidth: {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    types: ["length"],
  },
  borderInlineStartColor: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentColor",
    },
    types: ["hex-color"],
  },
  borderInlineStartStyle: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: [],
  },
  borderInlineStartWidth: {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    types: ["length"],
  },
  borderLeftColor: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentColor",
    },
    types: ["hex-color"],
  },
  borderLeftStyle: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: [],
  },
  borderLeftWidth: {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    types: ["length"],
  },
  borderRightColor: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentColor",
    },
    types: ["hex-color"],
  },
  borderRightStyle: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: [],
  },
  borderRightWidth: {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    types: ["length"],
  },
  borderSpacing: {
    unitGroups: ["length"],
    inherited: true,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length"],
  },
  borderStartEndRadius: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length", "percentage"],
  },
  borderStartStartRadius: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length", "percentage"],
  },
  borderTopColor: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentColor",
    },
    types: ["hex-color"],
  },
  borderTopLeftRadius: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length", "percentage"],
  },
  borderTopRightRadius: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length", "percentage"],
  },
  borderTopStyle: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: [],
  },
  borderTopWidth: {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    types: ["length"],
  },
  bottom: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage"],
  },
  boxDecorationBreak: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "slice",
    },
    types: [],
  },
  boxShadow: {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["length", "hex-color"],
  },
  boxSizing: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "content-box",
    },
    types: [],
  },
  breakAfter: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  breakBefore: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  breakInside: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  captionSide: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "top",
    },
    types: [],
  },
  caretColor: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["hex-color"],
  },
  clear: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: [],
  },
  clip: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  clipPath: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["url"],
  },
  color: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "black",
    },
    types: ["hex-color"],
  },
  colorScheme: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: ["custom-ident"],
  },
  columnCount: {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["integer"],
  },
  columnFill: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "balance",
    },
    types: [],
  },
  columnGap: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      value: 0,
      unit: "px",
    },
    types: ["length", "percentage"],
  },
  columnRuleColor: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentColor",
    },
    types: ["hex-color"],
  },
  columnRuleStyle: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: [],
  },
  columnRuleWidth: {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    types: ["length"],
  },
  columnSpan: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: [],
  },
  columnWidth: {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length"],
  },
  contain: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: [],
  },
  containIntrinsicBlockSize: {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["length"],
  },
  containIntrinsicHeight: {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["length"],
  },
  containIntrinsicInlineSize: {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["length"],
  },
  containIntrinsicWidth: {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["length"],
  },
  containerName: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["custom-ident"],
  },
  containerType: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: [],
  },
  content: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: ["url", "string"],
  },
  contentVisibility: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "visible",
    },
    types: [],
  },
  counterIncrement: {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["custom-ident", "integer"],
  },
  counterReset: {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["custom-ident", "integer"],
  },
  counterSet: {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["custom-ident", "integer"],
  },
  cursor: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["url", "x", "y"],
  },
  direction: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "ltr",
    },
    types: [],
  },
  display: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "inline",
    },
    types: [],
  },
  emptyCells: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "show",
    },
    types: [],
  },
  fieldSizing: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "fixed",
    },
    types: [],
  },
  filter: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["url"],
  },
  flexBasis: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage"],
  },
  flexDirection: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "row",
    },
    types: [],
  },
  flexGrow: {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "number",
      value: 0,
    },
    types: ["number"],
  },
  flexShrink: {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "number",
      value: 1,
    },
    types: ["number"],
  },
  flexWrap: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "nowrap",
    },
    types: [],
  },
  float: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: [],
  },
  fontFamily: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "inherit",
    },
    types: ["string", "custom-ident"],
  },
  fontFeatureSettings: {
    unitGroups: ["number"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: ["string", "integer"],
  },
  fontKerning: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  fontLanguageOverride: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: ["string"],
  },
  fontOpticalSizing: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  fontVariationSettings: {
    unitGroups: ["number"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: ["string", "number"],
  },
  fontSize: {
    unitGroups: ["length", "percentage"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "inherit",
    },
    types: ["length", "percentage"],
  },
  fontSizeAdjust: {
    unitGroups: ["number"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["number"],
  },
  fontStretch: {
    unitGroups: ["percentage"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: ["percentage"],
  },
  fontStyle: {
    unitGroups: ["angle"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: ["angle"],
  },
  fontSynthesisSmallCaps: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  fontSynthesisStyle: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  fontSynthesisWeight: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  fontVariantAlternates: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: [],
  },
  fontVariantCaps: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: [],
  },
  fontVariantEastAsian: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: [],
  },
  fontVariantLigatures: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: [],
  },
  fontVariantNumeric: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: [],
  },
  fontVariantPosition: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: [],
  },
  fontWeight: {
    unitGroups: ["number"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: ["number"],
  },
  gridAutoColumns: {
    unitGroups: ["length", "percentage", "flex"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage", "flex"],
  },
  gridAutoFlow: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "row",
    },
    types: [],
  },
  gridAutoRows: {
    unitGroups: ["length", "percentage", "flex"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage", "flex"],
  },
  gridColumnEnd: {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["custom-ident", "integer"],
  },
  gridColumnStart: {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["custom-ident", "integer"],
  },
  gridRowEnd: {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["custom-ident", "integer"],
  },
  gridRowStart: {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["custom-ident", "integer"],
  },
  gridTemplateAreas: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["string"],
  },
  gridTemplateColumns: {
    unitGroups: ["length", "percentage", "flex"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["custom-ident", "length", "percentage", "flex"],
  },
  gridTemplateRows: {
    unitGroups: ["length", "percentage", "flex"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["custom-ident", "length", "percentage", "flex"],
  },
  hangingPunctuation: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: [],
  },
  height: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage"],
  },
  hyphenateCharacter: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["string"],
  },
  hyphenateLimitChars: {
    unitGroups: ["number"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["integer"],
  },
  hyphens: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "manual",
    },
    types: [],
  },
  imageOrientation: {
    unitGroups: ["angle"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "from-image",
    },
    types: ["angle"],
  },
  imageRendering: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  inlineSize: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage"],
  },
  insetBlockEnd: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage"],
  },
  insetBlockStart: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage"],
  },
  insetInlineEnd: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage"],
  },
  insetInlineStart: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage"],
  },
  isolation: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  justifyContent: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: [],
  },
  justifyItems: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "legacy",
    },
    types: [],
  },
  justifySelf: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  left: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage"],
  },
  letterSpacing: {
    unitGroups: ["length"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: ["length"],
  },
  lineBreak: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  lineClamp: {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["integer"],
  },
  lineHeight: {
    unitGroups: ["number", "length", "percentage"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "inherit",
    },
    types: ["number", "length", "percentage"],
  },
  listStyleImage: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["url"],
  },
  listStylePosition: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "outside",
    },
    types: [],
  },
  listStyleType: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "disc",
    },
    types: ["custom-ident", "string"],
  },
  marginBlockEnd: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length", "percentage"],
  },
  marginBlockStart: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length", "percentage"],
  },
  marginBottom: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length", "percentage"],
  },
  marginInlineEnd: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length", "percentage"],
  },
  marginInlineStart: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length", "percentage"],
  },
  marginLeft: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length", "percentage"],
  },
  marginRight: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length", "percentage"],
  },
  marginTop: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length", "percentage"],
  },
  maskBorderMode: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "alpha",
    },
    types: [],
  },
  maskBorderOutset: {
    unitGroups: ["length", "number"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "number",
      value: 0,
    },
    types: ["length", "number"],
  },
  maskBorderRepeat: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "stretch",
    },
    types: [],
  },
  maskBorderSlice: {
    unitGroups: ["number", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "number",
      value: 0,
    },
    types: ["number", "percentage"],
  },
  maskBorderSource: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["url"],
  },
  maskBorderWidth: {
    unitGroups: ["length", "percentage", "number"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage", "number"],
  },
  maskClip: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "border-box",
    },
    types: [],
  },
  maskComposite: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "add",
    },
    types: [],
  },
  maskImage: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["url"],
  },
  maskMode: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "match-source",
    },
    types: [],
  },
  maskOrigin: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "border-box",
    },
    types: [],
  },
  maskPosition: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "tuple",
      value: [
        {
          type: "unit",
          unit: "%",
          value: 0,
        },
        {
          type: "unit",
          unit: "%",
          value: 0,
        },
      ],
    },
    types: ["length", "percentage"],
  },
  maskRepeat: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "repeat",
    },
    types: [],
  },
  maskSize: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage"],
  },
  maskType: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "luminance",
    },
    types: [],
  },
  mathDepth: {
    unitGroups: ["number"],
    inherited: true,
    initial: {
      type: "unit",
      unit: "number",
      value: 0,
    },
    types: ["integer"],
  },
  mathShift: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: [],
  },
  mathStyle: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: [],
  },
  maxBlockSize: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["length", "percentage"],
  },
  maxHeight: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["length", "percentage"],
  },
  maxInlineSize: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["length", "percentage"],
  },
  maxWidth: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["length", "percentage"],
  },
  minBlockSize: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length", "percentage"],
  },
  minHeight: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage"],
  },
  minInlineSize: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length", "percentage"],
  },
  minWidth: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage"],
  },
  mixBlendMode: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: [],
  },
  objectFit: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "fill",
    },
    types: [],
  },
  objectPosition: {
    unitGroups: ["length", "percentage"],
    inherited: true,
    initial: {
      type: "tuple",
      value: [
        {
          type: "unit",
          unit: "%",
          value: 50,
        },
        {
          type: "unit",
          unit: "%",
          value: 50,
        },
      ],
    },
    types: ["length", "percentage"],
  },
  offsetDistance: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length", "percentage"],
  },
  offsetPath: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["offset-path", "coord-box"],
  },
  offsetRotate: {
    unitGroups: ["angle"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["angle"],
  },
  opacity: {
    unitGroups: ["number", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "number",
      value: 1,
    },
    types: ["number", "percentage"],
  },
  order: {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "number",
      value: 0,
    },
    types: ["integer"],
  },
  orphans: {
    unitGroups: ["number"],
    inherited: true,
    initial: {
      type: "unit",
      unit: "number",
      value: 2,
    },
    types: ["integer"],
  },
  outlineColor: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["hex-color"],
  },
  outlineOffset: {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length"],
  },
  outlineStyle: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: [],
  },
  outlineWidth: {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "medium",
    },
    types: ["length"],
  },
  overflowWrap: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: [],
  },
  overflowX: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "visible",
    },
    types: [],
  },
  overflowY: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "visible",
    },
    types: [],
  },
  overscrollBehavior: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  overscrollBehaviorBlock: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  overscrollBehaviorInline: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  overscrollBehaviorX: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  overscrollBehaviorY: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  paddingBlockEnd: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length", "percentage"],
  },
  paddingBlockStart: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length", "percentage"],
  },
  paddingBottom: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length", "percentage"],
  },
  paddingInlineEnd: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length", "percentage"],
  },
  paddingInlineStart: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length", "percentage"],
  },
  paddingLeft: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length", "percentage"],
  },
  paddingRight: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length", "percentage"],
  },
  paddingTop: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length", "percentage"],
  },
  page: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["custom-ident"],
  },
  pageBreakAfter: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  pageBreakBefore: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  pageBreakInside: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  paintOrder: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: [],
  },
  perspective: {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["length"],
  },
  perspectiveOrigin: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "tuple",
      value: [
        {
          type: "unit",
          unit: "%",
          value: 50,
        },
        {
          type: "unit",
          unit: "%",
          value: 50,
        },
      ],
    },
    types: ["length", "percentage"],
  },
  pointerEvents: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  position: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "static",
    },
    types: [],
  },
  printColorAdjust: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "economy",
    },
    types: [],
  },
  quotes: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "dependsOnUserAgent",
    },
    types: ["string"],
  },
  resize: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: [],
  },
  right: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage"],
  },
  rotate: {
    unitGroups: ["angle", "number"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["angle", "number"],
  },
  rowGap: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      value: 0,
      unit: "px",
    },
    types: ["length", "percentage"],
  },
  scale: {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["number"],
  },
  scrollbarColor: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["hex-color"],
  },
  scrollbarGutter: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  scrollbarWidth: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  scrollBehavior: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  scrollMarginBlockStart: {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length"],
  },
  scrollMarginBlockEnd: {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length"],
  },
  scrollMarginBottom: {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length"],
  },
  scrollMarginInlineStart: {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length"],
  },
  scrollMarginInlineEnd: {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length"],
  },
  scrollMarginLeft: {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length"],
  },
  scrollMarginRight: {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length"],
  },
  scrollMarginTop: {
    unitGroups: ["length"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length"],
  },
  scrollPaddingBlockStart: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage"],
  },
  scrollPaddingBlockEnd: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage"],
  },
  scrollPaddingBottom: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage"],
  },
  scrollPaddingInlineStart: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage"],
  },
  scrollPaddingInlineEnd: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage"],
  },
  scrollPaddingLeft: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage"],
  },
  scrollPaddingRight: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage"],
  },
  scrollPaddingTop: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage"],
  },
  scrollSnapAlign: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: [],
  },
  scrollSnapStop: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: [],
  },
  scrollSnapType: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: [],
  },
  shapeImageThreshold: {
    unitGroups: ["number", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "number",
      value: 0,
    },
    types: ["number", "percentage"],
  },
  shapeMargin: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length", "percentage"],
  },
  shapeOutside: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["url"],
  },
  tabSize: {
    unitGroups: ["number", "length"],
    inherited: true,
    initial: {
      type: "unit",
      unit: "number",
      value: 8,
    },
    types: ["integer", "length"],
  },
  tableLayout: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  textAlign: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "start",
    },
    types: [],
  },
  textAlignLast: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  textCombineUpright: {
    unitGroups: ["number"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["integer"],
  },
  textDecorationColor: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "currentColor",
    },
    types: ["hex-color"],
  },
  textDecorationLine: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: [],
  },
  textDecorationSkipInk: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  textDecorationStyle: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "solid",
    },
    types: [],
  },
  textDecorationThickness: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage"],
  },
  textEmphasisColor: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "currentColor",
    },
    types: ["hex-color"],
  },
  textEmphasisPosition: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "tuple",
      value: [
        {
          type: "keyword",
          value: "over",
        },
        {
          type: "keyword",
          value: "right",
        },
      ],
    },
    types: [],
  },
  textEmphasisStyle: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["string"],
  },
  textIndent: {
    unitGroups: ["length", "percentage"],
    inherited: true,
    initial: {
      type: "unit",
      unit: "px",
      value: 0,
    },
    types: ["length", "percentage"],
  },
  textJustify: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  textOrientation: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "mixed",
    },
    types: [],
  },
  textOverflow: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "clip",
    },
    types: ["string"],
  },
  textRendering: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  textShadow: {
    unitGroups: ["length"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["length", "hex-color"],
  },
  textSizeAdjust: {
    unitGroups: ["percentage"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["percentage"],
  },
  textTransform: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: [],
  },
  textUnderlineOffset: {
    unitGroups: ["length", "percentage"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage"],
  },
  textUnderlinePosition: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  top: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage"],
  },
  touchAction: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  transform: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: [],
  },
  transformBox: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "view-box",
    },
    types: [],
  },
  transformOrigin: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "tuple",
      value: [
        {
          type: "unit",
          unit: "%",
          value: 50,
        },
        {
          type: "unit",
          unit: "%",
          value: 50,
        },
        {
          type: "unit",
          unit: "px",
          value: 0,
        },
      ],
    },
    types: ["length", "percentage"],
  },
  transformStyle: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "flat",
    },
    types: [],
  },
  transition: {
    unitGroups: ["time"],
    inherited: false,
    initial: {
      type: "tuple",
      value: [
        {
          type: "keyword",
          value: "all",
        },
        {
          type: "unit",
          unit: "s",
          value: 0,
        },
        {
          type: "keyword",
          value: "ease",
        },
        {
          type: "unit",
          unit: "s",
          value: 0,
        },
      ],
    },
    types: ["custom-ident", "time"],
  },
  transitionDelay: {
    unitGroups: ["time"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "s",
      value: 0,
    },
    types: ["time"],
  },
  transitionDuration: {
    unitGroups: ["time"],
    inherited: false,
    initial: {
      type: "unit",
      unit: "s",
      value: 0,
    },
    types: ["time"],
  },
  transitionProperty: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "all",
    },
    types: ["custom-ident"],
  },
  transitionTimingFunction: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "ease",
    },
    types: [],
  },
  translate: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "none",
    },
    types: ["length", "percentage"],
  },
  unicodeBidi: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: [],
  },
  userSelect: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: [],
  },
  verticalAlign: {
    unitGroups: ["percentage", "length"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "baseline",
    },
    types: ["percentage", "length"],
  },
  visibility: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "visible",
    },
    types: [],
  },
  whiteSpace: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: [],
  },
  widows: {
    unitGroups: ["number"],
    inherited: true,
    initial: {
      type: "unit",
      unit: "number",
      value: 2,
    },
    types: ["integer"],
  },
  width: {
    unitGroups: ["length", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["length", "percentage"],
  },
  willChange: {
    unitGroups: [],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["custom-ident"],
  },
  wordBreak: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: [],
  },
  wordSpacing: {
    unitGroups: ["length"],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: ["length"],
  },
  wordWrap: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: [],
  },
  writingMode: {
    unitGroups: [],
    inherited: true,
    initial: {
      type: "keyword",
      value: "horizontal-tb",
    },
    types: [],
  },
  zIndex: {
    unitGroups: ["number"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "auto",
    },
    types: ["integer"],
  },
  zoom: {
    unitGroups: ["number", "percentage"],
    inherited: false,
    initial: {
      type: "keyword",
      value: "normal",
    },
    types: ["number", "percentage"],
  },
} as const;
