// This file was generated by pnpm mdn-data
export const shorthandExpansions = {
  "-ms-content-zoom-limit": {
    "-ms-content-zoom-limit-max": "400%",
    "-ms-content-zoom-limit-min": "100%",
  },
  "-ms-content-zoom-snap": {
    "-ms-content-zoom-snap-type": "none",
    "-ms-content-zoom-snap-points": "snapInterval(0%, 100%)",
  },
  "-ms-scroll-limit": {
    "-ms-scroll-limit-x-min": "0",
    "-ms-scroll-limit-y-min": "0",
    "-ms-scroll-limit-x-max": "auto",
    "-ms-scroll-limit-y-max": "auto",
  },
  "-ms-scroll-snap-x": {
    "-ms-scroll-snap-type": "none",
    "-ms-scroll-snap-points-x": "snapInterval(0px, 100%)",
  },
  "-ms-scroll-snap-y": {
    "-ms-scroll-snap-type": "none",
    "-ms-scroll-snap-points-y": "snapInterval(0px, 100%)",
  },
  "animation-range": {
    "animation-range-start": "normal",
    "animation-range-end": "normal",
  },
  "border-image": {
    "border-image-source": "none",
    "border-image-slice": "100%",
    "border-image-width": "1",
    "border-image-outset": "0",
    "border-image-repeat": "stretch",
  },
  caret: {
    "caret-color": "auto",
    "caret-animation": "auto",
    "caret-shape": "auto",
  },
  "column-rule": {
    "column-rule-width": "medium",
    "column-rule-style": "none",
    "column-rule-color": "currentcolor",
  },
  columns: {
    "column-width": "auto",
    "column-count": "auto",
    "column-height": "auto",
  },
  container: {
    "container-name": "none",
    "container-type": "normal",
  },
  flex: {
    "flex-grow": "0",
    "flex-shrink": "1",
    "flex-basis": "auto",
  },
  "flex-flow": {
    "flex-direction": "row",
    "flex-wrap": "nowrap",
  },
  gap: {
    "row-gap": "normal",
    "column-gap": "normal",
  },
  "grid-gap": {
    "grid-row-gap": "0",
    "grid-column-gap": "0",
  },
  "list-style": {
    "list-style-type": "disc",
    "list-style-position": "outside",
    "list-style-image": "none",
  },
  "mask-border": {
    "mask-border-mode": "alpha",
    "mask-border-outset": "0",
    "mask-border-repeat": "stretch",
    "mask-border-slice": "0",
    "mask-border-source": "none",
    "mask-border-width": "auto",
  },
  offset: {
    "offset-position": "normal",
    "offset-path": "none",
    "offset-distance": "0",
    "offset-anchor": "auto",
    "offset-rotate": "auto",
  },
  outline: {
    "outline-width": "medium",
    "outline-style": "none",
    "outline-color": "auto",
  },
  "place-content": {
    "align-content": "normal",
    "justify-content": "normal",
  },
  "place-items": {
    "align-items": "normal",
    "justify-items": "legacy",
  },
  "place-self": {
    "align-self": "auto",
    "justify-self": "auto",
  },
  "position-try": {
    "position-try-fallbacks": "none",
    "position-try-order": "normal",
  },
  "scroll-timeline": {
    "scroll-timeline-name": "none",
    "scroll-timeline-axis": "block",
  },
  "text-emphasis": {
    "text-emphasis-style": "none",
    "text-emphasis-color": "currentcolor",
  },
} as const;
