// This file was generated by pnpm mdn-data
export const units = {
  number: [],
  percentage: ["%"],
  angle: ["deg", "grad", "rad", "turn"],
  decibel: ["db"],
  flex: ["fr"],
  frequency: ["hz", "khz"],
  length: ["px", "em", "rem", "vw", "vh"],
  resolution: ["dpi", "dpcm", "dppx", "x"],
  semitones: ["st"],
  time: ["s", "ms"],
} as const;
