import {
  colorControllerNames,
  darkColorControllers,
  lightColorControllers,
} from "./color-controllers.generated";

const colorVariable = (name: string) => `var(--colors-${name})`;

const controller = {
  canvas: colorVariable("theme-canvas"),
  ink: colorVariable("theme-ink"),
  accent: colorVariable("theme-accent"),
  positive: colorVariable("theme-positive"),
  negative: colorVariable("theme-negative"),
  warning: colorVariable("theme-warning"),
  informative: colorVariable("theme-informative"),
} as const;

const mix = (first: string, firstWeight: number, second: string) =>
  `color-mix(in oklch, ${first} ${firstWeight}%, ${second})`;

const alpha = (color: string, percentage: number) =>
  `oklch(from ${color} l c h / ${percentage}%)`;

const rotateHue = (color: string, degrees: number) =>
  `oklch(from ${color} l c calc(h + ${degrees}))`;

const semanticColor = {
  backgroundCanvas: controller.canvas,
  backgroundNeutralSubtle: mix(controller.canvas, 97, controller.ink),
  backgroundNeutral: mix(controller.canvas, 92, controller.ink),
  backgroundNeutralHover: mix(controller.canvas, 88, controller.ink),
  backgroundNeutralPressed: mix(controller.canvas, 82, controller.ink),
  backgroundNeutralDisabled: mix(controller.canvas, 96, controller.ink),
  backgroundNeutralStrong: mix(controller.canvas, 68, controller.ink),
  backgroundInverse: controller.ink,
  backgroundInverseHover: mix(controller.ink, 88, controller.canvas),
  backgroundAccent: controller.accent,
  backgroundAccentHover: mix(controller.accent, 88, controller.ink),
  backgroundAccentPressed: mix(controller.accent, 78, controller.ink),
  backgroundAccentSubtle: mix(controller.accent, 12, controller.canvas),
  backgroundAccentSubtleHover: mix(controller.accent, 20, controller.canvas),
  backgroundPositive: controller.positive,
  backgroundPositiveHover: mix(controller.positive, 88, controller.ink),
  backgroundPositiveSubtle: mix(controller.positive, 12, controller.canvas),
  backgroundPositiveSubtleHover: mix(
    controller.positive,
    20,
    controller.canvas
  ),
  backgroundNegative: controller.negative,
  backgroundNegativeHover: mix(controller.negative, 88, controller.ink),
  backgroundNegativeSubtle: mix(controller.negative, 12, controller.canvas),
  backgroundNegativeSubtleHover: mix(
    controller.negative,
    20,
    controller.canvas
  ),
  backgroundWarning: controller.warning,
  backgroundWarningHover: mix(controller.warning, 88, controller.ink),
  backgroundWarningSubtle: mix(controller.warning, 12, controller.canvas),
  backgroundWarningSubtleHover: mix(controller.warning, 20, controller.canvas),
  backgroundInformative: controller.informative,
  backgroundInformativeHover: mix(controller.informative, 88, controller.ink),
  backgroundInformativeSubtle: mix(
    controller.informative,
    12,
    controller.canvas
  ),
  backgroundInformativeSubtleHover: mix(
    controller.informative,
    20,
    controller.canvas
  ),
  contentPrimary: controller.ink,
  contentSecondary: mix(controller.ink, 68, controller.canvas),
  contentMuted: mix(controller.ink, 52, controller.canvas),
  contentDisabled: mix(controller.ink, 34, controller.canvas),
  contentInverse: controller.canvas,
  contentInverseSecondary: mix(controller.canvas, 72, controller.ink),
  contentAccent: mix(controller.accent, 86, controller.ink),
  contentPositive: mix(controller.positive, 86, controller.ink),
  contentNegative: mix(controller.negative, 86, controller.ink),
  contentWarning: mix(controller.warning, 86, controller.ink),
  contentInformative: mix(controller.informative, 86, controller.ink),
  borderDefault: mix(controller.canvas, 80, controller.ink),
  borderStrong: mix(controller.canvas, 62, controller.ink),
  borderFocus: controller.accent,
  borderAccent: mix(controller.accent, 62, controller.canvas),
  borderPositive: mix(controller.positive, 62, controller.canvas),
  borderNegative: mix(controller.negative, 62, controller.canvas),
  borderWarning: mix(controller.warning, 62, controller.canvas),
  borderInformative: mix(controller.informative, 62, controller.canvas),
  overlaySubtle: alpha(controller.ink, 6),
  overlayPressed: alpha(controller.ink, 11),
  overlayScrim: alpha(controller.ink, 48),
} as const;

const semantic = <Name extends keyof typeof semanticColor>(name: Name) =>
  colorVariable(name);

const accentAlternative = rotateHue(controller.accent, 72);
const accentComplement = rotateHue(controller.accent, 145);
const accentWarm = rotateHue(controller.accent, 210);
const transparentAccent = alpha(controller.accent, 0);
const transparentInk = alpha(controller.ink, 0);

/**
 * Compatibility names used by existing components and downstream packages.
 * New design-system code should use semanticColor directly.
 */
const compatibilityColor = {
  white: "oklch(from var(--colors-theme-canvas) 100% 0 h)",
  black: "oklch(from var(--colors-theme-ink) 0% 0 h)",
  backgroundPanel: semantic("backgroundCanvas"),
  backgroundPrimary: semantic("backgroundAccent"),
  backgroundHover: semantic("backgroundNeutralHover"),
  backgroundActive: semantic("backgroundAccent"),
  backgroundMenu: semantic("backgroundNeutralSubtle"),
  backgroundControls: semantic("backgroundNeutralSubtle"),
  backgroundAssetcardHover: semantic("backgroundNeutralHover"),
  backgroundNeutralMain: semantic("backgroundNeutral"),
  backgroundNeutralAccent: semantic("backgroundInverse"),
  backgroundNeutralNotification: semantic("backgroundNeutralSubtle"),
  backgroundNeutralDark: semantic("backgroundNeutralStrong"),
  backgroundDestructiveMain: semantic("backgroundNegative"),
  backgroundDestructiveNotification: semantic("backgroundNegativeSubtle"),
  backgroundSuccessMain: semantic("backgroundPositive"),
  backgroundSuccessNotification: semantic("backgroundPositiveSubtle"),
  backgroundStatusAttention: semantic("backgroundWarningSubtle"),
  backgroundAlertMain: semantic("backgroundWarning"),
  backgroundAlertNotification: semantic("backgroundWarningSubtle"),
  backgroundInfoMain: semantic("backgroundInformative"),
  backgroundInfoNotification: semantic("backgroundInformativeSubtle"),
  backgroundPresetMain: semantic("backgroundNeutral"),
  backgroundPresetHover: semantic("backgroundNeutralHover"),
  backgroundLocalMain: semantic("backgroundInformativeSubtle"),
  backgroundLocalHover: semantic("backgroundInformativeSubtleHover"),
  backgroundRemoteMain: semantic("backgroundWarningSubtle"),
  backgroundRemoteHover: semantic("backgroundWarningSubtleHover"),
  backgroundInputSelected: semantic("backgroundInformativeSubtle"),
  backgroundInputDisabled: semantic("backgroundNeutralDisabled"),
  backgroundInputHighlight: semantic("backgroundInformativeSubtle"),
  backgroundButtonHover: semantic("overlaySubtle"),
  backgroundButtonPressed: semantic("overlayPressed"),
  backgroundButtonDisabled: semantic("backgroundNeutralDisabled"),
  backgroundButtonDisabledDark: semantic("backgroundNeutralStrong"),
  backgroundItemCurrent: semantic("backgroundAccentSubtle"),
  backgroundItemCurrentChild: mix(controller.accent, 7, controller.canvas),
  backgroundItemCurrentHidden: semantic("contentMuted"),
  backgroundItemMenuItemHover: semantic("backgroundNeutralHover"),
  backgroundTooltipMain: semantic("backgroundInverse"),
  backgroundTooltipBuilder: semantic("backgroundCanvas"),
  backgroundTooltipDesigner: semantic("backgroundCanvas"),
  backgroundSpacingTopBottom: semantic("backgroundNeutralDisabled"),
  backgroundSpacingLeftRight: semantic("backgroundNeutralSubtle"),
  backgroundSpacingHover: semantic("backgroundNeutralHover"),
  backgroundStyleSourceSelected: semantic("backgroundAccent"),
  backgroundStyleSourceTag: semantic("backgroundNegative"),
  backgroundStyleSourceState: semantic("backgroundPositive"),
  backgroundStyleSourceNeutral: semantic("contentSecondary"),
  backgroundStyleSourceDisabled: semantic("contentDisabled"),
  backgroundStyleSourceGradientSelected: `linear-gradient(90deg, ${transparentAccent} 0%, ${controller.accent} 31.87%)`,
  backgroundStyleSourceGradientTag: `linear-gradient(90deg, ${alpha(controller.negative, 0)} 0%, ${controller.negative} 31.87%)`,
  backgroundStyleSourceGradientUnselected: `linear-gradient(90deg, ${transparentInk} 0%, ${semantic("contentSecondary")} 31.87%)`,
  backgroundStyleSourceBreakpoint: accentAlternative,
  backgroundTopbar: semantic("backgroundInverse"),
  backgroundGradientPrimary: `linear-gradient(135deg, ${controller.accent}, ${accentAlternative})`,
  backgroundGradientVertical: `linear-gradient(180deg, ${controller.accent}, ${accentAlternative})`,
  backgroundGradientHorizontal: `linear-gradient(90deg, ${controller.accent}, ${accentAlternative})`,
  backgroundGradientHorizontalReverse: `linear-gradient(90deg, ${accentAlternative}, ${controller.accent})`,
  backgroundMenuHint: semantic("backgroundNeutralHover"),
  backgroundTopbarHover: semantic("backgroundInverseHover"),
  backgroundWorkspace: semantic("backgroundNeutralStrong"),
  backgroundIconSubtle: mix(controller.ink, 84, controller.canvas),
  backgroundPrimaryLight: mix(controller.accent, 88, controller.canvas),
  backgroundOverwrittenMain: semantic("backgroundNegativeSubtle"),
  backgroundOverwrittenHover: semantic("backgroundNegativeSubtleHover"),
  backgroundDisabledDark: mix(controller.ink, 88, controller.canvas),
  brandBackgroundProjectCardFront: `linear-gradient(0deg, ${semantic("backgroundCanvas")}, ${semantic("backgroundNeutral")})`,
  brandBackgroundProjectCardBack: `linear-gradient(0deg, ${semantic("backgroundCanvas")}, ${semantic("backgroundNeutralStrong")})`,
  brandBackgroundProjectCardTextArea: semantic("backgroundCanvas"),
  brandBackgroundPublishedMain: semantic("backgroundPositive"),
  brandBackgroundGradient: `linear-gradient(180deg, ${accentAlternative}, ${accentWarm})`,
  brandBackgroundPublishedContrast: semantic("backgroundPositiveSubtle"),
  brandBackgroundDashboard: `radial-gradient(circle at 50% 50%, ${alpha(controller.canvas, 100)}, ${alpha(controller.canvas, 0)} 55%), linear-gradient(145deg, ${alpha(accentAlternative, 24)}, ${alpha(controller.positive, 16)}, ${semantic("backgroundCanvas")})`,
  brandBackgroundRegularButtonSelected: `linear-gradient(180deg, ${mix(controller.positive, 24, controller.canvas)}, ${semantic("backgroundCanvas")})`,
  brandBackgroundCtaButton: `linear-gradient(135deg, ${controller.accent}, ${accentAlternative})`,
  brandForegroundPublished: semantic("contentPositive"),
  brandBorderPublished: semantic("borderPositive"),
  brandBorderFullGradient: `linear-gradient(135deg, ${controller.positive}, ${controller.accent}, ${accentAlternative}, ${accentWarm})`,
  brandBorderNavbar: `linear-gradient(90deg, ${alpha(controller.positive, 0)}, ${controller.positive}, ${controller.accent}, ${accentAlternative}, ${accentWarm}, ${alpha(accentWarm, 0)})`,
  brandSpinnerTurquoise: controller.positive,
  brandSpinnerBlue: controller.accent,
  brandSpinnerPurple: accentAlternative,
  brandSpinnerOrange: accentWarm,
  borderMain: semantic("borderDefault"),
  borderMenuInner: mix(controller.canvas, 98, controller.ink),
  borderColorSwatch: semantic("borderStrong"),
  borderNeutral: semantic("borderDefault"),
  borderSuccess: semantic("borderPositive"),
  borderAlert: semantic("borderWarning"),
  borderInfo: semantic("borderInformative"),
  borderContrast: semantic("contentInverse"),
  borderItemChildLine: semantic("contentMuted"),
  borderItemChildLineCurrent: semantic("borderAccent"),
  borderLocalMain: semantic("borderInformative"),
  borderLocalFlexUi: semantic("borderFocus"),
  borderRemoteMain: semantic("borderWarning"),
  borderRemoteFlexUi: semantic("contentWarning"),
  borderDestructiveMain: semantic("borderNegative"),
  borderDestructiveNotification: mix(
    controller.negative,
    30,
    controller.canvas
  ),
  borderDark: semantic("borderStrong"),
  borderOverwrittenMain: semantic("borderNegative"),
  borderOverwrittenFlexUi: semantic("contentNegative"),
  borderPrimary: semantic("borderFocus"),
  foregroundMain: semantic("contentPrimary"),
  foregroundSubtle: semantic("contentSecondary"),
  foregroundCategoryLabel: semantic("contentMuted"),
  foregroundTextSubtle: semantic("contentSecondary"),
  foregroundDestructive: semantic("contentNegative"),
  foregroundSuccess: semantic("contentPositive"),
  foregroundInfo: semantic("contentInformative"),
  foregroundDisabled: semantic("contentDisabled"),
  foregroundHiddenItem: semantic("contentMuted"),
  foregroundFlexUiMain: semantic("contentDisabled"),
  foregroundFlexUiHover: semantic("contentSecondary"),
  foregroundContrastMain: semantic("contentInverse"),
  foregroundContrastSubtle: semantic("contentInverseSecondary"),
  foregroundLocalMain: semantic("contentInformative"),
  foregroundLocalFlexUi: semantic("contentInformative"),
  foregroundRemoteMain: semantic("contentWarning"),
  foregroundRemoteFlexUi: semantic("contentWarning"),
  foregroundTextMoreSubtle: semantic("contentMuted"),
  foregroundPrimary: semantic("contentAccent"),
  foregroundSuccessText: semantic("contentPositive"),
  foregroundGridControlsDot: semantic("contentDisabled"),
  foregroundGridControlsDotHover: semantic("contentSecondary"),
  foregroundGridControlsFlexHover: semantic("contentSecondary"),
  foregroundIconSecondary: semantic("contentDisabled"),
  foregroundIconMain: semantic("contentPrimary"),
  foregroundMoreSubtle: semantic("contentDisabled"),
  foregroundScrollBar: alpha(controller.ink, 48),
  foregroundOverwrittenMain: semantic("contentNegative"),
  foregroundOverwrittenFlexUi: semantic("contentNegative"),
  foregroundInversePrimary: accentComplement,
  foregroundReusable: accentAlternative,
  maintenanceLight: semantic("backgroundNeutralSubtle"),
  maintenanceMedium: semantic("backgroundNeutralStrong"),
  maintenanceDark: semantic("contentMuted"),
  maintenanceSpacerViz: semantic("backgroundNegativeSubtle"),
  darkBlueFade: `linear-gradient(180deg, ${mix(controller.accent, 18, controller.ink)}, ${alpha(controller.ink, 0)})`,
  strokeFade: `linear-gradient(180deg, ${mix(controller.accent, 70, controller.canvas)}, ${alpha(controller.accent, 0)})`,
} as const;

export const color = {
  ...lightColorControllers,
  ...semanticColor,
  ...compatibilityColor,
} as const;

export {
  colorControllerNames,
  darkColorControllers,
  lightColorControllers,
  semanticColor,
};
