import { readdir, readFile, writeFile } from "node:fs/promises";
import { relative } from "node:path";
import { fileURLToPath } from "node:url";
import { parseColorSource } from "./color-source-utils";
import {
  getUniqueCssVariableNames,
  parseCssVariableDeclarations,
  type CssVariableDeclaration,
} from "./css-variable-source-utils";

const sourceUrl = new URL("./colors.css", import.meta.url);
const outputUrl = new URL(
  "./__generated__/css-variable-names.d.ts",
  import.meta.url
);

const source = parseColorSource(await readFile(sourceUrl, "utf8"));
const repositoryUrl = new URL("../../../../", import.meta.url);

const ignoredDirectories = new Set([
  ".git",
  "__generated__",
  "dist",
  "lib",
  "node_modules",
]);
const isSourceFile = (name: string) =>
  (name.endsWith(".ts") || name.endsWith(".tsx")) &&
  name.endsWith(".d.ts") === false &&
  name.includes(".test.") === false &&
  name.includes(".stories.") === false;

const collectDeclarations = async (
  directoryUrl: URL
): Promise<CssVariableDeclaration[]> => {
  const declarations: CssVariableDeclaration[] = [];
  for (const entry of await readdir(directoryUrl, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (ignoredDirectories.has(entry.name)) {
        continue;
      }
      declarations.push(
        ...(await collectDeclarations(new URL(`${entry.name}/`, directoryUrl)))
      );
      continue;
    }
    if (entry.isFile() === false || isSourceFile(entry.name) === false) {
      continue;
    }
    const fileUrl = new URL(entry.name, directoryUrl);
    const fileName = relative(
      fileURLToPath(repositoryUrl),
      fileURLToPath(fileUrl)
    );
    declarations.push(
      ...parseCssVariableDeclarations({
        code: await readFile(fileUrl, "utf8"),
        source: fileName,
      })
    );
  }
  return declarations;
};

const themeNames = [
  ...Object.keys(source.theme.color).map((name) => `--theme-color-${name}`),
  ...Object.keys(source.theme.contrast).map(
    (name) => `--theme-contrast-${name}`
  ),
];
const names = Object.entries(source.semantic).flatMap(([category, colors]) =>
  Object.keys(colors).map((name) => `--${category}-${name}`)
);
const colorDeclarationNames = new Set([
  ...themeNames,
  ...Object.keys(source.scheme.light).map((name) => `--scheme-${name}`),
  ...Object.keys(source.derived).map((name) => `--color-${name}`),
  ...names,
]);
const declarations = (
  await Promise.all(
    ["apps/", "packages/"].map((directory) =>
      collectDeclarations(new URL(directory, repositoryUrl))
    )
  )
).flat();
const componentNames = getUniqueCssVariableNames({
  declarations,
  reservedNames: colorDeclarationNames,
});
const cssVariableNames = [...names, ...componentNames];
const generated = `// Generated by generate-color-types.ts from colors.css and declareCssVar() calls. Do not edit directly.\n\nexport type ThemeVariableName =\n${themeNames
  .map((name) => `  | ${JSON.stringify(name)}`)
  .join("\n")};\n\nexport type CssVariableName =\n${cssVariableNames
  .map((name) => `  | ${JSON.stringify(name)}`)
  .join("\n")};\n`;

if (process.argv.includes("--check")) {
  const current = await readFile(outputUrl, "utf8").catch(() => "");
  if (current !== generated) {
    throw new Error(
      `${fileURLToPath(outputUrl)} is stale. Run pnpm generate:color-types.`
    );
  }
} else {
  await writeFile(outputUrl, generated);
}
