import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { parse } from "@terrazzo/parser";

const controllerNames = [
  "canvas",
  "ink",
  "accent",
  "positive",
  "negative",
  "warning",
  "informative",
] as const;

const sourceUrl = new URL("../../tokens/colors.resolver.json", import.meta.url);
const outputUrl = new URL("./color-controllers.generated.ts", import.meta.url);

type DtcgColor = {
  colorSpace: string;
  components: unknown[];
  alpha?: unknown;
};

const formatNumber = (value: number) => String(Number(value.toFixed(4)));

const formatColor = (value: unknown) => {
  if (
    typeof value !== "object" ||
    value === null ||
    !("colorSpace" in value) ||
    !("components" in value)
  ) {
    throw new Error("Expected a structured DTCG color value");
  }

  const color = value as DtcgColor;
  if (color.colorSpace !== "oklch" || color.components.length !== 3) {
    throw new Error("Theme controllers must use OKLCH");
  }

  const [lightness, chroma, hue] = color.components;
  if (
    typeof lightness !== "number" ||
    typeof chroma !== "number" ||
    typeof hue !== "number"
  ) {
    throw new Error("OKLCH components must be numbers");
  }

  const alpha = color.alpha ?? 1;
  if (typeof alpha !== "number") {
    throw new Error("OKLCH alpha must be a number");
  }

  const alphaSuffix = alpha === 1 ? "" : ` / ${formatNumber(alpha)}`;
  return `oklch(${formatNumber(lightness * 100)}% ${formatNumber(chroma)} ${formatNumber(hue)}${alphaSuffix})`;
};

const source = await readFile(sourceUrl, "utf8");
const { resolver } = await parse({ filename: sourceUrl, src: source });

const resolveTheme = (theme: "light" | "dark") => {
  const tokens = resolver.apply({ theme });
  const values: Record<string, string> = {};

  for (const name of controllerNames) {
    const token = tokens[`color.theme.${name}`];
    if (token === undefined) {
      throw new Error(`Missing ${theme} color controller: ${name}`);
    }
    values[`theme-${name}`] = formatColor(token.$value);
  }

  const tokenNames = Object.keys(tokens);
  if (tokenNames.length !== controllerNames.length) {
    throw new Error(
      `Expected exactly ${controllerNames.length} ${theme} color controllers, received ${tokenNames.length}`
    );
  }

  return values;
};

const formatControllerNames = () =>
  controllerNames.map((name) => `  ${JSON.stringify(name)},`).join("\n");

const formatTheme = (theme: "light" | "dark") =>
  Object.entries(resolveTheme(theme))
    .map(
      ([name, value]) => `  ${JSON.stringify(name)}: ${JSON.stringify(value)},`
    )
    .join("\n");

const generated = `// Generated by generate-color-controllers.ts. Do not edit directly.\n\nexport const colorControllerNames = [\n${formatControllerNames()}\n] as const;\n\nexport const lightColorControllers = {\n${formatTheme("light")}\n} as const;\n\nexport const darkColorControllers = {\n${formatTheme("dark")}\n} as const;\n`;

if (process.argv.includes("--check")) {
  const current = await readFile(outputUrl, "utf8").catch(() => "");
  if (current !== generated) {
    throw new Error(
      `${fileURLToPath(outputUrl)} is stale. Run pnpm generate:colors.`
    );
  }
} else {
  await writeFile(outputUrl, generated);
}
