import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { parseColorSource } from "./color-source-utils";

const sourceUrl = new URL("./colors.css", import.meta.url);
const outputUrl = new URL(
  "./__generated__/css-variable-names.d.ts",
  import.meta.url
);

const source = parseColorSource(await readFile(sourceUrl, "utf8"));
const names = Object.entries(source.semantic).flatMap(([category, colors]) =>
  Object.keys(colors).map((name) => `--${category}-${name}`)
);
const generated = `// Generated by generate-color-types.ts from colors.css. Do not edit directly.\n\nexport type CssVariableName =\n${names.map((name) => `  | ${JSON.stringify(name)}`).join("\n")};\n`;

if (process.argv.includes("--check")) {
  const current = await readFile(outputUrl, "utf8").catch(() => "");
  if (current !== generated) {
    throw new Error(
      `${fileURLToPath(outputUrl)} is stale. Run pnpm generate:color-types.`
    );
  }
} else {
  await writeFile(outputUrl, generated);
}
