import { readFile, readdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { parse } from "@babel/parser";
import {
  getCssVariableReferences,
  parseColorSource,
  validateColorContrast,
} from "./color-source-utils";

const sourceUrl = new URL("./colors.css", import.meta.url);
const outputUrl = new URL(
  "./__generated__/css-variable-names.d.ts",
  import.meta.url
);
const componentsUrl = new URL("../components/", import.meta.url);

const getSourceFiles = async (directoryUrl: URL): Promise<URL[]> => {
  const entries = await readdir(directoryUrl, { withFileTypes: true });
  const files = await Promise.all(
    entries.map((entry) => {
      const entryUrl = new URL(entry.name, directoryUrl);
      if (entry.isDirectory()) {
        return getSourceFiles(new URL(`${entry.name}/`, directoryUrl));
      }
      return entry.isFile() && /\.tsx?$/.test(entry.name) ? [entryUrl] : [];
    })
  );
  return files.flat();
};

const validateComponentUsage = async (publicNames: ReadonlySet<string>) => {
  const usedNames = new Set<string>();
  for (const fileUrl of await getSourceFiles(componentsUrl)) {
    const fileName = fileURLToPath(fileUrl);
    const code = await readFile(fileUrl, "utf8");
    const sourceFile = parse(code, {
      sourceType: "module",
      plugins: ["typescript", "jsx"],
    });
    const hasPublicCssVarImport = sourceFile.program.body.some(
      (node) =>
        node.type === "ImportDeclaration" &&
        node.source.value.endsWith("/colors/css-var")
    );

    const visit = (value: unknown) => {
      if (Array.isArray(value)) {
        for (const item of value) {
          visit(item);
        }
        return;
      }
      if (typeof value !== "object" || value === null) {
        return;
      }
      const node = value as Record<string, unknown>;
      if (
        hasPublicCssVarImport &&
        node.type === "CallExpression" &&
        typeof node.callee === "object" &&
        node.callee !== null &&
        "type" in node.callee &&
        node.callee.type === "Identifier" &&
        "name" in node.callee &&
        node.callee.name === "cssVar"
      ) {
        const name = Array.isArray(node.arguments) ? node.arguments[0] : null;
        if (
          typeof name !== "object" ||
          name === null ||
          !("type" in name) ||
          name.type !== "StringLiteral" ||
          !("value" in name) ||
          typeof name.value !== "string"
        ) {
          throw new Error(`${fileName}: cssVar() requires a literal name`);
        }
        if (publicNames.has(name.value) === false) {
          throw new Error(
            `${fileName}: unknown public CSS variable ${name.value}`
          );
        }
        usedNames.add(name.value);
      }

      let cssText: string | undefined;
      if (node.type === "StringLiteral" && typeof node.value === "string") {
        cssText = node.value;
      }
      if (node.type === "TemplateLiteral" && Array.isArray(node.quasis)) {
        cssText = node.quasis
          .map((quasi) => {
            if (
              typeof quasi !== "object" ||
              quasi === null ||
              !("value" in quasi) ||
              typeof quasi.value !== "object" ||
              quasi.value === null ||
              !("raw" in quasi.value) ||
              typeof quasi.value.raw !== "string"
            ) {
              throw new Error(`${fileName}: invalid template literal`);
            }
            return quasi.value.raw;
          })
          .join("--template-expression");
      }
      if (cssText?.includes("var(") === true) {
        for (const reference of getCssVariableReferences(cssText)) {
          if (publicNames.has(reference) === false) {
            continue;
          }
          throw new Error(
            `${fileName}: use cssVar(${JSON.stringify(reference)}) instead of a direct semantic variable reference`
          );
        }
      }
      for (const child of Object.values(node)) {
        visit(child);
      }
    };
    visit(sourceFile);
  }

  const unusedNames = [...publicNames].filter((name) => !usedNames.has(name));
  if (unusedNames.length > 0) {
    throw new Error(`Unused semantic CSS variables: ${unusedNames.join(", ")}`);
  }
};

const source = parseColorSource(await readFile(sourceUrl, "utf8"));
validateColorContrast(source);

const names = Object.entries(source.semantic).flatMap(([category, colors]) =>
  Object.keys(colors).map((name) => `--${category}-${name}`)
);
await validateComponentUsage(new Set(names));
const generated = `// Generated by generate-color-types.ts from colors.css. Do not edit directly.\n\nexport type CssVariableName =\n${names.map((name) => `  | ${JSON.stringify(name)}`).join("\n")};\n`;

if (process.argv.includes("--check")) {
  const current = await readFile(outputUrl, "utf8").catch(() => "");
  if (current !== generated) {
    throw new Error(
      `${fileURLToPath(outputUrl)} is stale. Run pnpm generate:color-types.`
    );
  }
} else {
  await writeFile(outputUrl, generated);
}
