import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { colorTokenSource } from "../../tokens/colors";
import { compileColorRecipes } from "./color-recipe-utils";

const controllerNames = Object.keys(colorTokenSource.controllers);
const controllerOutputUrl = new URL(
  "./__generated__/color-controllers.ts",
  import.meta.url
);
const recipeOutputUrl = new URL(
  "./__generated__/color-recipes.ts",
  import.meta.url
);

const formatNumber = (value: number) => String(Number(value.toFixed(4)));

const formatColor = (value: readonly [number, number, number, number?]) => {
  const [lightness, chroma, hue, alpha = 1] = value;
  if (
    Number.isFinite(lightness) === false ||
    lightness < 0 ||
    lightness > 100 ||
    Number.isFinite(chroma) === false ||
    chroma < 0 ||
    Number.isFinite(hue) === false ||
    Number.isFinite(alpha) === false ||
    alpha < 0 ||
    alpha > 1
  ) {
    throw new Error(`Invalid OKLCH controller: ${JSON.stringify(value)}`);
  }

  const alphaSuffix = alpha === 1 ? "" : ` / ${formatNumber(alpha)}`;
  return `oklch(${formatNumber(lightness)}% ${formatNumber(chroma)} ${formatNumber(hue)}${alphaSuffix})`;
};

const recipes = {
  version: colorTokenSource.version,
  semantic: colorTokenSource.semantic,
  compatibility: colorTokenSource.compatibility,
};
const compiledRecipes = compileColorRecipes({
  controllers: controllerNames,
  recipes,
});

const formatControllerNames = () =>
  controllerNames.map((name) => `  ${JSON.stringify(name)},`).join("\n");

const formatTheme = (theme: "light" | "dark") =>
  Object.entries(colorTokenSource.controllers)
    .map(([name, controller]) => {
      return `  ${name}: ${JSON.stringify(formatColor(controller[theme]))},`;
    })
    .join("\n");

const generatedControllers = `// Generated by generate-colors.ts. Do not edit directly.\n\nexport const colorControllerNames = [\n${formatControllerNames()}\n] as const;\n\nexport const lightColorControllers = {\n${formatTheme("light")}\n} as const;\n\nexport const darkColorControllers = {\n${formatTheme("dark")}\n} as const;\n`;

const formatRecipes = (values: Record<string, string>) =>
  Object.entries(values)
    .map(([name, value]) => `  ${name}: ${JSON.stringify(value)},`)
    .join("\n");

const generatedRecipes = `// Generated by generate-colors.ts. Do not edit directly.\n\n// prettier-ignore\nexport const semanticColor = {\n${formatRecipes(compiledRecipes.semantic)}\n} as const;\n\n/**\n * Compatibility names used by existing components and downstream packages.\n * New design-system code should use semanticColor directly.\n */\n// prettier-ignore\nexport const compatibilityColor = {\n${formatRecipes(compiledRecipes.compatibility)}\n} as const;\n`;

const outputs = [
  [controllerOutputUrl, generatedControllers],
  [recipeOutputUrl, generatedRecipes],
] as const;

if (process.argv.includes("--check")) {
  for (const [outputUrl, generated] of outputs) {
    const current = await readFile(outputUrl, "utf8").catch(() => "");
    if (current !== generated) {
      throw new Error(
        `${fileURLToPath(outputUrl)} is stale. Run pnpm generate:colors.`
      );
    }
  }
} else {
  await Promise.all(
    outputs.map(([outputUrl, generated]) => writeFile(outputUrl, generated))
  );
}
