import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";
// @ts-ignore - app files are provided by the defaults template
import { redirectRequest } from "../app/redirect-url";
// @todo think about how to make __generated__ typeable
// @ts-ignore
import { redirects } from "../app/__generated__/$resources.redirects";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
import * as build from "../build/server";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
const requestHandler = createPagesFunctionHandler({ build });

export const onRequest: PagesFunction = (context) => {
  const redirectResponse = redirectRequest(context.request, redirects);
  if (redirectResponse !== undefined) {
    return redirectResponse;
  }

  return requestHandler(context);
};
