const Page = () => {
  return (
    <div
      role={""}
      aria-activedescendant={""}
      aria-atomic={true}
      aria-autocomplete={"inline"}
      aria-braillelabel={""}
      aria-brailleroledescription={""}
      aria-busy={true}
      aria-checked={"false"}
      aria-colcount={0}
      aria-colindex={0}
      aria-colspan={0}
      aria-controls={""}
      aria-current={"page"}
      aria-describedby={""}
      aria-description={""}
      aria-details={""}
      aria-disabled={true}
      aria-dropeffect={"copy"}
      aria-errormessage={""}
      aria-expanded={true}
      aria-flowto={""}
      aria-grabbed={true}
      aria-haspopup={"false"}
      aria-hidden={true}
      aria-invalid={"grammar"}
      aria-keyshortcuts={""}
      aria-label={""}
      aria-labelledby={""}
      aria-level={0}
      aria-live={"assertive"}
      aria-modal={true}
      aria-multiline={true}
      aria-multiselectable={true}
      aria-orientation={"vertical"}
      aria-owns={""}
      aria-placeholder={""}
      aria-posinset={0}
      aria-pressed={"false"}
      aria-readonly={true}
      aria-relevant={"additions"}
      aria-required={true}
      aria-roledescription={""}
      aria-rowcount={0}
      aria-rowindex={0}
      aria-rowspan={0}
      aria-selected={true}
      aria-setsize={0}
      aria-sort={"ascending"}
      aria-valuemax={0}
      aria-valuemin={0}
      aria-valuenow={0}
      aria-valuetext={""}
    />
  );
};
export { Page };
