export const categoriesByTag: Record<string, string[]> = {
  a: ["flow", "phrasing", "interactive", "palpable"],
  abbr: ["flow", "phrasing", "palpable"],
  address: ["flow", "palpable"],
  area: ["flow", "phrasing"],
  article: ["flow", "sectioning", "palpable"],
  aside: ["flow", "sectioning", "palpable"],
  audio: ["flow", "phrasing", "embedded", "interactive", "palpable"],
  b: ["flow", "phrasing", "palpable"],
  base: ["metadata"],
  bdi: ["flow", "phrasing", "palpable"],
  bdo: ["flow", "phrasing", "palpable"],
  blockquote: ["flow", "palpable"],
  body: ["none"],
  br: ["flow", "phrasing"],
  button: [
    "flow",
    "phrasing",
    "interactive",
    "listed",
    "labelable",
    "submittable",
    "form-associated",
    "palpable",
  ],
  canvas: ["flow", "phrasing", "embedded", "palpable"],
  caption: ["none"],
  cite: ["flow", "phrasing", "palpable"],
  code: ["flow", "phrasing", "palpable"],
  col: ["none"],
  colgroup: ["none"],
  data: ["flow", "phrasing", "palpable"],
  datalist: ["flow", "phrasing"],
  dd: ["none"],
  del: ["flow", "phrasing", "palpable"],
  details: ["flow", "interactive", "palpable"],
  dfn: ["flow", "phrasing", "palpable"],
  dialog: ["flow"],
  div: ["flow", "palpable"],
  dl: ["flow", "palpable"],
  dt: ["none"],
  em: ["flow", "phrasing", "palpable"],
  embed: ["flow", "phrasing", "embedded", "interactive", "palpable"],
  fieldset: ["flow", "listed", "form-associated", "palpable"],
  figcaption: ["none"],
  figure: ["flow", "palpable"],
  footer: ["flow", "palpable"],
  form: ["flow", "palpable"],
  h1: ["flow", "heading", "palpable"],
  h2: ["flow", "heading", "palpable"],
  h3: ["flow", "heading", "palpable"],
  h4: ["flow", "heading", "palpable"],
  h5: ["flow", "heading", "palpable"],
  h6: ["flow", "heading", "palpable"],
  head: ["none"],
  header: ["flow", "palpable"],
  hgroup: ["flow", "palpable"],
  hr: ["flow"],
  html: ["none"],
  i: ["flow", "phrasing", "palpable"],
  iframe: ["flow", "phrasing", "embedded", "interactive", "palpable"],
  img: [
    "flow",
    "phrasing",
    "embedded",
    "interactive",
    "form-associated",
    "palpable",
  ],
  input: [
    "flow",
    "phrasing",
    "interactive",
    "listed",
    "labelable",
    "submittable",
    "resettable",
    "form-associated",
    "palpable",
  ],
  ins: ["flow", "phrasing", "palpable"],
  kbd: ["flow", "phrasing", "palpable"],
  label: ["flow", "phrasing", "interactive", "palpable"],
  legend: ["none"],
  li: ["none"],
  link: ["metadata", "flow", "phrasing"],
  main: ["flow", "palpable"],
  map: ["flow", "phrasing", "palpable"],
  mark: ["flow", "phrasing", "palpable"],
  menu: ["flow", "palpable"],
  meta: ["metadata", "flow", "phrasing"],
  meter: ["flow", "phrasing", "labelable", "palpable"],
  nav: ["flow", "sectioning", "palpable"],
  noscript: ["metadata", "flow", "phrasing"],
  object: [
    "flow",
    "phrasing",
    "embedded",
    "interactive",
    "listed",
    "form-associated",
    "palpable",
  ],
  ol: ["flow", "palpable"],
  optgroup: ["none"],
  option: ["none"],
  output: [
    "flow",
    "phrasing",
    "listed",
    "labelable",
    "resettable",
    "form-associated",
    "palpable",
  ],
  p: ["flow", "palpable"],
  picture: ["flow", "phrasing", "embedded", "palpable"],
  pre: ["flow", "palpable"],
  progress: ["flow", "phrasing", "labelable", "palpable"],
  q: ["flow", "phrasing", "palpable"],
  rp: ["none"],
  rt: ["none"],
  ruby: ["flow", "phrasing", "palpable"],
  s: ["flow", "phrasing", "palpable"],
  samp: ["flow", "phrasing", "palpable"],
  script: ["metadata", "flow", "phrasing", "script-supporting"],
  search: ["flow", "palpable"],
  section: ["flow", "sectioning", "palpable"],
  select: [
    "flow",
    "phrasing",
    "interactive",
    "listed",
    "labelable",
    "submittable",
    "resettable",
    "form-associated",
    "palpable",
  ],
  slot: ["flow", "phrasing"],
  small: ["flow", "phrasing", "palpable"],
  source: ["none"],
  span: ["flow", "phrasing", "palpable"],
  strong: ["flow", "phrasing", "palpable"],
  style: ["metadata"],
  sub: ["flow", "phrasing", "palpable"],
  summary: ["none"],
  sup: ["flow", "phrasing", "palpable"],
  table: ["flow", "palpable"],
  tbody: ["none"],
  td: ["none"],
  template: ["metadata", "flow", "phrasing", "script-supporting"],
  textarea: [
    "flow",
    "phrasing",
    "interactive",
    "listed",
    "labelable",
    "submittable",
    "resettable",
    "form-associated",
    "palpable",
  ],
  tfoot: ["none"],
  th: ["interactive"],
  thead: ["none"],
  time: ["flow", "phrasing", "palpable"],
  title: ["metadata"],
  tr: ["none"],
  track: ["none"],
  u: ["flow", "phrasing", "palpable"],
  ul: ["flow", "palpable"],
  var: ["flow", "phrasing", "palpable"],
  video: ["flow", "phrasing", "embedded", "interactive", "palpable"],
  wbr: ["flow", "phrasing"],
};
export const childrenCategoriesByTag: Record<string, string[]> = {
  a: ["transparent"],
  abbr: ["phrasing"],
  address: ["flow"],
  area: ["empty"],
  article: ["flow"],
  aside: ["flow"],
  audio: ["source", "track", "transparent"],
  b: ["phrasing"],
  base: ["empty"],
  bdi: ["phrasing"],
  bdo: ["phrasing"],
  blockquote: ["flow"],
  body: ["flow"],
  br: ["empty"],
  button: ["phrasing"],
  canvas: ["transparent"],
  caption: ["flow"],
  cite: ["phrasing"],
  code: ["phrasing"],
  col: ["empty"],
  colgroup: ["col", "template"],
  data: ["phrasing"],
  datalist: ["phrasing", "option", "script-supporting elements"],
  dd: ["flow"],
  del: ["transparent"],
  details: ["summary", "flow"],
  dfn: ["phrasing"],
  dialog: ["flow"],
  div: ["flow"],
  dl: ["dt", "dd", "div", "script-supporting elements"],
  dt: ["flow"],
  em: ["phrasing"],
  embed: ["empty"],
  fieldset: ["legend", "flow"],
  figcaption: ["flow"],
  figure: ["figcaption", "flow"],
  footer: ["flow"],
  form: ["flow"],
  h1: ["phrasing"],
  h2: ["phrasing"],
  h3: ["phrasing"],
  h4: ["phrasing"],
  h5: ["phrasing"],
  h6: ["phrasing"],
  head: ["metadata content"],
  header: ["flow"],
  hgroup: ["h1", "h2", "h3", "h4", "h5", "h6", "script-supporting elements"],
  hr: ["empty"],
  html: ["head", "body"],
  i: ["phrasing"],
  iframe: ["empty"],
  img: ["empty"],
  input: ["empty"],
  ins: ["transparent"],
  kbd: ["phrasing"],
  label: ["phrasing"],
  legend: ["phrasing", "heading content"],
  li: ["flow"],
  link: ["empty"],
  main: ["flow"],
  map: ["transparent", "area"],
  mark: ["phrasing"],
  menu: ["li", "script-supporting elements"],
  meta: ["empty"],
  meter: ["phrasing"],
  nav: ["flow"],
  noscript: ["varies"],
  object: ["transparent"],
  ol: ["li", "script-supporting elements"],
  optgroup: ["option", "script-supporting elements"],
  option: ["text"],
  output: ["phrasing"],
  p: ["phrasing"],
  picture: ["source", "one img", "script-supporting elements"],
  pre: ["phrasing"],
  progress: ["phrasing"],
  q: ["phrasing"],
  rp: ["text"],
  rt: ["phrasing"],
  ruby: ["phrasing", "rt", "rp"],
  s: ["phrasing"],
  samp: ["phrasing"],
  script: ["script, data, or script documentation"],
  search: ["flow"],
  section: ["flow"],
  select: ["option", "optgroup", "script-supporting elements"],
  slot: ["transparent"],
  small: ["phrasing"],
  source: ["empty"],
  span: ["phrasing"],
  strong: ["phrasing"],
  style: ["text"],
  sub: ["phrasing"],
  summary: ["phrasing", "heading content"],
  sup: ["phrasing"],
  table: [
    "caption",
    "colgroup",
    "thead",
    "tbody",
    "tfoot",
    "tr",
    "script-supporting elements",
  ],
  tbody: ["tr", "script-supporting elements"],
  td: ["flow"],
  template: ["empty"],
  textarea: ["text"],
  tfoot: ["tr", "script-supporting elements"],
  th: ["flow"],
  thead: ["tr", "script-supporting elements"],
  time: ["phrasing"],
  title: ["text"],
  tr: ["th", "td", "script-supporting elements"],
  track: ["empty"],
  u: ["phrasing"],
  ul: ["li", "script-supporting elements"],
  var: ["phrasing"],
  video: ["source", "track", "transparent"],
  wbr: ["empty"],
};
