type Element = {
  description: string;
  categories: string[];
  children: string[];
};

export const elementsByTag: Record<string, Element> = {
  a: {
    description: "Hyperlink",
    categories: ["html-element", "flow", "phrasing", "interactive", "palpable"],
    children: ["transparent"],
  },
  abbr: {
    description: "Abbreviation",
    categories: ["html-element", "flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  address: {
    description: "Contact information for a page or article element",
    categories: ["html-element", "flow", "palpable"],
    children: ["flow"],
  },
  area: {
    description: "Hyperlink or dead area on an image map",
    categories: ["html-element", "flow", "phrasing"],
    children: [],
  },
  article: {
    description: "Self-contained syndicatable or reusable composition",
    categories: ["html-element", "flow", "sectioning", "palpable"],
    children: ["flow"],
  },
  aside: {
    description: "Sidebar for tangentially related content",
    categories: ["html-element", "flow", "sectioning", "palpable"],
    children: ["flow"],
  },
  audio: {
    description: "Audio player",
    categories: [
      "html-element",
      "flow",
      "phrasing",
      "embedded",
      "interactive",
      "palpable",
    ],
    children: ["source", "track", "transparent"],
  },
  b: {
    description: "Keywords",
    categories: ["html-element", "flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  bdi: {
    description: "Text directionality isolation",
    categories: ["html-element", "flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  bdo: {
    description: "Text directionality formatting",
    categories: ["html-element", "flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  blockquote: {
    description: "A section quoted from another source",
    categories: ["html-element", "flow", "palpable"],
    children: ["flow"],
  },
  body: {
    description: "Document body",
    categories: ["html-element", "none"],
    children: ["flow"],
  },
  br: {
    description: "Line break, e.g. in poem or postal address",
    categories: ["html-element", "flow", "phrasing"],
    children: [],
  },
  button: {
    description: "Button control",
    categories: [
      "html-element",
      "flow",
      "phrasing",
      "interactive",
      "listed",
      "labelable",
      "submittable",
      "form-associated",
      "palpable",
    ],
    children: ["phrasing"],
  },
  canvas: {
    description: "Scriptable bitmap canvas",
    categories: ["html-element", "flow", "phrasing", "embedded", "palpable"],
    children: ["transparent"],
  },
  caption: {
    description: "Table caption",
    categories: ["html-element", "none"],
    children: ["flow"],
  },
  cite: {
    description: "Title of a work",
    categories: ["html-element", "flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  code: {
    description: "Computer code",
    categories: ["html-element", "flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  col: {
    description: "Table column",
    categories: ["html-element", "none"],
    children: [],
  },
  colgroup: {
    description: "Group of columns in a table",
    categories: ["html-element", "none"],
    children: ["col", "template"],
  },
  data: {
    description: "Machine-readable equivalent",
    categories: ["html-element", "flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  datalist: {
    description: "Container for options for combo box control",
    categories: ["html-element", "flow", "phrasing"],
    children: ["phrasing", "option", "script-supporting elements"],
  },
  dd: {
    description: "Content for corresponding dt element(s)",
    categories: ["html-element", "none"],
    children: ["flow"],
  },
  del: {
    description: "A removal from the document",
    categories: ["html-element", "flow", "phrasing", "palpable"],
    children: ["transparent"],
  },
  details: {
    description: "Disclosure control for hiding details",
    categories: ["html-element", "flow", "palpable"],
    children: ["summary", "flow"],
  },
  dfn: {
    description: "Defining instance",
    categories: ["html-element", "flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  dialog: {
    description: "Dialog box or window",
    categories: ["html-element", "flow"],
    children: ["flow"],
  },
  div: {
    description:
      "Generic flow container, or container for name-value groups in dl elements",
    categories: ["html-element", "flow", "palpable"],
    children: ["flow"],
  },
  dl: {
    description:
      "Association list consisting of zero or more name-value groups",
    categories: ["html-element", "flow", "palpable"],
    children: ["dt", "dd", "div", "script-supporting elements"],
  },
  dt: {
    description: "Legend for corresponding dd element(s)",
    categories: ["html-element", "none"],
    children: ["flow"],
  },
  em: {
    description: "Stress emphasis",
    categories: ["html-element", "flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  embed: {
    description: "Plugin",
    categories: [
      "html-element",
      "flow",
      "phrasing",
      "embedded",
      "interactive",
      "palpable",
    ],
    children: [],
  },
  fieldset: {
    description: "Group of form controls",
    categories: [
      "html-element",
      "flow",
      "listed",
      "form-associated",
      "palpable",
    ],
    children: ["legend", "flow"],
  },
  figcaption: {
    description: "Caption for figure",
    categories: ["html-element", "none"],
    children: ["flow"],
  },
  figure: {
    description: "Figure with optional caption",
    categories: ["html-element", "flow", "palpable"],
    children: ["figcaption", "flow"],
  },
  footer: {
    description: "Footer for a page or section",
    categories: ["html-element", "flow", "palpable"],
    children: ["flow"],
  },
  form: {
    description: "User-submittable form",
    categories: ["html-element", "flow", "palpable"],
    children: ["flow"],
  },
  h1: {
    description: "Heading",
    categories: ["html-element", "flow", "heading content", "palpable"],
    children: ["phrasing"],
  },
  h2: {
    description: "Heading",
    categories: ["html-element", "flow", "heading content", "palpable"],
    children: ["phrasing"],
  },
  h3: {
    description: "Heading",
    categories: ["html-element", "flow", "heading content", "palpable"],
    children: ["phrasing"],
  },
  h4: {
    description: "Heading",
    categories: ["html-element", "flow", "heading content", "palpable"],
    children: ["phrasing"],
  },
  h5: {
    description: "Heading",
    categories: ["html-element", "flow", "heading content", "palpable"],
    children: ["phrasing"],
  },
  h6: {
    description: "Heading",
    categories: ["html-element", "flow", "heading content", "palpable"],
    children: ["phrasing"],
  },
  head: {
    description: "Container for document metadata",
    categories: ["html-element", "none"],
    children: ["metadata content"],
  },
  header: {
    description: "Introductory or navigational aids for a page or section",
    categories: ["html-element", "flow", "palpable"],
    children: ["flow"],
  },
  hgroup: {
    description: "Heading container",
    categories: ["html-element", "flow", "palpable"],
    children: [
      "h1",
      "h2",
      "h3",
      "h4",
      "h5",
      "h6",
      "script-supporting elements",
      "p",
    ],
  },
  hr: {
    description: "Thematic break",
    categories: ["html-element", "flow"],
    children: [],
  },
  html: {
    description: "Root element",
    categories: ["html-element", "none"],
    children: ["head", "body"],
  },
  i: {
    description: "Alternate voice",
    categories: ["html-element", "flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  iframe: {
    description: "Child navigable",
    categories: [
      "html-element",
      "flow",
      "phrasing",
      "embedded",
      "interactive",
      "palpable",
    ],
    children: [],
  },
  img: {
    description: "Image",
    categories: [
      "html-element",
      "flow",
      "phrasing",
      "embedded",
      "interactive",
      "form-associated",
      "palpable",
    ],
    children: [],
  },
  input: {
    description: "Form control",
    categories: [
      "html-element",
      "flow",
      "phrasing",
      "interactive",
      "listed",
      "labelable",
      "submittable",
      "resettable",
      "form-associated",
      "palpable",
    ],
    children: [],
  },
  ins: {
    description: "An addition to the document",
    categories: ["html-element", "flow", "phrasing", "palpable"],
    children: ["transparent"],
  },
  kbd: {
    description: "User input",
    categories: ["html-element", "flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  label: {
    description: "Caption for a form control",
    categories: ["html-element", "flow", "phrasing", "interactive", "palpable"],
    children: ["phrasing"],
  },
  legend: {
    description: "Caption for fieldset",
    categories: ["html-element", "none"],
    children: ["phrasing", "heading content"],
  },
  li: {
    description: "List item",
    categories: ["html-element", "none"],
    children: ["flow"],
  },
  main: {
    description: "Container for the dominant contents of the document",
    categories: ["html-element", "flow", "palpable"],
    children: ["flow"],
  },
  map: {
    description: "Image map",
    categories: ["html-element", "flow", "phrasing", "palpable"],
    children: ["transparent", "area"],
  },
  mark: {
    description: "Highlight",
    categories: ["html-element", "flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  menu: {
    description: "Menu of commands",
    categories: ["html-element", "flow", "palpable"],
    children: ["li", "script-supporting elements"],
  },
  meter: {
    description: "Gauge",
    categories: ["html-element", "flow", "phrasing", "labelable", "palpable"],
    children: ["phrasing"],
  },
  nav: {
    description: "Section with navigational links",
    categories: ["html-element", "flow", "sectioning", "palpable"],
    children: ["flow"],
  },
  object: {
    description: "Image, child navigable, or plugin",
    categories: [
      "html-element",
      "flow",
      "phrasing",
      "embedded",
      "interactive",
      "listed",
      "form-associated",
      "palpable",
    ],
    children: ["transparent"],
  },
  ol: {
    description: "Ordered list",
    categories: ["html-element", "flow", "palpable"],
    children: ["li", "script-supporting elements"],
  },
  optgroup: {
    description: "Group of options in a list box",
    categories: ["html-element", "none"],
    children: ["option", "script-supporting elements"],
  },
  option: {
    description: "Option in a list box or combo box control",
    categories: ["html-element", "none"],
    children: ["text"],
  },
  output: {
    description: "Calculated output value",
    categories: [
      "html-element",
      "flow",
      "phrasing",
      "listed",
      "labelable",
      "resettable",
      "form-associated",
      "palpable",
    ],
    children: ["phrasing"],
  },
  p: {
    description: "Paragraph",
    categories: ["html-element", "flow", "palpable"],
    children: ["phrasing"],
  },
  picture: {
    description: "Image",
    categories: ["html-element", "flow", "phrasing", "embedded", "palpable"],
    children: ["source", "one img", "script-supporting elements"],
  },
  pre: {
    description: "Block of preformatted text",
    categories: ["html-element", "flow", "palpable"],
    children: ["phrasing"],
  },
  progress: {
    description: "Progress bar",
    categories: ["html-element", "flow", "phrasing", "labelable", "palpable"],
    children: ["phrasing"],
  },
  q: {
    description: "Quotation",
    categories: ["html-element", "flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  rp: {
    description: "Parenthesis for ruby annotation text",
    categories: ["html-element", "none"],
    children: ["text"],
  },
  rt: {
    description: "Ruby annotation text",
    categories: ["html-element", "none"],
    children: ["phrasing"],
  },
  ruby: {
    description: "Ruby annotation(s)",
    categories: ["html-element", "flow", "phrasing", "palpable"],
    children: ["phrasing", "rt", "rp"],
  },
  s: {
    description: "Inaccurate text",
    categories: ["html-element", "flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  samp: {
    description: "Computer output",
    categories: ["html-element", "flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  search: {
    description: "Container for search controls",
    categories: ["html-element", "flow", "palpable"],
    children: ["flow"],
  },
  section: {
    description: "Generic document or application section",
    categories: ["html-element", "flow", "sectioning", "palpable"],
    children: ["flow"],
  },
  select: {
    description: "List box control",
    categories: [
      "html-element",
      "flow",
      "phrasing",
      "interactive",
      "listed",
      "labelable",
      "submittable",
      "resettable",
      "form-associated",
      "palpable",
    ],
    children: ["option", "optgroup", "script-supporting elements"],
  },
  slot: {
    description: "Shadow tree slot",
    categories: ["html-element", "flow", "phrasing"],
    children: ["transparent"],
  },
  small: {
    description: "Side comment",
    categories: ["html-element", "flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  source: {
    description: "Image source for img or media source for video or audio",
    categories: ["html-element", "none"],
    children: [],
  },
  span: {
    description: "Generic phrasing container",
    categories: ["html-element", "flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  strong: {
    description: "Importance",
    categories: ["html-element", "flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  sub: {
    description: "Subscript",
    categories: ["html-element", "flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  summary: {
    description: "Caption for details",
    categories: ["html-element", "none", "interactive"],
    children: ["phrasing", "heading content"],
  },
  sup: {
    description: "Superscript",
    categories: ["html-element", "flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  table: {
    description: "Table",
    categories: ["html-element", "flow", "palpable"],
    children: [
      "caption",
      "colgroup",
      "thead",
      "tbody",
      "tfoot",
      "tr",
      "script-supporting elements",
    ],
  },
  tbody: {
    description: "Group of rows in a table",
    categories: ["html-element", "none"],
    children: ["tr", "script-supporting elements"],
  },
  td: {
    description: "Table cell",
    categories: ["html-element", "none"],
    children: ["flow"],
  },
  textarea: {
    description: "Multiline text controls",
    categories: [
      "html-element",
      "flow",
      "phrasing",
      "interactive",
      "listed",
      "labelable",
      "submittable",
      "resettable",
      "form-associated",
      "palpable",
    ],
    children: [],
  },
  tfoot: {
    description: "Group of footer rows in a table",
    categories: ["html-element", "none"],
    children: ["tr", "script-supporting elements"],
  },
  th: {
    description: "Table header cell",
    categories: ["html-element", "interactive"],
    children: ["flow"],
  },
  thead: {
    description: "Group of heading rows in a table",
    categories: ["html-element", "none"],
    children: ["tr", "script-supporting elements"],
  },
  time: {
    description: "Machine-readable equivalent of date- or time-related data",
    categories: ["html-element", "flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  tr: {
    description: "Table row",
    categories: ["html-element", "none"],
    children: ["th", "td", "script-supporting elements"],
  },
  track: {
    description: "Timed text track",
    categories: ["html-element", "none"],
    children: [],
  },
  u: {
    description: "Unarticulated annotation",
    categories: ["html-element", "flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  ul: {
    description: "List",
    categories: ["html-element", "flow", "palpable"],
    children: ["li", "script-supporting elements"],
  },
  var: {
    description: "Variable",
    categories: ["html-element", "flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  video: {
    description: "Video player",
    categories: [
      "html-element",
      "flow",
      "phrasing",
      "embedded",
      "interactive",
      "palpable",
    ],
    children: ["source", "track", "transparent"],
  },
  wbr: {
    description: "Line breaking opportunity",
    categories: ["html-element", "flow", "phrasing"],
    children: [],
  },
  svg: {
    description: "",
    categories: ["html-element", "flow", "phrasing"],
    children: [
      "animate",
      "animateColor",
      "animateMotion",
      "animateTransform",
      "set",
      "desc",
      "metadata",
      "title",
      "circle",
      "ellipse",
      "line",
      "path",
      "polygon",
      "polyline",
      "rect",
      "defs",
      "g",
      "svg",
      "symbol",
      "use",
      "linearGradient",
      "radialGradient",
      "a",
      "altGlyphDef",
      "clipPath",
      "color-profile",
      "cursor",
      "filter",
      "font",
      "font-face",
      "foreignObject",
      "image",
      "marker",
      "mask",
      "pattern",
      "script",
      "style",
      "switch",
      "text",
      "view",
    ],
  },
  g: {
    description: "",
    categories: ["svg-element", "none"],
    children: [
      "animate",
      "animateColor",
      "animateMotion",
      "animateTransform",
      "set",
      "desc",
      "metadata",
      "title",
      "circle",
      "ellipse",
      "line",
      "path",
      "polygon",
      "polyline",
      "rect",
      "defs",
      "g",
      "svg",
      "symbol",
      "use",
      "linearGradient",
      "radialGradient",
      "a",
      "altGlyphDef",
      "clipPath",
      "color-profile",
      "cursor",
      "filter",
      "font",
      "font-face",
      "foreignObject",
      "image",
      "marker",
      "mask",
      "pattern",
      "script",
      "style",
      "switch",
      "text",
      "view",
    ],
  },
  defs: {
    description: "",
    categories: ["svg-element", "none"],
    children: [
      "animate",
      "animateColor",
      "animateMotion",
      "animateTransform",
      "set",
      "desc",
      "metadata",
      "title",
      "circle",
      "ellipse",
      "line",
      "path",
      "polygon",
      "polyline",
      "rect",
      "defs",
      "g",
      "svg",
      "symbol",
      "use",
      "linearGradient",
      "radialGradient",
      "a",
      "altGlyphDef",
      "clipPath",
      "color-profile",
      "cursor",
      "filter",
      "font",
      "font-face",
      "foreignObject",
      "image",
      "marker",
      "mask",
      "pattern",
      "script",
      "style",
      "switch",
      "text",
      "view",
    ],
  },
  desc: {
    description: "",
    categories: ["svg-element", "none"],
    children: [],
  },
  symbol: {
    description: "",
    categories: ["svg-element", "none"],
    children: [
      "animate",
      "animateColor",
      "animateMotion",
      "animateTransform",
      "set",
      "desc",
      "metadata",
      "title",
      "circle",
      "ellipse",
      "line",
      "path",
      "polygon",
      "polyline",
      "rect",
      "defs",
      "g",
      "svg",
      "symbol",
      "use",
      "linearGradient",
      "radialGradient",
      "a",
      "altGlyphDef",
      "clipPath",
      "color-profile",
      "cursor",
      "filter",
      "font",
      "font-face",
      "foreignObject",
      "image",
      "marker",
      "mask",
      "pattern",
      "script",
      "style",
      "switch",
      "text",
      "view",
    ],
  },
  use: {
    description: "",
    categories: ["svg-element", "none"],
    children: [
      "animate",
      "animateColor",
      "animateMotion",
      "animateTransform",
      "set",
      "desc",
      "metadata",
      "title",
    ],
  },
  image: {
    description: "",
    categories: ["svg-element", "none"],
    children: [
      "animate",
      "animateColor",
      "animateMotion",
      "animateTransform",
      "set",
      "desc",
      "metadata",
      "title",
    ],
  },
  switch: {
    description: "",
    categories: ["svg-element", "none"],
    children: [
      "animate",
      "animateColor",
      "animateMotion",
      "animateTransform",
      "set",
      "desc",
      "metadata",
      "title",
      "circle",
      "ellipse",
      "line",
      "path",
      "polygon",
      "polyline",
      "rect",
      "a",
      "foreignObject",
      "g",
      "image",
      "svg",
      "switch",
      "text",
      "use",
    ],
  },
  path: {
    description: "",
    categories: ["svg-element", "none"],
    children: [
      "animate",
      "animateColor",
      "animateMotion",
      "animateTransform",
      "set",
      "desc",
      "metadata",
      "title",
    ],
  },
  rect: {
    description: "",
    categories: ["svg-element", "none"],
    children: [
      "animate",
      "animateColor",
      "animateMotion",
      "animateTransform",
      "set",
      "desc",
      "metadata",
      "title",
    ],
  },
  circle: {
    description: "",
    categories: ["svg-element", "none"],
    children: [
      "animate",
      "animateColor",
      "animateMotion",
      "animateTransform",
      "set",
      "desc",
      "metadata",
      "title",
    ],
  },
  ellipse: {
    description: "",
    categories: ["svg-element", "none"],
    children: [
      "animate",
      "animateColor",
      "animateMotion",
      "animateTransform",
      "set",
      "desc",
      "metadata",
      "title",
    ],
  },
  line: {
    description: "",
    categories: ["svg-element", "none"],
    children: [
      "animate",
      "animateColor",
      "animateMotion",
      "animateTransform",
      "set",
      "desc",
      "metadata",
      "title",
    ],
  },
  polyline: {
    description: "",
    categories: ["svg-element", "none"],
    children: [
      "animate",
      "animateColor",
      "animateMotion",
      "animateTransform",
      "set",
      "desc",
      "metadata",
      "title",
    ],
  },
  polygon: {
    description: "",
    categories: ["svg-element", "none"],
    children: [
      "animate",
      "animateColor",
      "animateMotion",
      "animateTransform",
      "set",
      "desc",
      "metadata",
      "title",
    ],
  },
  text: {
    description: "",
    categories: ["svg-element", "none"],
    children: [
      "animate",
      "animateColor",
      "animateMotion",
      "animateTransform",
      "set",
      "desc",
      "metadata",
      "title",
      "altGlyph",
      "textPath",
      "tref",
      "tspan",
      "a",
    ],
  },
  tspan: {
    description: "",
    categories: ["svg-element", "none"],
    children: [
      "desc",
      "metadata",
      "title",
      "a",
      "altGlyph",
      "animate",
      "animateColor",
      "set",
      "tref",
      "tspan",
    ],
  },
  textPath: {
    description: "",
    categories: ["svg-element", "none"],
    children: [
      "desc",
      "metadata",
      "title",
      "a",
      "altGlyph",
      "animate",
      "animateColor",
      "set",
      "tref",
      "tspan",
    ],
  },
  marker: {
    description: "",
    categories: ["svg-element", "none"],
    children: [
      "animate",
      "animateColor",
      "animateMotion",
      "animateTransform",
      "set",
      "desc",
      "metadata",
      "title",
      "circle",
      "ellipse",
      "line",
      "path",
      "polygon",
      "polyline",
      "rect",
      "defs",
      "g",
      "svg",
      "symbol",
      "use",
      "linearGradient",
      "radialGradient",
      "a",
      "altGlyphDef",
      "clipPath",
      "color-profile",
      "cursor",
      "filter",
      "font",
      "font-face",
      "foreignObject",
      "image",
      "marker",
      "mask",
      "pattern",
      "script",
      "style",
      "switch",
      "text",
      "view",
    ],
  },
  linearGradient: {
    description: "",
    categories: ["svg-element", "none"],
    children: [
      "desc",
      "metadata",
      "title",
      "animate",
      "animateTransform",
      "set",
      "stop",
    ],
  },
  radialGradient: {
    description: "",
    categories: ["svg-element", "none"],
    children: [
      "desc",
      "metadata",
      "title",
      "animate",
      "animateTransform",
      "set",
      "stop",
    ],
  },
  stop: {
    description: "",
    categories: ["svg-element", "none"],
    children: ["animate", "animateColor", "set"],
  },
  pattern: {
    description: "",
    categories: ["svg-element", "none"],
    children: [
      "animate",
      "animateColor",
      "animateMotion",
      "animateTransform",
      "set",
      "desc",
      "metadata",
      "title",
      "circle",
      "ellipse",
      "line",
      "path",
      "polygon",
      "polyline",
      "rect",
      "defs",
      "g",
      "svg",
      "symbol",
      "use",
      "linearGradient",
      "radialGradient",
      "a",
      "altGlyphDef",
      "clipPath",
      "color-profile",
      "cursor",
      "filter",
      "font",
      "font-face",
      "foreignObject",
      "image",
      "marker",
      "mask",
      "pattern",
      "script",
      "style",
      "switch",
      "text",
      "view",
    ],
  },
  clipPath: {
    description: "",
    categories: ["svg-element", "none"],
    children: [
      "desc",
      "metadata",
      "title",
      "animate",
      "animateColor",
      "animateMotion",
      "animateTransform",
      "set",
      "circle",
      "ellipse",
      "line",
      "path",
      "polygon",
      "polyline",
      "rect",
      "text",
      "use",
    ],
  },
  mask: {
    description: "",
    categories: ["svg-element", "none"],
    children: [
      "animate",
      "animateColor",
      "animateMotion",
      "animateTransform",
      "set",
      "desc",
      "metadata",
      "title",
      "circle",
      "ellipse",
      "line",
      "path",
      "polygon",
      "polyline",
      "rect",
      "defs",
      "g",
      "svg",
      "symbol",
      "use",
      "linearGradient",
      "radialGradient",
      "a",
      "altGlyphDef",
      "clipPath",
      "color-profile",
      "cursor",
      "filter",
      "font",
      "font-face",
      "foreignObject",
      "image",
      "marker",
      "mask",
      "pattern",
      "script",
      "style",
      "switch",
      "text",
      "view",
    ],
  },
  filter: {
    description: "",
    categories: ["svg-element", "none"],
    children: [
      "desc",
      "metadata",
      "title",
      "feBlend",
      "feColorMatrix",
      "feComponentTransfer",
      "feComposite",
      "feConvolveMatrix",
      "feDiffuseLighting",
      "feDisplacementMap",
      "feFlood",
      "feGaussianBlur",
      "feImage",
      "feMerge",
      "feMorphology",
      "feOffset",
      "feSpecularLighting",
      "feTile",
      "feTurbulence",
      "animate",
      "set",
    ],
  },
  feDistantLight: {
    description: "",
    categories: ["svg-element", "none"],
    children: ["animate", "set"],
  },
  fePointLight: {
    description: "",
    categories: ["svg-element", "none"],
    children: ["animate", "set"],
  },
  feSpotLight: {
    description: "",
    categories: ["svg-element", "none"],
    children: ["animate", "set"],
  },
  feBlend: {
    description: "",
    categories: ["svg-element", "none"],
    children: ["animate", "set"],
  },
  feColorMatrix: {
    description: "",
    categories: ["svg-element", "none"],
    children: ["animate", "set"],
  },
  feComponentTransfer: {
    description: "",
    categories: ["svg-element", "none"],
    children: ["feFuncA", "feFuncB", "feFuncG", "feFuncR"],
  },
  feFuncR: {
    description: "",
    categories: ["svg-element", "none"],
    children: ["animate", "set"],
  },
  feFuncG: {
    description: "",
    categories: ["svg-element", "none"],
    children: ["animate", "set"],
  },
  feFuncB: {
    description: "",
    categories: ["svg-element", "none"],
    children: ["animate", "set"],
  },
  feFuncA: {
    description: "",
    categories: ["svg-element", "none"],
    children: ["animate", "set"],
  },
  feComposite: {
    description: "",
    categories: ["svg-element", "none"],
    children: ["animate", "set"],
  },
  feConvolveMatrix: {
    description: "",
    categories: ["svg-element", "none"],
    children: ["animate", "set"],
  },
  feDiffuseLighting: {
    description: "",
    categories: ["svg-element", "none"],
    children: [],
  },
  feDisplacementMap: {
    description: "",
    categories: ["svg-element", "none"],
    children: ["animate", "set"],
  },
  feFlood: {
    description: "",
    categories: ["svg-element", "none"],
    children: ["animate", "animateColor", "set"],
  },
  feGaussianBlur: {
    description: "",
    categories: ["svg-element", "none"],
    children: ["animate", "set"],
  },
  feImage: {
    description: "",
    categories: ["svg-element", "none"],
    children: ["animate", "animateTransform", "set"],
  },
  feMerge: {
    description: "",
    categories: ["svg-element", "none"],
    children: ["feMergeNode"],
  },
  feMergeNode: {
    description: "",
    categories: ["svg-element", "none"],
    children: ["animate", "set"],
  },
  feMorphology: {
    description: "",
    categories: ["svg-element", "none"],
    children: ["animate", "set"],
  },
  feOffset: {
    description: "",
    categories: ["svg-element", "none"],
    children: ["animate", "set"],
  },
  feSpecularLighting: {
    description: "",
    categories: ["svg-element", "none"],
    children: [],
  },
  feTile: {
    description: "",
    categories: ["svg-element", "none"],
    children: ["animate", "set"],
  },
  feTurbulence: {
    description: "",
    categories: ["svg-element", "none"],
    children: ["animate", "set"],
  },
  view: {
    description: "",
    categories: ["svg-element", "none"],
    children: ["desc", "metadata", "title"],
  },
  animate: {
    description: "",
    categories: ["svg-element", "none"],
    children: ["desc", "metadata", "title"],
  },
  set: {
    description: "",
    categories: ["svg-element", "none"],
    children: ["desc", "metadata", "title"],
  },
  animateMotion: {
    description: "",
    categories: ["svg-element", "none"],
    children: ["mpath"],
  },
  mpath: {
    description: "",
    categories: ["svg-element", "none"],
    children: ["desc", "metadata", "title"],
  },
  animateTransform: {
    description: "",
    categories: ["svg-element", "none"],
    children: ["desc", "metadata", "title"],
  },
  metadata: {
    description: "",
    categories: ["svg-element", "none"],
    children: [],
  },
  foreignObject: {
    description: "",
    categories: ["svg-element", "none"],
    children: [],
  },
};
