import {
  $,
  ActionValue,
  AssetValue,
  PageValue,
  Parameter,
  PlaceholderValue,
  ResourceValue,
  Variable,
  createProxy,
  css,
  expression,
  token,
  ws,
} from "@webstudio-is/template";

const componentBindings = {
  $,
  ws,
  radix: createProxy("@webstudio-is/sdk-components-react-radix:"),
  animation: createProxy("@webstudio-is/sdk-components-animation:"),
};

const helperBindings = {
  css,
  token,
  expression,
  Variable,
  Parameter,
  ResourceValue,
  ActionValue,
  AssetValue,
  PageValue,
  PlaceholderValue,
};

export const webstudioJsxRuntimeBindings = {
  ...componentBindings,
  ...helperBindings,
};

export const webstudioJsxComponentNamespaces = new Set(
  Object.keys(componentBindings)
);

const listFormatter = new Intl.ListFormat("en", {
  style: "long",
  type: "conjunction",
});

export const webstudioJsxFragmentBuiltInHelpers = listFormatter.format(
  Object.keys(webstudioJsxRuntimeBindings)
);

export const webstudioJsxFragmentInputDescription =
  `Webstudio JSX fragment. Use ${webstudioJsxFragmentBuiltInHelpers} helpers. ` +
  'Do not access host globals or dynamic code APIs such as process, globalThis, eval, Function, or constructor. Use Webstudio prop names such as class and for, not React aliases className or htmlFor. Use ws:style={css`...`} for Webstudio-native styles, or style={{ padding: 24 }} for React-style object syntax that is converted into editable Webstudio styles. Use Webstudio actions such as onClick={new ActionValue(["event"], expression`console.log(event)`)}; do not pass JavaScript functions such as onClick={() => ...}. Plain prop values must be JSON-compatible: use null, strings, booleans, finite numbers, arrays, and plain objects; do not pass undefined, Symbol, BigInt, NaN, Infinity, Date, Map, Set, class instances, or circular objects. Template-backed components used in JSX must include required child/part components explicitly under the same parent structure as the template; use insert-component when you want Webstudio to apply one registered component template automatically. Do not set ws:id; ids are generated by the runtime. The JSX is converted locally before the mutation request is sent.';
