name: Publish Any Commit
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install --ignore-scripts
      - run: pnpm --filter="webstudio..." build
      - run: pnpm --filter="webstudio..." dts

      - run: pnpx pkg-pr-new publish --compact "./packages/*"
