// Generated by transform-figma-tokens.ts from ./src/__generated__/figma-design-tokens.json

export const boxShadow = {
  menuDropShadow: "0px 5px 17px 0px #00000026, 0px 2px 7px 0px #0000001a",
  brandElevationSmall: "0px 4px 4px 0px #1717171a",
  brandElevationBig: "0px 8px 16px 0px #1717171a",
} as const;

export const fontFamilies = {
  inter:
    "Inter Variable, InterVariable, Inter, -apple-system, system-ui, sans-serif",
  manrope: "Manrope Variable, ManropeVariable, Manrope, sans-serif",
  robotoMono: "Roboto Mono, RobotoMono, menlo, monospace",
} as const;

export const lineHeights = {
  "0": "8px",
  "1": "10px",
  "2": "11px",
  "3": "12px",
  "4": "16px",
  "5": "22px",
  "6": "27px",
  "7": "39px",
  "8": "58px",
  "9": "360px",
} as const;

export const fontWeights = {
  inter0: 400,
  inter1: 500,
  inter2: 600,
  inter3: 700,
  robotoMono4: 400,
  manrope5: 200,
  manrope6: 400,
  manrope7: 700,
  manrope8: 800,
} as const;

export const fontSizes = {
  fontSize0: "8px",
  fontSize1: "10px",
  fontSize2: "12px",
  fontSize3: "16px",
  fontSize4: "20px",
  fontSize5: "32px",
  fontSize6: "48px",
  fontSize7: "360px",
} as const;

export const letterSpacing = {
  "0": "-0.05em",
  "1": "-0.02em",
  "2": "0em",
  "3": "0.005em",
  "4": "0.01em",
} as const;

export const paragraphSpacing = { "0": 0 } as const;

export const typography = {
  regular: {
    fontFamily:
      "Inter Variable, InterVariable, Inter, -apple-system, system-ui, sans-serif",
    fontWeight: 400,
    fontSize: "12px",
    lineHeight: "16px",
    letterSpacing: "0.005em",
  },
  labelTitleCase: {
    fontFamily:
      "Inter Variable, InterVariable, Inter, -apple-system, system-ui, sans-serif",
    fontWeight: 500,
    fontSize: "12px",
    lineHeight: "16px",
    letterSpacing: "0.005em",
  },
  labelSentenceCase: {
    fontFamily:
      "Inter Variable, InterVariable, Inter, -apple-system, system-ui, sans-serif",
    fontWeight: 500,
    fontSize: "12px",
    lineHeight: "16px",
    letterSpacing: "0.005em",
  },
  title: {
    fontFamily:
      "Inter Variable, InterVariable, Inter, -apple-system, system-ui, sans-serif",
    fontWeight: 700,
    fontSize: "12px",
    lineHeight: "16px",
    letterSpacing: "0.01em",
  },
  small: {
    fontFamily:
      "Inter Variable, InterVariable, Inter, -apple-system, system-ui, sans-serif",
    fontWeight: 400,
    fontSize: "10px",
    lineHeight: "11px",
    letterSpacing: "0.01em",
  },
  tiny: {
    fontFamily:
      "Inter Variable, InterVariable, Inter, -apple-system, system-ui, sans-serif",
    fontWeight: 500,
    fontSize: "8px",
    lineHeight: "8px",
    letterSpacing: "0.01em",
  },
  unit: {
    fontFamily:
      "Inter Variable, InterVariable, Inter, -apple-system, system-ui, sans-serif",
    fontWeight: 500,
    fontSize: "10px",
    lineHeight: "12px",
    letterSpacing: "0em",
  },
  mono: {
    fontFamily: "Roboto Mono, RobotoMono, menlo, monospace",
    fontWeight: 400,
    fontSize: "12px",
    lineHeight: "16px",
    letterSpacing: "0.01em",
  },
  bigTitle: {
    fontFamily:
      "Inter Variable, InterVariable, Inter, -apple-system, system-ui, sans-serif",
    fontWeight: 500,
    fontSize: "32px",
    lineHeight: "39px",
    letterSpacing: "0.005em",
  },
  spaceSectionUnitText: {
    fontFamily:
      "Inter Variable, InterVariable, Inter, -apple-system, system-ui, sans-serif",
    fontWeight: 600,
    fontSize: "8px",
    lineHeight: "8px",
    letterSpacing: "0.01em",
  },
  spaceSectionValueText: {
    fontFamily:
      "Inter Variable, InterVariable, Inter, -apple-system, system-ui, sans-serif",
    fontWeight: 500,
    fontSize: "10px",
    lineHeight: "10px",
    letterSpacing: "0.01em",
  },
  brandSectionTitle: {
    fontFamily: "Manrope Variable, ManropeVariable, Manrope, sans-serif",
    fontWeight: 700,
    fontSize: "20px",
    lineHeight: "27px",
    letterSpacing: "0em",
  },
  brandLargeTitle: {
    fontFamily: "Manrope Variable, ManropeVariable, Manrope, sans-serif",
    fontWeight: 700,
    fontSize: "48px",
    lineHeight: "58px",
    letterSpacing: "-0.02em",
  },
  brandRegular: {
    fontFamily: "Manrope Variable, ManropeVariable, Manrope, sans-serif",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "22px",
    letterSpacing: "0em",
  },
  brandThumbnailLargeDefault: {
    fontFamily: "Manrope Variable, ManropeVariable, Manrope, sans-serif",
    fontWeight: 200,
    fontSize: "360px",
    lineHeight: "360px",
    letterSpacing: "-0.05em",
  },
  brandThumbnailLargeHover: {
    fontFamily: "Manrope Variable, ManropeVariable, Manrope, sans-serif",
    fontWeight: 800,
    fontSize: "360px",
    lineHeight: "360px",
    letterSpacing: "-0.05em",
  },
  brandThumbnailSmallDefault: {
    fontFamily: "Manrope Variable, ManropeVariable, Manrope, sans-serif",
    fontWeight: 400,
    fontSize: "48px",
    lineHeight: "58px",
    letterSpacing: "-0.02em",
  },
  brandThumbnailSmallHover: {
    fontFamily: "Manrope Variable, ManropeVariable, Manrope, sans-serif",
    fontWeight: 800,
    fontSize: "48px",
    lineHeight: "58px",
    letterSpacing: "-0.02em",
  },
} as const;

export const textCase = {
  none: "none",
  uppercase: "uppercase",
  capitalize: "capitalize",
} as const;

export const textDecoration = { none: "none" } as const;

export const borderRadius = {
  radius0: "1px",
  radius1: "2px",
  radius2: "3px",
  radius3: "4px",
  radius4: "5px",
  radius5: "6px",
} as const;

export const color = {
  white: "#ffffff",
  black: "#000000",
  backgroundPanel: "#f8f8f8",
  backgroundPrimary: "#0175dc",
  backgroundHover: "#dfe3e6",
  backgroundActive: "#0175dc",
  backgroundMenu: "#ededed",
  backgroundControls: "#ffffff",
  backgroundAssetcardHover: "#e6e8eb",
  backgroundNeutralMain: "#d7dbdf",
  backgroundNeutralAccent: "#11181c",
  backgroundNeutralNotification: "#ffffff",
  backgroundNeutralDark: "#7e868c",
  backgroundDestructiveMain: "#de3339",
  backgroundDestructiveNotification: "#d53f45",
  backgroundSuccessMain: "#00894a",
  backgroundSuccessNotification: "#e9f9ee",
  backgroundAlertMain: "#f5d90a",
  backgroundAlertNotification: "#fffbd1",
  backgroundInfoMain: "#0175dc",
  backgroundInfoNotification: "#edf6ff",
  backgroundPresetMain: "#e6e8eb",
  backgroundPresetHover: "#dfe3e6",
  backgroundSetMain: "#e1f0ff",
  backgroundSetHover: "#cee7fe",
  backgroundInheritedMain: "#ffe8d7",
  backgroundInheritedHover: "#ffdcc3",
  backgroundInputSelected: "#b7d9f8",
  backgroundInputDisabled: "#f8f8f8",
  backgroundButtonHover: "#ffffff17",
  backgroundButtonPressed: "#0000001c",
  backgroundButtonDisabled: "#dfe3e6",
  backgroundItemCurrent: "#0175dc",
  backgroundItemCurrentChild: "#e1f0ff",
  backgroundItemCurrentHidden: "#7e868c",
  backgroundItemMenuItemHover: "#d3d3d3",
  backgroundTooltipMain: "#11181c",
  backgroundTooltipDesigner: "#ffffff",
  backgroundSpacingTopBottom: "#f1f3f5",
  backgroundSpacingLeftRight: "#eceef0",
  backgroundSpacingHover: "#d7dbdf",
  backgroundStyleSourceToken: "#0175dc",
  backgroundStyleSourceTag: "#d23197",
  backgroundStyleSourceState: "#00894a",
  backgroundStyleSourceNeutral: "#687076",
  backgroundStyleSourceDisabled: "#9da2a6",
  backgroundStyleSourceGradientToken:
    "linear-gradient(90deg, #0175dc00 0%, #0175dc 31.87%)",
  backgroundStyleSourceGradientTag:
    "linear-gradient(90deg, #d2319700 0%, #d23197 31.87%)",
  backgroundStyleSourceGradientState:
    "linear-gradient(90deg, #00894a00 0%, #00894a 31.87%)",
  backgroundCanvas: "#c7c7c7",
  brandBackgroundProjectCardFront:
    "linear-gradient(0deg, #fbf8ff 0%, #e2e2e2 100%)",
  brandBackgroundProjectCardBack:
    "linear-gradient(0deg, #fbf8ff 0%, #c7c7c7 100%)",
  brandBackgroundProjectCardTextArea: "#ffffff",
  brandBackgroundPublishedMain: "#39fbbb",
  brandBackgroundGradient: "linear-gradient(180deg, #e63cfe 0%, #ffae3c 100%)",
  brandBackgroundPublishedContrast: "#ebfffc",
  brandBackgroundDashboard: "#ededed",
  brandForegroundPublished: "#00894a",
  brandBorderPublished: "#ebfffc",
  borderMain: "#c1c8cd",
  borderFocus: "#0175dc",
  borderMenuInner: "#fcfcfc",
  borderColorSwatch: "#687076",
  borderNeutral: "#e8e8e8",
  borderSuccess: "#00894a",
  borderAlert: "#e2c802",
  borderInfo: "#0175dc",
  borderContrast: "#ffffff",
  borderItemChildLine: "#889096",
  borderItemChildLineCurrent: "#96c7f2",
  borderSetMain: "#b7d9f8",
  borderSetFlexUi: "#0175dc",
  borderInheritedMain: "#ffcca7",
  borderInheritedFlexUi: "#fa934e",
  borderDestructiveMain: "#de3339",
  borderDestructiveNotification: "#f9c6c6",
  foregroundMain: "#11181c",
  foregroundSubtle: "#707375",
  foregroundCategoryLabel: "#889096",
  foregroundTextSubtle: "#687076",
  foregroundDestructive: "#de3339",
  foregroundSuccess: "#00894a",
  foregroundInfo: "#0175dc",
  foregroundDisabled: "#c1c8cd",
  foregroundHiddenItem: "#7e868c",
  foregroundFlexUiMain: "#c7c7c7",
  foregroundFlexUiHover: "#96c7f2",
  foregroundContrastMain: "#ffffff",
  foregroundContrastSubtle: "#c1c8cd",
  foregroundSetMain: "#016ccc",
  foregroundSetFlexUi: "#0d84ed",
  foregroundInheritedMain: "#b74900",
  foregroundInheritedFlexUi: "#fa934e",
  maintenanceLight: "#ededed",
  maintenanceMedium: "#c7c7c7",
  maintenanceDark: "#858585",
  maintenanceSpacerViz: "#f9c6c6",
} as const;

export const borderWidth = {
  borderWidth0: 1,
  borderWidth1: 2,
  regularIconBorder0: 1,
  regularIconBorder1: 1.3,
  regularIconBorder2: 1.6,
  largeIconBorder1: 1.5,
  largeIconBorder2: 1.8,
} as const;

export const dimension = { paragraphIndent0: "0px" } as const;

export const other = { tokenSetOrder0: "global" } as const;
