// Generated by transform-figma-tokens.ts from ./src/__generated__/figma-design-tokens.json

export const boxShadow = {
  menuDropShadow: "0px 5px 17px 0px #00000026, 0px 2px 7px 0px #0000001a",
  brandElevationSmall: "0px 4px 4px 0px #1717171a",
  brandElevationBig: "0px 8px 16px 0px #1717171a",
  brandInnerGlow0: "inset 0px 2px 1px 0px #fbf8ff",
  brandInnerGlow1: "inset 0px 5px 3px 0px #fbf8ff",
  brandInnerGlow2: "inset 0px 8px 5px 0px #fbf8ff",
} as const;

export const fontFamilies = {
  inter: "Inter",
  manrope: "Manrope",
  robotoMono: "Roboto Mono",
} as const;

export const lineHeights = {
  "0": 8,
  "1": 10,
  "2": 11,
  "3": 12,
  "4": 16,
  "5": 22,
  "6": 27,
  "7": 39,
  "8": 58,
} as const;

export const fontWeights = {
  inter0: "Regular",
  inter1: "Medium",
  inter2: "Bold",
  inter4: "Semi Bold",
  manrope5: "Bold",
  robotoMono3: "Regular",
  manrope6: "Regular",
} as const;

export const fontSizes = {
  fontSize0: 8,
  fontSize1: 10,
  fontSize2: 12,
  fontSize3: 16,
  fontSize4: 20,
  fontSize5: 32,
  fontSize6: 48,
} as const;

export const letterSpacing = {
  "0": "-2%",
  "1": "0%",
  "2": "0.5%",
  "3": "1%",
} as const;

export const paragraphSpacing = { "0": 0 } as const;

export const typography = {
  regular: {
    fontFamily: "InterVariable, Inter, -apple-system, system-ui, sans-serif",
    fontWeight: 400,
    fontSize: "12px",
    lineHeight: "16px",
    letterSpacing: "0.005em",
  },
  labelsTitleCase: {
    fontFamily: "InterVariable, Inter, -apple-system, system-ui, sans-serif",
    fontWeight: 500,
    fontSize: "12px",
    lineHeight: "16px",
    letterSpacing: "0.005em",
  },
  labelsSentenceCase: {
    fontFamily: "InterVariable, Inter, -apple-system, system-ui, sans-serif",
    fontWeight: 500,
    fontSize: "12px",
    lineHeight: "16px",
    letterSpacing: "0.005em",
  },
  titles: {
    fontFamily: "InterVariable, Inter, -apple-system, system-ui, sans-serif",
    fontWeight: 700,
    fontSize: "12px",
    lineHeight: "16px",
    letterSpacing: "0.01em",
  },
  small: {
    fontFamily: "InterVariable, Inter, -apple-system, system-ui, sans-serif",
    fontWeight: 400,
    fontSize: "10px",
    lineHeight: "11px",
    letterSpacing: "0.01em",
  },
  tiny: {
    fontFamily: "InterVariable, Inter, -apple-system, system-ui, sans-serif",
    fontWeight: 500,
    fontSize: "8px",
    lineHeight: "8px",
    letterSpacing: "0.01em",
  },
  unit: {
    fontFamily: "InterVariable, Inter, -apple-system, system-ui, sans-serif",
    fontWeight: 500,
    fontSize: "10px",
    lineHeight: "12px",
    letterSpacing: "0em",
  },
  mono: {
    fontFamily: "Roboto, menlo, monospace",
    fontWeight: 400,
    fontSize: "12px",
    lineHeight: "16px",
    letterSpacing: "0.01em",
  },
  bigTitle: {
    fontFamily: "InterVariable, Inter, -apple-system, system-ui, sans-serif",
    fontWeight: 500,
    fontSize: "32px",
    lineHeight: "39px",
    letterSpacing: "0.005em",
  },
  spaceSectionUnitText: {
    fontFamily: "InterVariable, Inter, -apple-system, system-ui, sans-serif",
    fontWeight: 600,
    fontSize: "8px",
    lineHeight: "8px",
    letterSpacing: "0.01em",
  },
  spaceSectionValueText: {
    fontFamily: "InterVariable, Inter, -apple-system, system-ui, sans-serif",
    fontWeight: 500,
    fontSize: "10px",
    lineHeight: "10px",
    letterSpacing: "0.01em",
  },
  brandSectionTitle: {
    fontFamily: "ManropeVariable, Manrope, sans-serif",
    fontWeight: 700,
    fontSize: "20px",
    lineHeight: "27px",
    letterSpacing: "0em",
  },
  brandLargeTitle: {
    fontFamily: "ManropeVariable, Manrope, sans-serif",
    fontWeight: 700,
    fontSize: "48px",
    lineHeight: "58px",
    letterSpacing: "-0.02em",
  },
  brandRegular: {
    fontFamily: "ManropeVariable, Manrope, sans-serif",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "22px",
    letterSpacing: "0em",
  },
} as const;

export const textCase = {
  none: "none",
  uppercase: "uppercase",
  capitalize: "capitalize",
} as const;

export const textDecoration = { none: "none" } as const;

export const borderRadius = {
  radius0: "1px",
  radius1: "2px",
  radius2: "3px",
  radius3: "4px",
  radius4: "5px",
  radius5: "6px",
} as const;

export const color = {
  white: "#ffffff",
  black: "#000000",
  backgroundPanel: "#f8f8f8",
  backgroundPrimary: "#0081f1",
  backgroundHover: "#dfe3e6",
  backgroundActive: "#0081f1",
  backgroundMenu: "#ededed",
  backgroundControls: "#ffffff",
  backgroundAssetcardHover: "#e6e8eb",
  backgroundNeutralMain: "#d7dbdf",
  backgroundNeutralAccent: "#11181c",
  backgroundNeutralNotification: "#ffffff",
  backgroundDestructiveMain: "#dc3d43",
  backgroundDestructiveNotification: "#ffefef",
  backgroundSuccessMain: "#299764",
  backgroundSuccessNotification: "#e9f9ee",
  backgroundAlertMain: "#f5d90a",
  backgroundAlertNotification: "#fffbd1",
  backgroundInfoMain: "#006adc",
  backgroundInfoNotification: "#edf6ff",
  backgroundPresetMain: "#e6e8eb",
  backgroundPresetHover: "#dfe3e6",
  backgroundSetMain: "#e1f0ff",
  backgroundSetHover: "#cee7fe",
  backgroundInheritedMain: "#ffe8d7",
  backgroundInheritedHover: "#ffdcc3",
  backgroundInputSelected: "#b7d9f8",
  backgroundInputDisabled: "#f8f8f8",
  backgroundButtonHover: "#ffffff17",
  backgroundButtonPressed: "#0000001c",
  backgroundButtonDisabled: "#dfe3e6",
  backgroundItemCurrent: "#0081f1",
  backgroundItemCurrentChild: "#e1f0ff",
  backgroundItemCurrentHidden: "#7e868c",
  backgroundItemMenuItemHover: "#cdcdcd",
  backgroundTooltipMain: "#11181c",
  backgroundTooltipDesigner: "#ffffff",
  backgroundSpacingTopBottom: "#f1f3f5",
  backgroundSpacingLeftRight: "#eceef0",
  backgroundSpacingHover: "#d7dbdf",
  backgroundStyleSourceToken: "#0081f1",
  backgroundStyleSourceTag: "#d23197",
  backgroundStyleSourceState: "#299764",
  backgroundStyleSourceNeutral: "#687076",
  backgroundStyleSourceDisabled: "#9da2a6",
  backgroundStyleSourceGradientToken:
    "linear-gradient(90deg, #0081f100 0%, #0081f1 31.87%)",
  backgroundStyleSourceGradientTag:
    "linear-gradient(90deg, #d2319700 0%, #d23197 31.87%)",
  backgroundStyleSourceGradientState:
    "linear-gradient(90deg, #29976400 0%, #299764 31.87%)",
  brandBackgroundProjectCardFront:
    "linear-gradient(0deg, #fbf8ff 25%, #e2e2e2 66%)",
  brandBackgroundProjectCardBack:
    "linear-gradient(0deg, #fbf8ff 0%, #c7c7c7 100%)",
  brandBackgroundProjectCardTextArea: "#ffffffe6",
  brandBackgroundPublishedMain: "#39fbbb",
  brandBackgroundGradient: "linear-gradient(180deg, #e63cfe 0%, #ffae3c 100%)",
  brandBackgroundPublishedContrast: "#ebfffc",
  brandBackgroundDashboard: "#ededed",
  brandForegroundPublished: "#005406",
  brandBorderPublished: "#ebfffc",
  borderMain: "#c1c8cd",
  borderFocus: "#0081f1",
  borderMenuInner: "#fcfcfc",
  borderColorSwatch: "#687076",
  borderNeutral: "#e8e8e8",
  borderSuccess: "#30a46c",
  borderAlert: "#f5d90a",
  borderInfo: "#0091ff",
  borderContrast: "#ffffff",
  borderItemChildLine: "#889096",
  borderItemChildLineCurrent: "#96c7f2",
  borderSetMain: "#b7d9f8",
  borderSetFlexUi: "#0091ff",
  borderInheritedMain: "#ffcca7",
  borderInheritedFlexUi: "#fa934e",
  borderDestructiveMain: "#dc3d43",
  borderDestructiveNotification: "#f9c6c6",
  foregroundMain: "#11181c",
  foregroundSubtle: "#7e868c",
  foregroundCategoryLabel: "#889096",
  foregroundTextSubtle: "#687076",
  foregroundDestructive: "#dc3d43",
  foregroundSuccess: "#008846",
  foregroundInfo: "#006adc",
  foregroundDisabled: "#c1c8cd",
  foregroundHiddenItem: "#7e868c",
  foregroundFlexUiMain: "#c7c7c7",
  foregroundFlexUiHover: "#96c7f2",
  foregroundContrastMain: "#ffffff",
  foregroundContrastSubtle: "#c1c8cd",
  foregroundSetMain: "#006adc",
  foregroundSetFlexUi: "#0091ff",
  foregroundInheritedMain: "#bd4b00",
  foregroundInheritedFlexUi: "#fa934e",
  maintenanceLight: "#ededed",
  maintenanceMedium: "#c7c7c7",
  maintenanceDark: "#858585",
  maintenanceSpacerViz: "#f9c6c6",
} as const;

export const borderWidth = { borderWidth0: 1, borderWidth1: 2 } as const;

export const dimension = { paragraphIndent0: "0px" } as const;

export const other = { tokenSetOrder0: "global" } as const;
